# Generated by Django 4.0.3 on 2024-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_seshat_task_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seshat_expert',
            name='role',
            field=models.CharField(blank=True, choices=[('Seshat Admin', 'Seshat Admin'), ('RA', 'Seshat Researcher'), ('Seshat Expert', 'Seshat Expert')], max_length=60, null=True),
        ),
    ]
