# Generated by Django 4.0.3 on 2025-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_seshat_expert_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seshat_expert',
            name='role',
            field=models.CharField(blank=True, choices=[('Seshat Admin', 'Seshat Admin'), ('Researcher', 'Researcher'), ('Seshat Expert', 'Seshat Expert'), ('Lead Researcher', 'Lead Researcher'), ('Seshat Director', 'Seshat Director'), ('Project Manager', 'Project Manager')], max_length=60, null=True),
        ),
    ]
