from django.urls import path

from .models import (
    Us_violence,
    Us_location,
    Us_violence_subtype,
    Us_violence_data_source,
    Power_transition,
)
from . import views
from .specific_views import downloads


urlpatterns = [
    path("vars/", views.qing_vars_view, name="qing_vars"),
    path("playground/", views.playground, name="playground"),
    path(
        "playgrounddownload/",
        views.playgrounddownload_view,
        name="playgrounddownload",
    ),
    # US
    path(
        "us_locations/",
        views.UsLocationListView.as_view(),
        name="us_location_list",
    ),
    path(
        "us_locations/create/",
        views.UsLocationCreateView.as_view(),
        name="us_location_create",
    ),
    path(
        "us_locations/<int:pk>/update/",
        views.UsLocationUpdateView.as_view(),
        name="us_location_update",
    ),
    path(
        "subtypes/",
        views.UsViolenceSubtypeListView.as_view(),
        name="subtype_list",
    ),
    path(
        "subtypes/create/",
        views.UsViolenceSubtypeCreateView.as_view(),
        name="subtype_create",
    ),
    path(
        "subtypes/<int:pk>/update/",
        views.UsViolenceSubtypeUpdateView.as_view(),
        name="subtype_update",
    ),
    path(
        "datasources/",
        views.UsViolenceDataSourceListView.as_view(),
        name="datasource_list",
    ),
    path(
        "datasources/create/",
        views.UsViolenceDataSourceCreateView.as_view(),
        name="datasource_create",
    ),
    path(
        "datasources/<int:pk>/update/",
        views.UsViolenceDataSourceUpdateView.as_view(),
        name="datasource_update",
    ),
    path(
        "uspvdb_all/",
        views.UsViolenceListView.as_view(),
        name="us_violence_list",
    ),
    path(
        "uspvdb/",
        views.UsViolenceListViewPaginated.as_view(),
        name="us_violence_paginated",
    ),
    path(
        "uspvdb/create/",
        views.UsViolenceCreateView.as_view(),
        name="us_violence_create",
    ),
    path(
        "uspvdb/<int:pk>/update/",
        views.UsViolenceUpdateView.as_view(),
        name="us_violence_update",
    ),
    path(
        "uspvdb_download/",
        downloads.us_violence_download_view,
        name="us_violence_download",
    ),
    # CrisisDB
    path(
        "crisis_consequence/create/",
        views.Crisis_consequenceCreateView.as_view(),
        name="crisis_consequence-create",
    ),
    path(
        "crisis_consequence/createheavy/",
        views.Crisis_consequenceCreateHeavyView.as_view(),
        name="crisis_consequence-create_heavy",
    ),
    path(
        "crisis_consequences/",
        views.Crisis_consequenceListView.as_view(),
        name="crisis_consequences",
    ),
    path(
        "crisis_consequences_all/",
        views.Crisis_consequenceListAllView.as_view(),
        name="crisis_consequences_all",
    ),
    path(
        "crisis_consequence/<int:pk>",
        views.Crisis_consequenceDetailView.as_view(),
        name="crisis_consequence-detail",
    ),
    path(
        "crisis_consequence/<int:pk>/update/",
        views.Crisis_consequenceUpdateView.as_view(),
        name="crisis_consequence-update",
    ),
    path(
        "crisis_consequence/<int:pk>/updateheavy/",
        views.Crisis_consequenceUpdateHeavyView.as_view(),
        name="crisis_consequence-update_heavy",
    ),
    path(
        "crisis_consequence/<int:pk>/delete/",
        views.Crisis_consequenceDeleteView.as_view(),
        name="crisis_consequence-delete",
    ),
    path(
        "crisis_consequencedownload/",
        downloads.crisis_consequence_download_view,
        name="crisis_consequence-download",
    ),
    path(
        "crisis_consequencemetadownload/",
        downloads.crisis_consequence_meta_download_view,
        name="crisis_consequence-metadownload",
    ),
    path(
        "get-citations-dropdown/",
        views.get_citations_dropdown_view,
        name="get_citations_dropdown_view",
    ),
    path(
        "power_transition/create/",
        views.Power_transitionCreateView.as_view(),
        name="power_transition-create",
    ),
    path(
        "power_transition/createheavy/",
        views.Power_transitionCreateHeavyView.as_view(),
        name="power_transition-create_heavy",
    ),
    path(
        "power_transitions/",
        views.Power_transitionListView.as_view(),
        name="power_transitions",
    ),
    path(
        "power_transitions_list_all/",
        views.Power_transitionListAllView.as_view(),
        name="power_transition_list",
    ),
    path(
        "power_transitions_all/",
        views.Power_transitionListAllView.as_view(),
        name="power_transitions_all",
    ),
    path(
        "power_transition/<int:pk>",
        views.Power_transitionDetailView.as_view(),
        name="power_transition-detail",
    ),
    path(
        "power_transition/<int:pk>/update/",
        views.Power_transitionUpdateView.as_view(),
        name="power_transition-update",
    ),
    path(
        "power_transition/<int:pk>/updateheavy/",
        views.Power_transitionUpdateHeavyView.as_view(),
        name="power_transition-update_heavy",
    ),
    path(
        "power_transitiondownload/",
        downloads.power_transition_download_view,
        name="power_transition-download",
    ),
    path(
        "power_transitionmetadownload/",
        downloads.power_transition_meta_download_view,
        name="power_transition-metadownload",
    ),
    # Human Sacrifice
    path(
        "human_sacrifice/create/",
        views.Human_sacrificeCreateView.as_view(),
        name="human_sacrifice-create",
    ),
    path(
        "human_sacrifices/",
        views.Human_sacrificeListView.as_view(),
        name="human_sacrifices",
    ),
    path(
        "human_sacrifices_all/",
        views.Human_sacrificeListAllView.as_view(),
        name="human_sacrifices_all",
    ),
    path(
        "human_sacrifice/<int:pk>",
        views.Human_sacrificeDetailView.as_view(),
        name="human_sacrifice-detail",
    ),
    path(
        "human_sacrifice/<int:pk>/update/",
        views.Human_sacrificeUpdateView.as_view(),
        name="human_sacrifice-update",
    ),
    path(
        "human_sacrifice/<int:pk>/delete/",
        views.Human_sacrificeDeleteView.as_view(),
        name="human_sacrifice-delete",
    ),
    path(
        "human_sacrificedownload/",
        downloads.human_sacrifice_download_view,
        name="human_sacrifice-download",
    ),
    path(
        "human_sacrificemetadownload/",
        downloads.human_sacrifice_meta_download_view,
        name="human_sacrifice-metadownload",
    ),
    path(
        "create_subcomment/<int:hs_instance_id>/",
        views.create_a_comment_with_a_subcomment,
        name="create_subcomment",
    ),
    # External conflict
    path(
        "external_conflict/create/",
        views.External_conflictCreateView.as_view(),
        name="external_conflict-create",
    ),
    path(
        "external_conflicts/",
        views.External_conflictListView.as_view(),
        name="external_conflicts",
    ),
    path(
        "external_conflict/<int:pk>",
        views.External_conflictDetailView.as_view(),
        name="external_conflict-detail",
    ),
    path(
        "external_conflict/<int:pk>/update/",
        views.External_conflictUpdateView.as_view(),
        name="external_conflict-update",
    ),
    path(
        "external_conflict/<int:pk>/delete/",
        views.External_conflictDeleteView.as_view(),
        name="external_conflict-delete",
    ),
    path(
        "external_conflictdownload/",
        downloads.external_conflict_download_view,
        name="external_conflict-download",
    ),
    path(
        "external_conflictmetadownload/",
        downloads.external_conflict_meta_download_view,
        name="external_conflict-metadownload",
    ),
    path(
        "external_conflict_side/create/",
        views.External_conflict_sideCreateView.as_view(),
        name="external_conflict_side-create",
    ),
    path(
        "external_conflict_sides/",
        views.External_conflict_sideListView.as_view(),
        name="external_conflict_sides",
    ),
    path(
        "external_conflict_side/<int:pk>",
        views.External_conflict_sideDetailView.as_view(),
        name="external_conflict_side-detail",
    ),
    path(
        "external_conflict_side/<int:pk>/update/",
        views.External_conflict_sideUpdateView.as_view(),
        name="external_conflict_side-update",
    ),
    path(
        "external_conflict_side/<int:pk>/delete/",
        views.External_conflict_sideDeleteView.as_view(),
        name="external_conflict_side-delete",
    ),
    path(
        "external_conflict_sidedownload/",
        downloads.external_conflict_side_download_view,
        name="external_conflict_side-download",
    ),
    path(
        "external_conflict_sidemetadownload/",
        downloads.external_conflict_side_meta_download_view,
        name="external_conflict_side-metadownload",
    ),
    # Internal conflict
    path(
        "internal_conflict/create/",
        views.Internal_conflictCreateView.as_view(),
        name="internal_conflict-create",
    ),
    path(
        "internal_conflicts/",
        views.Internal_conflictListView.as_view(),
        name="internal_conflicts",
    ),
    path(
        "internal_conflict/<int:pk>",
        views.Internal_conflictDetailView.as_view(),
        name="internal_conflict-detail",
    ),
    path(
        "internal_conflict/<int:pk>/update/",
        views.Internal_conflictUpdateView.as_view(),
        name="internal_conflict-update",
    ),
    path(
        "internal_conflict/<int:pk>/delete/",
        views.Internal_conflictDeleteView.as_view(),
        name="internal_conflict-delete",
    ),
    path(
        "internal_conflictdownload/",
        downloads.internal_conflict_download_view,
        name="internal_conflict-download",
    ),
    path(
        "internal_conflictmetadownload/",
        downloads.internal_conflict_meta_download_view,
        name="internal_conflict-metadownload",
    ),
    # Agricultural
    path(
        "agricultural_population/create/",
        views.Agricultural_populationCreateView.as_view(),
        name="agricultural_population-create",
    ),
    path(
        "agricultural_populations/",
        views.Agricultural_populationListView.as_view(),
        name="agricultural_populations",
    ),
    path(
        "agricultural_population/<int:pk>",
        views.Agricultural_populationDetailView.as_view(),
        name="agricultural_population-detail",
    ),
    path(
        "agricultural_population/<int:pk>/update/",
        views.Agricultural_populationUpdateView.as_view(),
        name="agricultural_population-update",
    ),
    path(
        "agricultural_population/<int:pk>/delete/",
        views.Agricultural_populationDeleteView.as_view(),
        name="agricultural_population-delete",
    ),
    path(
        "agricultural_populationdownload/",
        downloads.agricultural_population_download_view,
        name="agricultural_population-download",
    ),
    path(
        "agricultural_populationmetadownload/",
        downloads.agricultural_population_meta_download_view,
        name="agricultural_population-metadownload",
    ),
    # Arable
    path(
        "arable_land/create/",
        views.Arable_landCreateView.as_view(),
        name="arable_land-create",
    ),
    path(
        "arable_lands/",
        views.Arable_landListView.as_view(),
        name="arable_lands",
    ),
    path(
        "arable_land/<int:pk>",
        views.Arable_landDetailView.as_view(),
        name="arable_land-detail",
    ),
    path(
        "arable_land/<int:pk>/update/",
        views.Arable_landUpdateView.as_view(),
        name="arable_land-update",
    ),
    path(
        "arable_land/<int:pk>/delete/",
        views.Arable_landDeleteView.as_view(),
        name="arable_land-delete",
    ),
    path(
        "arable_landdownload/",
        downloads.arable_land_download_view,
        name="arable_land-download",
    ),
    path(
        "arable_landmetadownload/",
        downloads.arable_land_meta_download_view,
        name="arable_land-metadownload",
    ),
    path(
        "arable_land_per_farmer/create/",
        views.Arable_land_per_farmerCreateView.as_view(),
        name="arable_land_per_farmer-create",
    ),
    path(
        "arable_land_per_farmers/",
        views.Arable_land_per_farmerListView.as_view(),
        name="arable_land_per_farmers",
    ),
    path(
        "arable_land_per_farmer/<int:pk>",
        views.Arable_land_per_farmerDetailView.as_view(),
        name="arable_land_per_farmer-detail",
    ),
    path(
        "arable_land_per_farmer/<int:pk>/update/",
        views.Arable_land_per_farmerUpdateView.as_view(),
        name="arable_land_per_farmer-update",
    ),
    path(
        "arable_land_per_farmer/<int:pk>/delete/",
        views.Arable_land_per_farmerDeleteView.as_view(),
        name="arable_land_per_farmer-delete",
    ),
    path(
        "arable_land_per_farmerdownload/",
        downloads.arable_land_per_farmer_download_view,
        name="arable_land_per_farmer-download",
    ),
    path(
        "arable_land_per_farmermetadownload/",
        downloads.arable_land_per_farmer_meta_download_view,
        name="arable_land_per_farmer-metadownload",
    ),
    # Grains
    path(
        "gross_grain_shared_per_agricultural_population/create/",
        views.Gross_grain_shared_per_agricultural_populationCreateView.as_view(),
        name="gross_grain_shared_per_agricultural_population-create",
    ),
    path(
        "gross_grain_shared_per_agricultural_populations/",
        views.Gross_grain_shared_per_agricultural_populationListView.as_view(),
        name="gross_grain_shared_per_agricultural_populations",
    ),
    path(
        "gross_grain_shared_per_agricultural_population/<int:pk>",
        views.Gross_grain_shared_per_agricultural_populationDetailView.as_view(),
        name="gross_grain_shared_per_agricultural_population-detail",
    ),
    path(
        "gross_grain_shared_per_agricultural_population/<int:pk>/update/",
        views.Gross_grain_shared_per_agricultural_populationUpdateView.as_view(),
        name="gross_grain_shared_per_agricultural_population-update",
    ),
    path(
        "gross_grain_shared_per_agricultural_population/<int:pk>/delete/",
        views.Gross_grain_shared_per_agricultural_populationDeleteView.as_view(),
        name="gross_grain_shared_per_agricultural_population-delete",
    ),
    path(
        "gross_grain_shared_per_agricultural_populationdownload/",
        downloads.gross_grain_shared_per_agricultural_population_download_view,
        name="gross_grain_shared_per_agricultural_population-download",
    ),
    path(
        "gross_grain_shared_per_agricultural_populationmetadownload/",
        downloads.gross_grain_shared_per_agricultural_population_meta_download_view,
        name="gross_grain_shared_per_agricultural_population-metadownload",
    ),
    path(
        "net_grain_shared_per_agricultural_population/create/",
        views.Net_grain_shared_per_agricultural_populationCreateView.as_view(),
        name="net_grain_shared_per_agricultural_population-create",
    ),
    path(
        "net_grain_shared_per_agricultural_populations/",
        views.Net_grain_shared_per_agricultural_populationListView.as_view(),
        name="net_grain_shared_per_agricultural_populations",
    ),
    path(
        "net_grain_shared_per_agricultural_population/<int:pk>",
        views.Net_grain_shared_per_agricultural_populationDetailView.as_view(),
        name="net_grain_shared_per_agricultural_population-detail",
    ),
    path(
        "net_grain_shared_per_agricultural_population/<int:pk>/update/",
        views.Net_grain_shared_per_agricultural_populationUpdateView.as_view(),
        name="net_grain_shared_per_agricultural_population-update",
    ),
    path(
        "net_grain_shared_per_agricultural_population/<int:pk>/delete/",
        views.Net_grain_shared_per_agricultural_populationDeleteView.as_view(),
        name="net_grain_shared_per_agricultural_population-delete",
    ),
    path(
        "net_grain_shared_per_agricultural_populationdownload/",
        downloads.net_grain_shared_per_agricultural_population_download_view,
        name="net_grain_shared_per_agricultural_population-download",
    ),
    path(
        "net_grain_shared_per_agricultural_populationmetadownload/",
        downloads.net_grain_shared_per_agricultural_population_meta_download_view,
        name="net_grain_shared_per_agricultural_population-metadownload",
    ),
    # Surplus
    path(
        "surplus/create/",
        views.SurplusCreateView.as_view(),
        name="surplus-create",
    ),
    path("surplus/", views.SurplusListView.as_view(), name="surplus"),
    path(
        "surplus/<int:pk>",
        views.SurplusDetailView.as_view(),
        name="surplus-detail",
    ),
    path(
        "surplus/<int:pk>/update/",
        views.SurplusUpdateView.as_view(),
        name="surplus-update",
    ),
    path(
        "surplus/<int:pk>/delete/",
        views.SurplusDeleteView.as_view(),
        name="surplus-delete",
    ),
    path(
        "surplusdownload/",
        downloads.surplus_download_view,
        name="surplus-download",
    ),
    path(
        "surplusmetadownload/",
        downloads.surplus_meta_download_view,
        name="surplus-metadownload",
    ),
    # Military expense
    path(
        "military_expense/create/",
        views.Military_expenseCreateView.as_view(),
        name="military_expense-create",
    ),
    path(
        "military_expenses/",
        views.Military_expenseListView.as_view(),
        name="military_expenses",
    ),
    path(
        "military_expense/<int:pk>",
        views.Military_expenseDetailView.as_view(),
        name="military_expense-detail",
    ),
    path(
        "military_expense/<int:pk>/update/",
        views.Military_expenseUpdateView.as_view(),
        name="military_expense-update",
    ),
    path(
        "military_expense/<int:pk>/delete/",
        views.Military_expenseDeleteView.as_view(),
        name="military_expense-delete",
    ),
    path(
        "military_expensedownload/",
        downloads.military_expense_download_view,
        name="military_expense-download",
    ),
    path(
        "military_expensemetadownload/",
        downloads.military_expense_meta_download_view,
        name="military_expense-metadownload",
    ),
    # Silver
    path(
        "silver_inflow/create/",
        views.Silver_inflowCreateView.as_view(),
        name="silver_inflow-create",
    ),
    path(
        "silver_inflows/",
        views.Silver_inflowListView.as_view(),
        name="silver_inflows",
    ),
    path(
        "silver_inflow/<int:pk>",
        views.Silver_inflowDetailView.as_view(),
        name="silver_inflow-detail",
    ),
    path(
        "silver_inflow/<int:pk>/update/",
        views.Silver_inflowUpdateView.as_view(),
        name="silver_inflow-update",
    ),
    path(
        "silver_inflow/<int:pk>/delete/",
        views.Silver_inflowDeleteView.as_view(),
        name="silver_inflow-delete",
    ),
    path(
        "silver_inflowdownload/",
        downloads.silver_inflow_download_view,
        name="silver_inflow-download",
    ),
    path(
        "silver_inflowmetadownload/",
        downloads.silver_inflow_meta_download_view,
        name="silver_inflow-metadownload",
    ),
    path(
        "silver_stock/create/",
        views.Silver_stockCreateView.as_view(),
        name="silver_stock-create",
    ),
    path(
        "silver_stocks/",
        views.Silver_stockListView.as_view(),
        name="silver_stocks",
    ),
    path(
        "silver_stock/<int:pk>",
        views.Silver_stockDetailView.as_view(),
        name="silver_stock-detail",
    ),
    path(
        "silver_stock/<int:pk>/update/",
        views.Silver_stockUpdateView.as_view(),
        name="silver_stock-update",
    ),
    path(
        "silver_stock/<int:pk>/delete/",
        views.Silver_stockDeleteView.as_view(),
        name="silver_stock-delete",
    ),
    path(
        "silver_stockdownload/",
        downloads.silver_stock_download_view,
        name="silver_stock-download",
    ),
    path(
        "silver_stockmetadownload/",
        downloads.silver_stock_meta_download_view,
        name="silver_stock-metadownload",
    ),
    # Population
    path(
        "total_population/create/",
        views.Total_populationCreateView.as_view(),
        name="total_population-create",
    ),
    path(
        "total_populations/",
        views.Total_populationListView.as_view(),
        name="total_populations",
    ),
    path(
        "total_population/<int:pk>",
        views.Total_populationDetailView.as_view(),
        name="total_population-detail",
    ),
    path(
        "total_population/<int:pk>/update/",
        views.Total_populationUpdateView.as_view(),
        name="total_population-update",
    ),
    path(
        "total_population/<int:pk>/delete/",
        views.Total_populationDeleteView.as_view(),
        name="total_population-delete",
    ),
    path(
        "total_populationdownload/",
        downloads.total_population_download_view,
        name="total_population-download",
    ),
    path(
        "total_populationmetadownload/",
        downloads.total_population_meta_download_view,
        name="total_population-metadownload",
    ),
    # GDP
    path(
        "gdp_per_capita/create/",
        views.Gdp_per_capitaCreateView.as_view(),
        name="gdp_per_capita-create",
    ),
    path(
        "gdp_per_capitas/",
        views.Gdp_per_capitaListView.as_view(),
        name="gdp_per_capitas",
    ),
    path(
        "gdp_per_capita/<int:pk>",
        views.Gdp_per_capitaDetailView.as_view(),
        name="gdp_per_capita-detail",
    ),
    path(
        "gdp_per_capita/<int:pk>/update/",
        views.Gdp_per_capitaUpdateView.as_view(),
        name="gdp_per_capita-update",
    ),
    path(
        "gdp_per_capita/<int:pk>/delete/",
        views.Gdp_per_capitaDeleteView.as_view(),
        name="gdp_per_capita-delete",
    ),
    path(
        "gdp_per_capitadownload/",
        downloads.gdp_per_capita_download_view,
        name="gdp_per_capita-download",
    ),
    path(
        "gdp_per_capitametadownload/",
        downloads.gdp_per_capita_meta_download_view,
        name="gdp_per_capita-metadownload",
    ),
    # Drought
    path(
        "drought_event/create/",
        views.Drought_eventCreateView.as_view(),
        name="drought_event-create",
    ),
    path(
        "drought_events/",
        views.Drought_eventListView.as_view(),
        name="drought_events",
    ),
    path(
        "drought_event/<int:pk>",
        views.Drought_eventDetailView.as_view(),
        name="drought_event-detail",
    ),
    path(
        "drought_event/<int:pk>/update/",
        views.Drought_eventUpdateView.as_view(),
        name="drought_event-update",
    ),
    path(
        "drought_event/<int:pk>/delete/",
        views.Drought_eventDeleteView.as_view(),
        name="drought_event-delete",
    ),
    path(
        "drought_eventdownload/",
        downloads.drought_event_download_view,
        name="drought_event-download",
    ),
    path(
        "drought_eventmetadownload/",
        downloads.drought_event_meta_download_view,
        name="drought_event-metadownload",
    ),
    # Locust
    path(
        "locust_event/create/",
        views.Locust_eventCreateView.as_view(),
        name="locust_event-create",
    ),
    path(
        "locust_events/",
        views.Locust_eventListView.as_view(),
        name="locust_events",
    ),
    path(
        "locust_event/<int:pk>",
        views.Locust_eventDetailView.as_view(),
        name="locust_event-detail",
    ),
    path(
        "locust_event/<int:pk>/update/",
        views.Locust_eventUpdateView.as_view(),
        name="locust_event-update",
    ),
    path(
        "locust_event/<int:pk>/delete/",
        views.Locust_eventDeleteView.as_view(),
        name="locust_event-delete",
    ),
    path(
        "locust_eventdownload/",
        downloads.locust_event_download_view,
        name="locust_event-download",
    ),
    path(
        "locust_eventmetadownload/",
        downloads.locust_event_meta_download_view,
        name="locust_event-metadownload",
    ),
    # Socioeconomic turmoil
    path(
        "socioeconomic_turmoil_event/create/",
        views.Socioeconomic_turmoil_eventCreateView.as_view(),
        name="socioeconomic_turmoil_event-create",
    ),
    path(
        "socioeconomic_turmoil_events/",
        views.Socioeconomic_turmoil_eventListView.as_view(),
        name="socioeconomic_turmoil_events",
    ),
    path(
        "socioeconomic_turmoil_event/<int:pk>",
        views.Socioeconomic_turmoil_eventDetailView.as_view(),
        name="socioeconomic_turmoil_event-detail",
    ),
    path(
        "socioeconomic_turmoil_event/<int:pk>/update/",
        views.Socioeconomic_turmoil_eventUpdateView.as_view(),
        name="socioeconomic_turmoil_event-update",
    ),
    path(
        "socioeconomic_turmoil_event/<int:pk>/delete/",
        views.Socioeconomic_turmoil_eventDeleteView.as_view(),
        name="socioeconomic_turmoil_event-delete",
    ),
    path(
        "socioeconomic_turmoil_eventdownload/",
        downloads.socioeconomic_turmoil_event_download_view,
        name="socioeconomic_turmoil_event-download",
    ),
    path(
        "socioeconomic_turmoil_eventmetadownload/",
        downloads.socioeconomic_turmoil_event_meta_download_view,
        name="socioeconomic_turmoil_event-metadownload",
    ),
    # Crop failure
    path(
        "crop_failure_event/create/",
        views.Crop_failure_eventCreateView.as_view(),
        name="crop_failure_event-create",
    ),
    path(
        "crop_failure_events/",
        views.Crop_failure_eventListView.as_view(),
        name="crop_failure_events",
    ),
    path(
        "crop_failure_event/<int:pk>",
        views.Crop_failure_eventDetailView.as_view(),
        name="crop_failure_event-detail",
    ),
    path(
        "crop_failure_event/<int:pk>/update/",
        views.Crop_failure_eventUpdateView.as_view(),
        name="crop_failure_event-update",
    ),
    path(
        "crop_failure_event/<int:pk>/delete/",
        views.Crop_failure_eventDeleteView.as_view(),
        name="crop_failure_event-delete",
    ),
    path(
        "crop_failure_eventdownload/",
        downloads.crop_failure_event_download_view,
        name="crop_failure_event-download",
    ),
    path(
        "crop_failure_eventmetadownload/",
        downloads.crop_failure_event_meta_download_view,
        name="crop_failure_event-metadownload",
    ),
    # Famine
    path(
        "famine_event/create/",
        views.Famine_eventCreateView.as_view(),
        name="famine_event-create",
    ),
    path(
        "famine_events/",
        views.Famine_eventListView.as_view(),
        name="famine_events",
    ),
    path(
        "famine_event/<int:pk>",
        views.Famine_eventDetailView.as_view(),
        name="famine_event-detail",
    ),
    path(
        "famine_event/<int:pk>/update/",
        views.Famine_eventUpdateView.as_view(),
        name="famine_event-update",
    ),
    path(
        "famine_event/<int:pk>/delete/",
        views.Famine_eventDeleteView.as_view(),
        name="famine_event-delete",
    ),
    path(
        "famine_eventdownload/",
        downloads.famine_event_download_view,
        name="famine_event-download",
    ),
    path(
        "famine_eventmetadownload/",
        downloads.famine_event_meta_download_view,
        name="famine_event-metadownload",
    ),
    # Disease outbreak
    path(
        "disease_outbreak/create/",
        views.Disease_outbreakCreateView.as_view(),
        name="disease_outbreak-create",
    ),
    path(
        "disease_outbreaks/",
        views.Disease_outbreakListView.as_view(),
        name="disease_outbreaks",
    ),
    path(
        "disease_outbreak/<int:pk>",
        views.Disease_outbreakDetailView.as_view(),
        name="disease_outbreak-detail",
    ),
    path(
        "disease_outbreak/<int:pk>/update/",
        views.Disease_outbreakUpdateView.as_view(),
        name="disease_outbreak-update",
    ),
    path(
        "disease_outbreak/<int:pk>/delete/",
        views.Disease_outbreakDeleteView.as_view(),
        name="disease_outbreak-delete",
    ),
    path(
        "disease_outbreakdownload/",
        downloads.disease_outbreak_download_view,
        name="disease_outbreak-download",
    ),
    path(
        "disease_outbreakmetadownload/",
        downloads.disease_outbreak_meta_download_view,
        name="disease_outbreak-metadownload",
    ),
]


"""
Programmatically create the following URL patterns for each model:
- /model_name/<int:pk>/confirm-delete
- /model_name/<int:pk>/delete/
"""
model_form_pairs = [
    (
        Us_location,
        "us_location",
    ),
    (
        Us_violence,
        "us_violence",
    ),
    (
        Us_violence_subtype,
        "us_violence_subtype",
    ),
    (
        Us_violence_data_source,
        "us_violence_data_source",
    ),
    (
        Power_transition,
        "power_transition",
    ),
]

for model_class, x_name in model_form_pairs:
    urlpatterns.append(
        path(
            f"{x_name}/<int:pk>/confirm-delete/",
            views.generic_confirm_delete_view,
            {
                "model_class": model_class,
                "var_name": x_name,
            },
            name=f"{x_name}-confirm-delete",
        )
    )

    urlpatterns.append(
        path(
            f"{x_name}/<int:pk>/delete/",
            views.generic_delete_object_view,
            {
                "model_class": model_class,
                "var_name": x_name,
            },
            name=f"{x_name}-delete",
        )
    )
