# Generated by Django 4.2.14 on 2024-09-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seshat_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="track",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="track",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Track",
        ),
    ]
