# Generated by Django 4.0.3 on 2024-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_videoshapefile_cliopatria'),
        ('wf', '0005_atlatl_private_comment_battle_axe_private_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlatl',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='atlatl',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='battle_axe',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='battle_axe',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='breastplate',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='breastplate',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='bronze',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='bronze',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='camel',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='camel',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='chainmail',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='chainmail',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='complex_fortification',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='complex_fortification',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='composite_bow',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='composite_bow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='copper',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='copper',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crossbow',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='crossbow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='dagger',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='dagger',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='ditch',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='ditch',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='dog',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='donkey',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='donkey',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='earth_rampart',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='earth_rampart',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='fortified_camp',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='fortified_camp',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gunpowder_siege_artillery',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gunpowder_siege_artillery',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='handheld_firearm',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='handheld_firearm',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='horse',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='iron',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='iron',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='laminar_armor',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='laminar_armor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='leather_cloth',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='leather_cloth',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='limb_protection',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='limb_protection',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='long_wall',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='long_wall',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='merchant_ships_pressed_into_service',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='merchant_ships_pressed_into_service',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='moat',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='moat',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='modern_fortification',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='modern_fortification',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='plate_armor',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='plate_armor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polearm',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polearm',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='scaled_armor',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='scaled_armor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='self_bow',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='self_bow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='settlements_in_a_defensive_position',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='settlements_in_a_defensive_position',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='shield',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='sling',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='sling',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='sling_siege_engine',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='sling_siege_engine',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='small_vessels_canoes_etc',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='small_vessels_canoes_etc',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='spear',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='spear',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='specialized_military_vessel',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='specialized_military_vessel',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='steel',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='steel',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='stone_walls_mortared',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='stone_walls_mortared',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='stone_walls_non_mortared',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='stone_walls_non_mortared',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='sword',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='sword',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='tension_siege_engine',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='tension_siege_engine',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='war_club',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='war_club',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='wood_bark_etc',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='wood_bark_etc',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='wooden_palisade',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='wooden_palisade',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
    ]
