# Generated by Django 4.0.3 on 2024-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_videoshapefile_cliopatria'),
        ('general', '0018_polity_preceding_entity_relationship_to_preceding_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity_alternate_religion',
            name='alternate_religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Shadhil', 'Shadhil'), ('Karrami', 'Karrami'), ('Hanafi', 'Hanafi'), ('Mevlevi', 'Mevlevi'), ('Ismaili', 'Ismaili'), ('Shafii', 'Shafii'), ('Shia', 'Shia'), ('Twelver', 'Twelver'), ('Byzantine Orthodox', 'Byzantine Orthodox'), ('Bektasi', 'Bektasi'), ('uncoded', 'uncoded'), ('Sunni', 'Sunni'), ('Roman Catholic', 'Roman Catholic')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_family',
            name='alternate_religion_family',
            field=models.CharField(choices=[('Saivist Traditions', 'Saivist Traditions'), ('Assyrian Religions', 'Assyrian Religions'), ('Republican Religions', 'Republican Religions'), ('Imperial Confucian Traditions', 'Imperial Confucian Traditions'), ('Shii', 'Shii'), ('Bhagavatist Traditions', 'Bhagavatist Traditions'), ('Sunni', 'Sunni'), ('Vedist Traditions', 'Vedist Traditions'), ('Saivist', 'Saivist'), ('Islam', 'Islam'), ('Chinese Folk Religion', 'Chinese Folk Religion'), ('Semitic', 'Semitic'), ('Vaisnava Traditions', 'Vaisnava Traditions'), ('Ptolemaic Religion', 'Ptolemaic Religion'), ('Vedic Traditions', 'Vedic Traditions'), ('Japanese Buddhism', 'Japanese Buddhism'), ('Orthodox', 'Orthodox'), ('Vaishnava Traditions', 'Vaishnava Traditions'), ('Shang Religion', 'Shang Religion'), ('Atenism', 'Atenism'), ('Mahayana', 'Mahayana'), ('unknown', 'unknown'), ('Japanese State Shinto', 'Japanese State Shinto'), ('Saiva Traditions', 'Saiva Traditions'), ('Sufi', 'Sufi'), ('Chinese Buddhist Traditions', 'Chinese Buddhist Traditions'), ('Arian', 'Arian'), ('Shia', 'Shia'), ('Catholic', 'Catholic'), ('Western Zhou Religion', 'Western Zhou Religion'), ('Imperial Cult', 'Imperial Cult'), ('Theravada', 'Theravada'), ('Seleucid Religion', 'Seleucid Religion'), ('Saivite Hinduism', 'Saivite Hinduism'), ('Theravada Buddhism', 'Theravada Buddhism'), ('Theravāda Buddhism', 'Theravāda Buddhism'), ('Protestant Christianity', 'Protestant Christianity'), ('Saivist Hinduism', 'Saivist Hinduism'), ('Sunni Islam', 'Sunni Islam'), ('Shia Islam', 'Shia Islam'), ('Vodun', 'Vodun'), ('Dahomey royal ancestor cult', 'Dahomey royal ancestor cult'), ('Shaivist', 'Shaivist'), ('Shaivism', 'Shaivism'), ('Sufi Islam', 'Sufi Islam'), ('Shaivite Hinduism', 'Shaivite Hinduism'), ('Vaishnavist Hinduism', 'Vaishnavist Hinduism'), ('Catholicism', 'Catholicism'), ('Protestant', 'Protestant'), ('Christianity', 'Christianity'), ('Vedic', 'Vedic'), ('Church of England', 'Church of England'), ('Protestantism', 'Protestantism'), ('Zoroastrianism', 'Zoroastrianism'), ('Central Asian Shamanism', 'Central Asian Shamanism'), ('Hawaiian Religion', 'Hawaiian Religion'), ('Paganism', 'Paganism')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_family',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_genus',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternative_name',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_alternative_name',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_capital',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_capital',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_degree_of_centralization',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_degree_of_centralization',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_duration',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_duration',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_editor',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_editor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_expert',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_expert',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_language',
            name='language',
            field=models.CharField(choices=[('Polish', 'Polish'), ('Pashto', 'Pashto'), ('Persian', 'Persian'), ('Greek', 'Greek'), ('Bactrian', 'Bactrian'), ('Sogdian', 'Sogdian'), ('Pahlavi', 'Pahlavi'), ('Brahmi', 'Brahmi'), ('Kharoshthi', 'Kharoshthi'), ('Tocharian', 'Tocharian'), ('Chinese', 'Chinese'), ('archaic Chinese', 'archaic Chinese'), ('Xiangxi', 'Xiangxi'), ('Qiandong', 'Qiandong'), ('Chuanqiandian', 'Chuanqiandian'), ('Hmong-Mien', 'Hmong-Mien'), ('Hmongic', 'Hmongic'), ('Middle Chinese', 'Middle Chinese'), ('Jurchen', 'Jurchen'), ('Khitan', 'Khitan'), ('Xianbei', 'Xianbei'), ('Manchu language', 'Manchu language'), ('Mongolian language', 'Mongolian language'), ('Atanque', 'Atanque'), ('Shuar', 'Shuar'), ('Arabic', 'Arabic'), ('uncoded', 'uncoded'), ('Demotic', 'Demotic'), ('Ancient Egyptian', 'Ancient Egyptian'), ('Late Egyptian', 'Late Egyptian'), ('demotic Egyptian', 'demotic Egyptian'), ('Castilian Spanish', 'Castilian Spanish'), ('Chuukese', 'Chuukese'), ('French', 'French'), ('Langues dOil', 'Langues dOil'), ('Occitan', 'Occitan'), ('Latin', 'Latin'), ('Old Frankish', 'Old Frankish'), ('Germanic', 'Germanic'), ('Gallic', 'Gallic'), ('Gaulish', 'Gaulish'), ('English', 'English'), ('Akan', 'Akan'), ('Twi', 'Twi'), ('Doric Greek', 'Doric Greek'), ('Minoan', 'Minoan'), ('Early Greek', 'Early Greek'), ('Eteocretan', 'Eteocretan'), ('Old Hawaiian', 'Old Hawaiian'), ('Hawaiian', 'Hawaiian'), ('Iban', 'Iban'), ('Sanskrit', 'Sanskrit'), ('Old Javanese', 'Old Javanese'), ('Middle Javanese', 'Middle Javanese'), ('Javanese', 'Javanese'), ('Canaanite', 'Canaanite'), ('Aramaic', 'Aramaic'), ('Hebrew', 'Hebrew'), ('Kannada', 'Kannada'), ('Urdu', 'Urdu'), ('A’chik', 'A’chik'), ('Prakrit', 'Prakrit'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Akkadian', 'Akkadian'), ('Sumerian', 'Sumerian'), ('Amorite', 'Amorite'), ('Old Babylonian', 'Old Babylonian'), ('Mesopotamian Religions', 'Mesopotamian Religions'), ('Old Persian', 'Old Persian'), ('Elamite', 'Elamite'), ('Egyptian', 'Egyptian'), ('Old Elamite', 'Old Elamite'), ('Mongolian', 'Mongolian'), ('native Iranian languages', 'native Iranian languages'), ('Turkic', 'Turkic'), ('Turkish', 'Turkish'), ('Babylonian', 'Babylonian'), ('Hurrian', 'Hurrian'), ('Proto-Elamite', 'Proto-Elamite'), ('Old Norse', 'Old Norse'), ('Italian', 'Italian'), ('Middle Japanese', 'Middle Japanese'), ('Old Japanese', 'Old Japanese'), ('Late Old Japanese', 'Late Old Japanese'), ('Japanese', 'Japanese'), ('Early Modern Japanese', 'Early Modern Japanese'), ('Old Turkic', 'Old Turkic'), ('Iranian', 'Iranian'), ('Old Khmer', 'Old Khmer'), ('Mon', 'Mon'), ('Tai', 'Tai'), ('Khmer', 'Khmer'), ('Pali', 'Pali'), ('Phoenician', 'Phoenician'), ('Berber', 'Berber'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Bambara', 'Bambara'), ('Mande', 'Mande'), ('Songhay', 'Songhay'), ('Russian', 'Russian'), ('Georgian', 'Georgian'), ('Armenian', 'Armenian'), ('Kereid', 'Kereid'), ('Tatar', 'Tatar'), ('Naimans', 'Naimans'), ('Khalkha', 'Khalkha'), ('Rouran', 'Rouran'), ('Xiongnu', 'Xiongnu'), ('Oirat', 'Oirat'), ('Zapotec', 'Zapotec'), ('Icelandic', 'Icelandic'), ('Aymara', 'Aymara'), ('Puquina', 'Puquina'), ('Quechua', 'Quechua'), ('Orokaiva', 'Orokaiva'), ('unknown', 'unknown'), ('Sindhi', 'Sindhi'), ('Punjabi', 'Punjabi'), ('Sakha (Yakut)', 'Sakha (Yakut)'), ('Merotic', 'Merotic'), ('Coptic', 'Coptic'), ('Thai', 'Thai'), ('Proto-Indo-European language', 'Proto-Indo-European language'), ('Nesite', 'Nesite'), ('Luwian', 'Luwian'), ('Hattic', 'Hattic'), ('Hittite', 'Hittite'), ('Old Assyrian dialect of Akkadian', 'Old Assyrian dialect of Akkadian'), ('Indo-European language', 'Indo-European language'), ('Lydian', 'Lydian'), ('Ottoman Turkish', 'Ottoman Turkish'), ('Phrygian', 'Phrygian'), ('Miami Illinois', 'Miami Illinois'), ('Cayuga', 'Cayuga'), ('Mohawk', 'Mohawk'), ('Oneida', 'Oneida'), ('Onondaga', 'Onondaga'), ('Seneca', 'Seneca'), ('Tuscarora', 'Tuscarora'), ('Middle Mongolian', 'Middle Mongolian'), ('Ancient Iranian', 'Ancient Iranian'), ('Chagatai Turkish', 'Chagatai Turkish'), ('Sabaic', 'Sabaic'), ('Mainic', 'Mainic'), ('Qatabanic', 'Qatabanic'), ('Hadramawtic', 'Hadramawtic'), ('Old Arabic', 'Old Arabic'), ('Susu', 'Susu'), ('Koranko', 'Koranko'), ('Limba', 'Limba'), ('Temne', 'Temne'), ('Bullom', 'Bullom'), ('Loko', 'Loko'), ('Manding', 'Manding'), ('Krio', 'Krio'), ('Pulaar', 'Pulaar'), ('Kissi', 'Kissi'), ('Krim', 'Krim'), ('Vai', 'Vai'), ('Mossi', 'Mossi'), ('Shona', 'Shona'), ('Sinhala', 'Sinhala'), ('Dutch', 'Dutch'), ('Sinhalese', 'Sinhalese'), ('Oromo', 'Oromo'), ('Harari', 'Harari'), ('Argobba', 'Argobba'), ('Maay', 'Maay'), ('Somali', 'Somali'), ('Harla', 'Harla'), ('Hadiyya', 'Hadiyya'), ('Tigrinya', 'Tigrinya'), ('Funj', 'Funj'), ('Kafa', 'Kafa'), ('Yemsa', 'Yemsa'), ('Qafar', 'Qafar'), ('Proto-Yoruba', 'Proto-Yoruba'), ('Yoruba', 'Yoruba'), ('Bini', 'Bini'), ('Jukun', 'Jukun'), ('Ajagbe', 'Ajagbe'), ('Proto-Yoruboid', 'Proto-Yoruboid'), ('Sokoto', 'Sokoto'), ('Hausa', 'Hausa'), ('Idoma', 'Idoma'), ('Igbo', 'Igbo'), ('Nri', 'Nri'), ('Kanuri', 'Kanuri'), ('Kanembu', 'Kanembu'), ('Fongbe', 'Fongbe'), ('Wolof', 'Wolof'), ('Sereer', 'Sereer'), ('Fula', 'Fula'), ('Luganda', 'Luganda'), ('Kinyambo', 'Kinyambo'), ('Kinyarwanda', 'Kinyarwanda'), ('Runyankore', 'Runyankore'), ('Kirundi', 'Kirundi'), ('Fipa', 'Fipa'), ('Haya', 'Haya'), ('Old Tamil', 'Old Tamil'), ('Efik-Ibibio', 'Efik-Ibibio'), ('Hungarian', 'Hungarian'), ('Native languages', 'Native languages'), ('German', 'German'), ('Czech', 'Czech'), ('Lombardic', 'Lombardic'), ('Pukina / Puquina', 'Pukina / Puquina'), ('Old English', 'Old English'), ('Middle-Modern Persian', 'Middle-Modern Persian'), ('Anglo-Norman', 'Anglo-Norman'), ('Pictish', 'Pictish')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_language',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_language',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_language_genus',
            name='language_genus',
            field=models.CharField(choices=[('uncoded', 'uncoded'), ('Afro-Asiatic', 'Afro-Asiatic'), ('Indo-European', 'Indo-European'), ('unknown', 'unknown')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_language_genus',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_language_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_linguistic_family',
            name='linguistic_family',
            field=models.CharField(choices=[('Indo-European', 'Indo-European'), ('Sino-Tibetan', 'Sino-Tibetan'), ('uncoded', 'uncoded'), ('Tungusic', 'Tungusic'), ('Altaic', 'Altaic'), ('Mongolic', 'Mongolic'), ('Chibcha', 'Chibcha'), ('Chicham', 'Chicham'), ('Afro-Asiatic', 'Afro-Asiatic'), ('Oceanic-Austronesian', 'Oceanic-Austronesian'), ('Celtic', 'Celtic'), ('Niger-Congo', 'Niger-Congo'), ('Kwa', 'Kwa'), ('Hamito-Semitic', 'Hamito-Semitic'), ('Austronesian', 'Austronesian'), ('Malayo-Polynesian', 'Malayo-Polynesian'), ('Semitic', 'Semitic'), ('Indo-Iranian', 'Indo-Iranian'), ('Dravidian', 'Dravidian'), ('isolate language', 'isolate language'), ('West Semetic', 'West Semetic'), ('isolate', 'isolate'), ('language isolate', 'language isolate'), ('none', 'none'), ('Germanic', 'Germanic'), ('Japonic', 'Japonic'), ('Turkic', 'Turkic'), ('Austro-Asiatic, Mon-Khmer', 'Austro-Asiatic, Mon-Khmer'), ('Austro-Asiatic', 'Austro-Asiatic'), ('unknown', 'unknown'), ('Mande', 'Mande'), ('Songhay', 'Songhay'), ('Oghuz', 'Oghuz'), ('Kartvelian', 'Kartvelian'), ('Manchu-Tungusic', 'Manchu-Tungusic'), ('Proto-Mongolic', 'Proto-Mongolic'), ('Otomanguean', 'Otomanguean'), ('Proto-Otomanguean', 'Proto-Otomanguean'), ('Mixe-Zoquean', 'Mixe-Zoquean'), ('Aymaran', 'Aymaran'), ('Quechuan', 'Quechuan'), ('Papuan Languages', 'Papuan Languages'), ('Tai-Kadai', 'Tai-Kadai'), ('Algonquian', 'Algonquian'), ('Iroquois', 'Iroquois'), ('Iranian', 'Iranian'), ('Creoles and Pidgins', 'Creoles and Pidgins'), ('Indo-Aryan', 'Indo-Aryan'), ('Yoruboid', 'Yoruboid'), ('Edoid', 'Edoid'), ('Proto-Bene-Kwa', 'Proto-Bene-Kwa'), ('Chadic', 'Chadic'), ('Saharan', 'Saharan'), ('Southern Dravidian', 'Southern Dravidian'), ('Uralic', 'Uralic'), ('Romance', 'Romance'), ('West Germanic', 'West Germanic')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_linguistic_family',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_linguistic_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_original_name',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_original_name',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_peak_years',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_peak_years',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_preceding_entity',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_preceding_entity',
            name='relationship_to_preceding_entity',
            field=models.CharField(blank=True, choices=[('continuity', 'continuity'), ('elite replacement', 'elite replacement'), ('absorption', 'absorption'), ('population replacement', 'population replacement'), ('vassalage', 'vassalage'), ('unknown', 'unknown'), ('economic displacement', 'economic displacement'), ('secession', 'secession'), ('territorial consolidation', 'territorial consolidation')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='polity_preceding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_relationship_to_preceding_entity',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_relationship_to_preceding_entity',
            name='relationship_to_preceding_entity',
            field=models.CharField(choices=[('continuity', 'continuity'), ('elite replacement', 'elite replacement'), ('absorption', 'absorption'), ('population replacement', 'population replacement'), ('vassalage', 'vassalage'), ('unknown', 'unknown'), ('economic displacement', 'economic displacement'), ('secession', 'secession'), ('territorial consolidation', 'territorial consolidation')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_relationship_to_preceding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_religion',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Shadhil', 'Shadhil'), ('Karrami', 'Karrami'), ('Hanafi', 'Hanafi'), ('Mevlevi', 'Mevlevi'), ('Ismaili', 'Ismaili'), ('Shafii', 'Shafii'), ('Shia', 'Shia'), ('Twelver', 'Twelver'), ('Byzantine Orthodox', 'Byzantine Orthodox'), ('Bektasi', 'Bektasi'), ('uncoded', 'uncoded'), ('Sunni', 'Sunni'), ('Roman Catholic', 'Roman Catholic')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion_family',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_religion_family',
            name='religion_family',
            field=models.CharField(choices=[('Saivist Traditions', 'Saivist Traditions'), ('Assyrian Religions', 'Assyrian Religions'), ('Republican Religions', 'Republican Religions'), ('Imperial Confucian Traditions', 'Imperial Confucian Traditions'), ('Shii', 'Shii'), ('Bhagavatist Traditions', 'Bhagavatist Traditions'), ('Sunni', 'Sunni'), ('Vedist Traditions', 'Vedist Traditions'), ('Saivist', 'Saivist'), ('Islam', 'Islam'), ('Chinese Folk Religion', 'Chinese Folk Religion'), ('Semitic', 'Semitic'), ('Vaisnava Traditions', 'Vaisnava Traditions'), ('Ptolemaic Religion', 'Ptolemaic Religion'), ('Vedic Traditions', 'Vedic Traditions'), ('Japanese Buddhism', 'Japanese Buddhism'), ('Orthodox', 'Orthodox'), ('Vaishnava Traditions', 'Vaishnava Traditions'), ('Shang Religion', 'Shang Religion'), ('Atenism', 'Atenism'), ('Mahayana', 'Mahayana'), ('unknown', 'unknown'), ('Japanese State Shinto', 'Japanese State Shinto'), ('Saiva Traditions', 'Saiva Traditions'), ('Sufi', 'Sufi'), ('Chinese Buddhist Traditions', 'Chinese Buddhist Traditions'), ('Arian', 'Arian'), ('Shia', 'Shia'), ('Catholic', 'Catholic'), ('Western Zhou Religion', 'Western Zhou Religion'), ('Imperial Cult', 'Imperial Cult'), ('Theravada', 'Theravada'), ('Seleucid Religion', 'Seleucid Religion'), ('Saivite Hinduism', 'Saivite Hinduism'), ('Theravada Buddhism', 'Theravada Buddhism'), ('Theravāda Buddhism', 'Theravāda Buddhism'), ('Protestant Christianity', 'Protestant Christianity'), ('Saivist Hinduism', 'Saivist Hinduism'), ('Sunni Islam', 'Sunni Islam'), ('Shia Islam', 'Shia Islam'), ('Vodun', 'Vodun'), ('Dahomey royal ancestor cult', 'Dahomey royal ancestor cult'), ('Shaivist', 'Shaivist'), ('Shaivism', 'Shaivism'), ('Sufi Islam', 'Sufi Islam'), ('Shaivite Hinduism', 'Shaivite Hinduism'), ('Vaishnavist Hinduism', 'Vaishnavist Hinduism'), ('Catholicism', 'Catholicism'), ('Protestant', 'Protestant'), ('Christianity', 'Christianity'), ('Vedic', 'Vedic'), ('Church of England', 'Church of England'), ('Protestantism', 'Protestantism'), ('Zoroastrianism', 'Zoroastrianism'), ('Central Asian Shamanism', 'Central Asian Shamanism'), ('Hawaiian Religion', 'Hawaiian Religion'), ('Paganism', 'Paganism')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_religion_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion_genus',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_religion_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religious_tradition',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_religious_tradition',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_research_assistant',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_research_assistant',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_scale_of_supracultural_interaction',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_scale_of_supracultural_interaction',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_succeeding_entity',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_succeeding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_supracultural_entity',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_supracultural_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_suprapolity_relations',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_suprapolity_relations',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_utm_zone',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='polity_utm_zone',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
    ]
