# Generated by Django 4.0.3 on 2025-03-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_prec_met_instance'),
        ('general', '0022_city_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_duration',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.capital'),
        ),
    ]
