# Generated by Django 4.0.3 on 2024-07-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_country_options_alter_polity_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoShapefile',
            new_name='Cliopatria',
        ),
    ]
