# Generated by Django 4.0.3 on 2025-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_videoshapefile_cliopatria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prec_met_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='precious_metal_instance', max_length=100)),
                ('metal', models.CharField(max_length=100)),
            ],
        ),
    ]
