# Generated by Django 4.0.3 on 2025-04-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_prec_met_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_names', models.CharField(blank=True, max_length=300, null=True)),
                ('current_country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('url_on_the_map', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('private_comment_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment')),
            ],
            options={
                'ordering': ['is_verified'],
            },
        ),
        migrations.CreateModel(
            name='CityPolityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPITAL', 'Capital'), ('MAJOR', 'Major Settlement'), ('NORMAL', 'Normal Settlement')], max_length=10)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('polity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.polity')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habitationsite')),
            ],
            options={
                'verbose_name': 'Settlement-Polity Relation',
                'verbose_name_plural': 'Settlement-Polity Relations',
            },
        ),
    ]
