# Generated by Django 4.0.3 on 2025-04-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_habitationsite_citypolityrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScientificResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, help_text='List of authors, separated by commas', max_length=500, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('dataset', 'Dataset'), ('book', 'Book'), ('report', 'Report'), ('thesis', 'Thesis'), ('code', 'Code Repository'), ('other', 'Other')], default='article', max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier if available', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_peer_reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-publication_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CurrentCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g., 'AF')", max_length=2, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='core.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
