# Generated by Django 4.0.3 on 2025-04-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_continent_scientificresource_currentcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitationsite',
            name='current_country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.currentcountry'),
        ),
    ]
