# Generated by Django 4.0.3 on 2025-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_habitationsite_current_country_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablehierarchy',
            name='who_can_access',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('some_polities_are_public', 'some_polities_are_public')], default='private', max_length=50),
        ),
    ]
