# Generated by Django 4.0.3 on 2025-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_section_unique_together_section_db_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablehierarchy',
            name='api_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variablehierarchy',
            name='data_type',
            field=models.CharField(blank=True, choices=[('A/P/U/~', 'A/P/U/~'), ('RANGE', 'RANGE'), ('TEXT', 'TEXT'), ('COMPLEX', 'COMPLEX')], default='A/P/U/~', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variablehierarchy',
            name='data_type_defintion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variablehierarchy',
            name='data_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
