# Generated by Django 4.0.3 on 2025-05-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_variablehierarchy_api_endpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablehierarchy',
            old_name='data_type_defintion',
            new_name='data_type_definition',
        ),
    ]
