# Generated by Django 4.0.3 on 2025-05-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_rename_data_type_defintion_variablehierarchy_data_type_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablehierarchy',
            name='private_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment'),
        ),
    ]
