# Generated by Django 4.0.3 on 2025-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_variablehierarchy_private_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablehierarchy',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
