# Generated by Django 4.0.3 on 2025-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_variablehierarchy_canonical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variablehierarchy',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
