# Generated by Django 4.0.3 on 2025-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_section_sort_order_subsection_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='variablehierarchy',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='variablehierarchy',
            name='data_type',
            field=models.CharField(blank=True, choices=[('A/P/U/~', 'A/P/U/~'), ('RANGE', 'RANGE'), ('TEXT', 'TEXT'), ('CHOICES', 'CHOICES'), ('COMPLEX', 'COMPLEX')], default='A/P/U/~', max_length=50, null=True),
        ),
    ]
