# Generated by Django 4.0.3 on 2025-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_section_options_alter_subsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='unreliable_instability_events',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
