# Generated by Django 4.0.3 on 2025-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_polity_unreliable_instability_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='is_empty_on_polaris_release',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
