# Generated by Django 4.0.3 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_polity_is_empty_on_polaris_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinHoard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seshat_id", models.CharField(max_length=6, unique=True)),
                ("external_dataset_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("data_source", models.CharField(db_index=True, max_length=128)),
                ("hoard_name", models.CharField(blank=True, default="", max_length=255)),
                ("number_of_coins", models.IntegerField(blank=True, null=True)),
                ("year_from", models.IntegerField(blank=True, db_index=True, null=True)),
                ("year_to", models.IntegerField(blank=True, db_index=True, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("region", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("country", models.CharField(blank=True, default="", max_length=255)),
                ("external_url", models.URLField(blank=True, default="")),
                ("raw_external_id", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["external_dataset_id"]},
        ),
        migrations.AddIndex(
            model_name="coinhoard",
            index=models.Index(fields=["data_source", "year_from", "year_to"], name="core_coinho_data_so_b72e26_idx"),
        ),
        migrations.AddIndex(
            model_name="coinhoard",
            index=models.Index(fields=["region"], name="core_coinho_region_2f88ec_idx"),
        ),
    ]
