# Generated by Django 4.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_coinhoard"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinhoard",
            name="altitude",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="contextual_rating",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="county",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="discovery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Agricultural or drainage work", "Agricultural or drainage work"),
                    ("Building work", "Building work"),
                    ("Controlled archaeological investigation", "Controlled archaeological investigation"),
                    ("Fieldwalking", "Fieldwalking"),
                    ("Gardening", "Gardening"),
                    ("Metal detector", "Metal detector"),
                    (
                        "Metal detector during controlled archaeological investigation",
                        "Metal detector during controlled archaeological investigation",
                    ),
                    ("Other chance find", "Other chance find"),
                    ("Railroad construction", "Railroad construction"),
                    ("Road construction", "Road construction"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="discovery_year1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="discovery_year2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="find_spot_rating",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="numismatic_rating",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
