# Generated by Django 4.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_coinhoard_additional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinhoard",
            name="opening_year1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coinhoard",
            name="opening_year2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
