# Generated by Django 4.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_coinhoard_opening_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinhoard",
            name="external_source_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
