# Generated by Django 4.0.3 on 2026-04-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_coinhoardpolitymapping'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coinhoard',
            name='core_coinho_data_so_b72e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='coinhoard',
            name='core_coinho_region_2f88ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='coinhoardpolitymapping',
            name='core_coinho_coin_ho_58056c_idx',
        ),
        migrations.RemoveIndex(
            model_name='coinhoardpolitymapping',
            name='core_coinho_overlap_d51f84_idx',
        ),
        migrations.AddIndex(
            model_name='coinhoard',
            index=models.Index(fields=['data_source', 'year_from', 'year_to'], name='core_coinho_data_so_406111_idx'),
        ),
        migrations.AddIndex(
            model_name='coinhoard',
            index=models.Index(fields=['region'], name='core_coinho_region_ea085b_idx'),
        ),
        migrations.AddIndex(
            model_name='coinhoardpolitymapping',
            index=models.Index(fields=['coin_hoard', 'polity'], name='core_coinho_coin_ho_6cfa61_idx'),
        ),
        migrations.AddIndex(
            model_name='coinhoardpolitymapping',
            index=models.Index(fields=['overlap_year_from', 'overlap_year_to'], name='core_coinho_overlap_7e3b8a_idx'),
        ),
    ]
