sc_var_defs = {
'polity_territory': "in squared kilometers",
'polity_population': "Estimated population of the polity; can change as a result of both adding/losing new territories or by population growth/decline within a region",
'population_of_the_largest_settlement': 'Note that this could be different from the capital (coded under General). If possible, indicate the dynamics (that is, how population changed during the temporal period of the polity). Note that we are also building a city database - you should consult it as it may already have the needed data.',
 'communal_building': "This code distinguishes between settlements that consist of only private households (code 'absent') and settlements where there are communal buildings which could be used for a variety of uses (code 'present').",
 'utilitarian_public_building': 'Typical examples include aqueducts, sewers, and granaries. In the narrative paragraph list all utilitarian buildings and give examples of the most impressive/costly/large ones.',
 'symbolic_building': "Non-utilitarian constructions that display symbols, or are themselves symbols of the community or polity (or a ruler as a symbol of the polity). Examples include Taj Mahal mausoleum, Trajan's Column, Ashoka's Pillars, Qin Shih Huang's Terracota Army, the Statue of Liberty. Has to be constructed by humans, so sacred groves or mountains are not symbolic buildings. A palace is also not a symbolic building, because it has other, utilitarian functions (houses the ruler).",
 'entertainment_building': 'These include theaters, arenas, race tracks.',
 'knowledge_or_information_building': 'These include astronomic observatories, libraries, and museums.',
 'special_purpose_site': 'Sites not associated with residential areas. This position is primarily useful for coding archaneologically known societies.',
 'ceremonial_site': 'No Description',
 'burial_site': 'Dissociated from settlement, has monumental features.',
 'trading_emporia': 'Trading settlements characterised by their peripheral locations, on the shore at the edge of a polity, a lack of infrastructure (typically those in Europe contained no churches) and often of a short-lived nature. They include isolated caravanserai along trade routes.',
 'enclosure': "An 'enclosure' is clearly demarcated special-purpose area. It can be separated from surrounding land by earthworks (including banks or ditches), walls, or fencing. It may be as small as a few meters across, or encompass many hectares. It is non-residential, but could serve numerous purposes, both practical (animal pens) as well as religious and ceremonial",
 'length_measurement_system': 'Textual evidence of length measurement systems. Measurement units are named in sources.',
 'area_measurement_system': 'Textual evidence of area measurement systems. Measurement units are named in sources.',
 'volume_measurement_system': 'Textual evidence of volume measurement systems. Measurement units are named in sources. Archaeological evidence includes finding containers of standard volume, etc. (use "inferred present" in such cases)',
 'weight_measurement_system': 'Textual evidence of weight measurement systems. Measurement units are named in sources.',
 'time_measurement_system': "Textual evidence of time measurement systems. Measurement units are named in sources. A natural unit such as 'day' doesn't qualify. Nor does a vague one like 'season'. Archaeological evidence is a clock (e.g., sundial)",
 'geometrical_measurement_system': 'Textual evidence of geometrical measurement systems. Measurement units are named in sources.  For example: degree.',
 'other_measurement_system': 'Textual evidence of more advanced measurement systems: temperature, force, astronomical',
 'debt_and_credit_structure': 'Commercial/market practices that take physical form, e.g. a contract on parchment (not just verbal agreements).',
 'store_of_wealth': 'Example: hoard, chest for storing valuables, treasury room. Note for the future: perhaps should separate these into individual variables.',
  'source_of_support': "possible codes: state salary, governed population, land, none. 'State salary' can be paid either in currency or in kind (e.g., koku of rice). 'Governed population' means that the official directly collects tribute from the population (for example, the 'kormlenie' system in Medieval Russia). 'Land' is when the bureaucrats live off land supplied by the state. 'None' is when the state officials are not compensated (example: in the Republican and Principate Rome the magistrates were wealthy individuals who served without salary, motivated by prestige and social or career advancement).",
   'other_special_purpose_site': 'Other special-purpose sites.',
'special_purpose_house': 'A normal house used in a distinctive or special manner. This code reflects differentiation between houses.',
'occupational_complexity': "No Descriptions in the code book.",
'military_level': """levels. Again, start with the commander-in-chief = level 1 and work down to the private.
Even in primitive societies such as simple chiefdoms it is often possible to distinguish at least two levels – a commander and soldiers. A complex chiefdom would be coded three levels. The presence of warrior burials might be the basis for inferring the existence of a military organization. (The lowest military level is always the individual soldier).""",
'fastest_individual_communication': 'This is the fastest time (in days) an individual can travel from the capital city to the most outlying provincial capital (if one exists), usually keeping within the boundaries of the polity. This might be by ship, horse, horse relay, or on foot, or a combination.',
'largest_communication_distance': """Distance in kilometers between the capital and the furthest provincial capital. Use the figure for the most direct land and/or sea route that was available.
As an alternative for prehistoric communities, measure the distance between largest quasi-capital and furthest village within the quasi-polity.""",
 'other_utilitarian_public_building': 'Other utilitarian public buildings...',

################################################
"ra": "The name of the research assistant or associate who coded the data. If more than one RA made a substantial contribution, list all via separate entries.",
"polity_territory": "Polity territory is coded in squared kilometers.",
"polity_population": "Polity Population is the estimated population of the polity; can change as a result of both adding/losing new territories or by population growth/decline within a region",
"population_of_the_largest_settlement": "Population of the largest settlement is the estimated population of the largest settlement of the polity. Note that the largest settlement could be different from the capital (coded under General Variables). If possible, indicate the dynamics (that is, how population changed during the temporal period of the polity). Note that we are also building a city database - you should consult it as it may already have the needed data.",
"settlement_hierarchy": "Settlement hierarchy records (in levels) the hierarchy of not just settlement sizes, but also their complexity as reflected in different roles they play within the (quasi)polity. As settlements become more populous they acquire more complex functions: transportational (e.g. port); economic (e.g. market); administrative (e.g. storehouse, local government building); cultural (e.g. theatre); religious (e.g. temple), utilitarian (e.g. hospital), monumental (e.g. statues, plazas). Example: (1) Large City (monumental structures, theatre, market, hospital, central government buildings) (2) City (market, theatre, regional government buildings) (3) Large Town (market, administrative buildings) (4) Town (administrative buildings, storehouse)) (5) Village (shrine) (6) Hamlet (residential only). In the narrative paragraph explain the different levels and list their functions. Provide a (crude) estimate of population sizes. For example, Large Town (market, temple, administrative buildings): 2,000-5,000 inhabitants.",
"administrative_level": "Administrative levels records the administrative levels of a polity. An example of hierarchy for a state society could be (1) the overall ruler, (2) provincial/regional governors, (3) district heads, (4) town mayors, (5) village heads. Note that unlike in settlement hierarchy, here you code people hierarchy. Do not simply copy settlement hierarchy data here. For archaeological polities, you will usually code as 'unknown', unless experts identified ranks of chiefs or officials independently of the settlement hierarchy. Note: Often there are more than one concurrent administrative hierarchy. In the example above the hierarchy refers to the territorial government. In addition, the ruler may have a hierarchically organized central bureaucracy located in the capital. For example, (4)the overall ruler, (3) chiefs of various ministries, (2) midlevel bureaucrats, (1) scribes and clerks. In the narrative paragraph detail what is known about both hierarchies. The machine-readable code should reflect the largest number (the longer chain of command).",
"religious_level": "Religious levels records the Religious levels of a polity. Same principle as with Administrative levels. Start with the head of the official cult (if present) coded as: level 1, and work down to the local priest.",
"military_level": "Military levels records the Military levels of a polity. Same principle as with Administrative levels. Start with the commander-in-chief coded as: level 1, and work down to the private. Even in primitive societies such as simple chiefdoms it is often possible to distinguish at least two levels – a commander and soldiers. A complex chiefdom would be coded three levels. The presence of warrior burials might be the basis for inferring the existence of a military organization. (The lowest military level is always the individual soldier).",
"professional_military_officer": "Professional military officers refer to Full-time Professional military officers.",
"professional_soldier": "Professional soldiers refer to Full-time Professional soldiers.",
"professional_priesthood": "Professional priesthood refers to Full-time Professional priesthood.",
"full_time_bureaucrat": "Full-time bureaucrats refer to Full-time administrative specialists. Code this absent if administrative duties are performed by generalists such as chiefs and subchiefs. Also code it absent if state officials perform multiple functions, e.g. combining administrative tasks with military duties. Note that this variable shouldn't be coded 'present' only on the basis of the presence of specialized government buildings; there must be some additional evidence of functional specialization in government.",
"examination_system": "The paradigmatic example of an Examination system is the Chinese imperial system.",
"merit_promotion": "Merit promotion is coded present if there are regular, institutionalized procedures for promotion based on performance. When exceptional individuals are promoted to the top ranks, in the absence of institutionalized procedures, we code it under institution and equity variables",
"specialized_government_building": "These buildings are where administrative officials are located, and must be distinct from the ruler's palace. They may be used for document storage, registration offices, minting money, etc. Defense structures also are not coded here (see Military). State-owned/operated workshop should also not be coded here.",
"formal_legal_code": "Formal legal code refers to legal code usually, but not always written down. If not written down, code it 'present' when a uniform legal system is established by oral transmission (e.g., officials are taught the rules, or the laws are announced in a public space). Provide a short description",
"judge": "judges refers only to full-time professional judges",
"court": "courts are buildings specialized for legal proceedings only.",
"professional_lawyer": "we have coded the absence or presence of the variable..",
"irrigation_system": "irrigation systems are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.",
"drinking_water_supply_system": "drinking water supply systems are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.",
"market": "markets are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.",
"food_storage_site": "food storage sites are polity owned (which  includes owned by the community, or the state), we have coded the absence or presence of the variable.",
"road": "roads refers to deliberately constructed roads that connect settlements or other sites. It excludes streets/accessways within settlements and paths between settlements that develop through repeated use.",
"bridge": "bridges refers to bridges built and/or maintained by the polity (that is, code 'present' even if the polity did not build a bridge, but devotes resources to maintaining it).",
"canal": "canals refers to canals built and/or maintained by the polity (that is, code 'present' even if the polity did not build a canal, but devotes resources to maintaining it).",
"port": "Ports include river ports. Direct historical or archaeological evidence of Ports is absent when no port has been excavated or all evidence of such has been obliterated. Indirect historical or archaeological data is absent when there is no evidence that suggests that the polity engaged in maritime or riverine trade, conflict, or transportation, such as evidence of merchant shipping, administrative records of customs duties, or evidence that at the same period of time a trading relation in the region had a port (for example, due to natural processes, there is little evidence of ancient ports in delta Egypt at a time we know there was a timber trade with the Levant). When evidence for the variable itself is available the code is 'present.' When other forms of evidence suggests the existence of the variable (or not) the code may be 'inferred present' (or 'inferred absent'). When indirect evidence is not available the code will be either absent, temporal uncertainty, suspected unknown, or unknown.",
"mines_or_quarry": "we have coded the absence or presence of the variable.",
"mnemonic_device": "Mnemonic devices are: For example, tallies",
"nonwritten_record": "Nonwritten Records are more extensive than mnemonics, but don't utilize script. Example: quipu; seals and stamps",
"written_record": "Written records are more than short and fragmentary inscriptions, such as found on tombs or runic stones. There must be several sentences strung together, at the very minimum. For example, royal proclamations from Mesopotamia and Egypt qualify as written records",
"script": "script is as indicated at least by fragmentary inscriptions (note that if written records are present, then so is script)",
"non_phonetic_writing": "this refers to the kind of script",
"phonetic_alphabetic_writing": "this refers to the kind of script",
"lists_tables_and_classification": "we have coded the absence or presence of the variable.",
"calendar": "we have coded the absence or presence of the variable.",
"sacred_text": "Sacred Texts originate from supernatural agents (deities), or are directly inspired by them.",
"religious_literature": "Religious literature differs from the sacred texts. For example, it may provide commentary on the sacred texts, or advice on how to live a virtuous life.",
"practical_literature": "Practical literature refers to texts written with the aim of providing guidance on a certain topic, for example manuals on agriculture, warfare, or cooking. Letters do not count as practical literature.",
"history": "we have coded the absence or presence of the variable.",
"philosophy": "we have coded the absence or presence of the variable.",
"scientific_literature": "Scientific literature includes mathematics, natural sciences, social sciences",
"fiction": "fiction includes poetry.",
"article": "articles are items that have both a regular use and are used as money (example: axes, cattle, measures of grain, ingots of non-precious metals)",
"token": "tokens, unlike articles, are used only for exchange, and unlike coins, are not manufactured (example: cowries)",
"precious_metal": "Precious metals are non-coined silver, gold, platinum",
"foreign_coin": "we have coded the absence or presence of the variable.",
"indigenous_coin": "we have coded the absence or presence of the variable.",
"paper_currency": "Paper currency or another kind of fiat money. Note that this only refers to indigenously produced paper currency. Code absent if colonial money is used.",
"courier": "Full-time professional couriers.",
"postal_station": "Postal stations are specialized buildings exclusively devoted to the postal service. If there is a special building that has other functions than a postal station, we still code postal station as present. The intent is to capture additional infrastructure beyond having a corps of messengers.",
"general_postal_service": "'General postal service' refers to a postal service that not only serves the ruler's needs, but carries mail for private citizens.",


 }

sc_var_secs = {

}

sc_var_subsecs = {

}


