# yourapp/management/commands/populate_variables.py

from django.core.management.base import BaseCommand
from seshat.apps.core.models import Section, Subsection, Variablehierarchy

VARIABLE_DATA = [{'name': 'Long Wall',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "in km. These are fortifications that were used not to protect a specific city or town, but a large territory. Examples include the Great Wall of China. Provide an estimate in km of the extent of the longest of such fortification systems. If not present, enter '0'. Very large circular walls protecting a settlement are not long walls - long walls are fairly linear and protect whole areas from incursions. If a polity inherits a stone wall from a previous one and continues to use and repair it, then we should probably code it as present."},
 {'name': 'Copper',
  'section': 'Military use of Metals',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of copper as a military technology used in warfare. '},
 {'name': 'Bronze',
  'section': 'Military use of Metals',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "The absence or presence of bronze as a military technology used in warfare. Bronze is an alloy that includes copper, so a polity that uses bronze in warfare is familiar with copper technology and probably uses it to at least a limited extent. Consequently, if a culture uses bronze in warfare and there is no mention of using copper then 'inferred present' is probably best."},
 {'name': 'Iron',
  'section': 'Military use of Metals',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of iron as a military technology used in warfare. '},
 {'name': 'Steel',
  'section': 'Military use of Metals',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "The absence or presence of steel as a military technology used in warfare. Steel is an alloy that includes iron, so a polity that uses bronze in warfare is familiar with copper technology and probably uses it to at least a limited extent. Consequently, if a culture uses steel in warfare and there is no mention of using iron then 'inferred present' is probably best."},
 {'name': 'Javelin',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of javelins as a military technology used in warfare. Includes thrown spears'},
 {'name': 'Atlatl',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of atlatl as a military technology used in warfare. '},
 {'name': 'Sling',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of slings as a military technology used in warfare. '},
 {'name': 'Self Bow',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of self_bow as a military technology used in warfare. This is a bow made from a single piece of wood (example: the English/Welsh longbow)'},
 {'name': 'Composite Bow',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "The absence or presence of composite_bow as a military technology used in warfare. This is a bow made from several different materials, usually wood, horn, and sinew. Also known as laminated bow. Recurved bows should be coded here as well, because usually they are composite bows. When there is evidence for bows (or arrows) and no specific comment about how sophisticated the bows are then 'inferred present' for self bows and 'inferred absent' for composite bows is generally best (along with brief notes indicating that it is best to assume the less sophisticated rather than the more sophisticated technology is present)."},
 {'name': 'Crossbow',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of crossbow as a military technology used in warfare. '},
 {'name': 'Tension Siege Engine',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of tension_siege_engines as a military technology used in warfare. For example, catapult, onager'},
 {'name': 'Sling Siege Engine',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of sling_siege_engines as a military technology used in warfare. E.g., trebuchet, innclude mangonels here'},
 {'name': 'Gunpowder Siege Artillery',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of gunpowder_siege_artillery as a military technology used in warfare. For example, cannon, mortars.'},
 {'name': 'Handheld Firearm',
  'section': 'Projectiles',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of handheld_firearms as a military technology used in warfare. E.g., muskets, pistols, and rifles'},
 {'name': 'War Club',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of war_clubs as a military technology used in warfare. Includes maces'},
 {'name': 'Battle Axe',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of battle_axes as a military technology used in warfare. Axes designed for military use.'},
 {'name': 'Dagger',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of daggers as a military technology used in warfare. Bladed weapons shorter than 50 cm. Includes knives. Material is not important (coded elsewhere), thus flint daggers should be coded as present.'},
 {'name': 'Sword',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of swords as a military technology used in warfare. Bladed weapons longer than 50 cm. A machete is a sword (assuming the blade is probably longer than 50 cm). Material is not important (coded elsewhere), thus swords made from hard wood, or those edged with stones or bone should be coded as present.'},
 {'name': 'Spear',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of spears as a military technology used in warfare. Includes lances and pikes. A trident is a spear.'},
 {'name': 'Polearm',
  'section': 'Handheld weapons',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of polearms as a military technology used in warfare. This category includes halberds, naginatas, and morning stars'},
 {'name': 'Dog',
  'section': 'Animals used in warfare',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of dogs as a military technology used in warfare. '},
 {'name': 'Donkey',
  'section': 'Animals used in warfare',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of donkeys as a military technology used in warfare. '},
 {'name': 'Horse',
  'section': 'Animals used in warfare',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of horses as a military technology used in warfare. '},
 {'name': 'Camel',
  'section': 'Animals used in warfare',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of camels as a military technology used in warfare. '},
 {'name': 'Elephant',
  'section': 'Animals used in warfare',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of elephants as a military technology used in warfare. '},
 {'name': 'Wood Bark Etc',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of wood_bark_etc as a military technology used in warfare. '},
 {'name': 'Leather Cloth',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of leather_cloth as a military technology used in warfare. For example, leather cuirass, quilted cotton armor'},
 {'name': 'Shield',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of shields as a military technology used in warfare. '},
 {'name': 'Helmet',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of helmets as a military technology used in warfare. '},
 {'name': 'Breastplate',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "The absence or presence of breastplates as a military technology used in warfare. Armor made from wood, horn, or bone can be very important (as in the spread of the Asian War Complex into North America). Leather and cotton (in the Americas) armor was also effective against arrows and warclubs. Breastplate refers to any form of torso protection (in fact, we might rename this variable 'torso protection' at a later date). In the vast majority of cases you will probably find that if a culture has wooden armor, leather armor, chainmail armor, or scaled armor that breastplate should be coded as present because this is the most common location for armor. However, in theory, it is possible to have armor that doesn't protect the torso (for example, a culture might use armor that protects the limbs only)."},
 {'name': 'Limb Protection',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of limb_protection as a military technology used in warfare. E.g., greaves. Covering arms, or legs, or both.'},
 {'name': 'Scaled Armor',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': "The absence or presence of scaled_armor as a military technology used in warfare. Armor consisting of many individual small armor scales (plates) attached to a backing of cloth or leather. The scaled don't need to be metal (i.e. they could be particularly rigid bits of leather, horn, bone, etc)."},
 {'name': 'Laminar Armor',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of laminar_armor as a military technology used in warfare. (also known as banded mail, example: lorica segmentata). Armor that is made from horizontal overlapping rows or bands of sold armor plates.'},
 {'name': 'Plate Armor',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of plate_armor as a military technology used in warfare. Armor made of iron or steel plates.'},
 {'name': 'Small Vessels Canoes Etc',
  'section': 'Naval technology',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of small_vessels_canoes_etc as a military technology used in warfare. '},
 {'name': 'Merchant Ships Pressed Into Service',
  'section': 'Naval technology',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of merchant_ships_pressed_into_service as a military technology used in warfare. '},
 {'name': 'Specialized Military Vessel',
  'section': 'Naval technology',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of specialized_military_vessels as a military technology used in warfare. (such as galleys and sailing ships)'},
 {'name': 'Settlements In A Defensive Position',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of settlements_in_a_defensive_position as a military technology used in warfare. Settlements in a location that was clearly chosen for defensive reasons. E.g. on a hill top, peninsula.'},
 {'name': 'Wooden Palisade',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of wooden_palisades as a military technology used in warfare. '},
 {'name': 'Earth Rampart',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of earth_ramparts as a military technology used in warfare. '},
 {'name': 'Ditch',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of ditch as a military technology used in warfare. '},
 {'name': 'Moat',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of moat as a military technology used in warfare. Differs from a ditch in that it has water'},
 {'name': 'Stone Walls Non Mortared',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of stone_walls_non-mortared as a military technology used in warfare. '},
 {'name': 'Stone Walls Mortared',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of stone_walls_mortared as a military technology used in warfare. '},
 {'name': 'Fortified Camp',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of fortified_camps as a military technology used in warfare. Camps made by armies on the move (e.g. on a campaign) that which could be constructed on a hill top or in the middle of a plain or desert, usually out of local materials.'},
 {'name': 'Complex Fortification',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of complex_fortifications as a military technology used in warfare. When there are two or more concentric walls. So simply a wall and a donjon, for example, is not enough.'},
 {'name': 'Modern Fortification',
  'section': 'Fortifications',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of modern_fortifications as a military technology used in warfare. used after the introduction of gunpowder, e.g., trace italienne/starfort.'},
 {'name': 'Chainmail',
  'section': 'Armor',
  'subsection': None,
  'db_section': 'Warfare',
  'who_can_access': 'public',
  'var_def': 'The absence or presence of chainmail as a military technology used in warfare. We’re using a broad definition of chainmail. Habergeon was the word used to describe the Chinese version and that would qualify as chainmail. Armor that is made of small metal rings linked together in a pattern to form a mesh.'},
 {'name': 'Polity Territory',
  'section': 'Social Scale',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Social Scale, Polity territory is coded in squared kilometers.'},
 {'name': 'Polity Population',
  'section': 'Social Scale',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Social Scale, Polity Population is the estimated population of the polity; can change as a result of both adding/losing new territories or by population growth/decline within a region'},
 {'name': 'Population Of The Largest Settlement',
  'section': 'Social Scale',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Social Scale, Population of the largest settlement is the estimated population of the largest settlement of the polity. Note that the largest settlement could be different from the capital (coded under General Variables). If possible, indicate the dynamics (that is, how population changed during the temporal period of the polity). Note that we are also building a city database - you should consult it as it may already have the needed data.'},
 {'name': 'Settlement Hierarchy',
  'section': 'Hierarchical Complexity',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Hierarchical Complexity, Settlement hierarchy records (in levels) the hierarchy of not just settlement sizes, but also their complexity as reflected in different roles they play within the (quasi)polity. As settlements become more populous they acquire more complex functions: transportational (e.g. port); economic (e.g. market); administrative (e.g. storehouse, local government building); cultural (e.g. theatre); religious (e.g. temple), utilitarian (e.g. hospital), monumental (e.g. statues, plazas). Example: (1) Large City (monumental structures, theatre, market, hospital, central government buildings) (2) City (market, theatre, regional government buildings) (3) Large Town (market, administrative buildings) (4) Town (administrative buildings, storehouse)) (5) Village (shrine) (6) Hamlet (residential only). In the narrative paragraph explain the different levels and list their functions. Provide a (crude) estimate of population sizes. For example, Large Town (market, temple, administrative buildings): 2,000-5,000 inhabitants.'},
 {'name': 'Administrative Level',
  'section': 'Hierarchical Complexity',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Hierarchical Complexity, Administrative levels records the administrative levels of a polity. An example of hierarchy for a state society could be (1) the overall ruler, (2) provincial/regional governors, (3) district heads, (4) town mayors, (5) village heads. Note that unlike in settlement hierarchy, here you code people hierarchy. Do not simply copy settlement hierarchy data here. For archaeological polities, you will usually code as 'unknown', unless experts identified ranks of chiefs or officials independently of the settlement hierarchy. Note: Often there are more than one concurrent administrative hierarchy. In the example above the hierarchy refers to the territorial government. In addition, the ruler may have a hierarchically organized central bureaucracy located in the capital. For example, (4)the overall ruler, (3) chiefs of various ministries, (2) midlevel bureaucrats, (1) scribes and clerks. In the narrative paragraph detail what is known about both hierarchies. The machine-readable code should reflect the largest number (the longer chain of command)."},
 {'name': 'Religious Level',
  'section': 'Hierarchical Complexity',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Hierarchical Complexity, Religious levels records the Religious levels of a polity. Same principle as with Administrative levels. Start with the head of the official cult (if present) coded as: level 1, and work down to the local priest.'},
 {'name': 'Military Level',
  'section': 'Hierarchical Complexity',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Hierarchical Complexity, Military levels records the Military levels of a polity. Same principle as with Administrative levels. Start with the commander-in-chief coded as: level 1, and work down to the private. Even in primitive societies such as simple chiefdoms it is often possible to distinguish at least two levels – a commander and soldiers. A complex chiefdom would be coded three levels. The presence of warrior burials might be the basis for inferring the existence of a military organization. (The lowest military level is always the individual soldier).'},
 {'name': 'Professional Military Officer',
  'section': 'Professions',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Professions, Professional military officers refer to Full-time Professional military officers.'},
 {'name': 'Professional Soldier',
  'section': 'Professions',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Professions, Professional soldiers refer to Full-time Professional soldiers.'},
 {'name': 'Professional Priesthood',
  'section': 'Professions',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Professions, Professional priesthood refers to Full-time Professional priesthood.'},
 {'name': 'Full Time Bureaucrat',
  'section': 'Bureaucracy characteristics',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Bureaucracy characteristics, Full-time bureaucrats refer to Full-time administrative specialists. Code this absent if administrative duties are performed by generalists such as chiefs and subchiefs. Also code it absent if state officials perform multiple functions, e.g. combining administrative tasks with military duties. Note that this variable shouldn't be coded 'present' only on the basis of the presence of specialized government buildings; there must be some additional evidence of functional specialization in government."},
 {'name': 'Examination System',
  'section': 'Bureaucracy characteristics',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Bureaucracy characteristics, The paradigmatic example of an Examination system is the Chinese imperial system.'},
 {'name': 'Merit Promotion',
  'section': 'Bureaucracy characteristics',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Bureaucracy characteristics, Merit promotion is coded present if there are regular, institutionalized procedures for promotion based on performance. When exceptional individuals are promoted to the top ranks, in the absence of institutionalized procedures, we code it under institution and equity variables'},
 {'name': 'Specialized Government Building',
  'section': 'Bureaucracy characteristics',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Bureaucracy characteristics, These buildings are where administrative officials are located, and must be distinct from the ruler's palace. They may be used for document storage, registration offices, minting money, etc. Defense structures also are not coded here (see Military). State-owned/operated workshop should also not be coded here."},
 {'name': 'Formal Legal Code',
  'section': 'Law',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Law, Formal legal code refers to legal code usually, but not always written down. If not written down, code it 'present' when a uniform legal system is established by oral transmission (e.g., officials are taught the rules, or the laws are announced in a public space). Provide a short description"},
 {'name': 'Judge',
  'section': 'Law',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Law, judges refers only to full-time professional judges'},
 {'name': 'Court',
  'section': 'Law',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Law, courts are buildings specialized for legal proceedings only.'},
 {'name': 'Professional Lawyer',
  'section': 'Law',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Law, we have coded the absence or presence of the variable..'},
 {'name': 'Irrigation System',
  'section': 'Specialized Buildings',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Specialized Buildings, irrigation systems are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.'},
 {'name': 'Drinking Water Supply System',
  'section': 'Specialized Buildings',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Specialized Buildings, drinking water supply systems are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.'},
 {'name': 'Market',
  'section': 'Specialized Buildings',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Specialized Buildings, markets are polity owned (which includes owned by the community, or the state), we have coded the absence or presence of the variable.'},
 {'name': 'Food Storage Site',
  'section': 'Specialized Buildings',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Specialized Buildings, food storage sites are polity owned (which  includes owned by the community, or the state), we have coded the absence or presence of the variable.'},
 {'name': 'Road',
  'section': 'Transport infrastructure',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Transport infrastructure, roads refers to deliberately constructed roads that connect settlements or other sites. It excludes streets/accessways within settlements and paths between settlements that develop through repeated use.'},
 {'name': 'Bridge',
  'section': 'Transport infrastructure',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Transport infrastructure, bridges refers to bridges built and/or maintained by the polity (that is, code 'present' even if the polity did not build a bridge, but devotes resources to maintaining it)."},
 {'name': 'Canal',
  'section': 'Transport infrastructure',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Transport infrastructure, canals refers to canals built and/or maintained by the polity (that is, code 'present' even if the polity did not build a canal, but devotes resources to maintaining it)."},
 {'name': 'Port',
  'section': 'Transport infrastructure',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Transport infrastructure, Ports include river ports. Direct historical or archaeological evidence of Ports is absent when no port has been excavated or all evidence of such has been obliterated. Indirect historical or archaeological data is absent when there is no evidence that suggests that the polity engaged in maritime or riverine trade, conflict, or transportation, such as evidence of merchant shipping, administrative records of customs duties, or evidence that at the same period of time a trading relation in the region had a port (for example, due to natural processes, there is little evidence of ancient ports in delta Egypt at a time we know there was a timber trade with the Levant). When evidence for the variable itself is available the code is 'present.' When other forms of evidence suggests the existence of the variable (or not) the code may be 'inferred present' (or 'inferred absent'). When indirect evidence is not available the code will be either absent, temporal uncertainty, suspected unknown, or unknown."},
 {'name': 'Mines Or Quarry',
  'section': 'Special purpose sites',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Special purpose sites, we have coded the absence or presence of the variable.'},
 {'name': 'Mnemonic Device',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Writing Systems, Mnemonic devices are: For example, tallies'},
 {'name': 'Nonwritten Record',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about Writing Systems, Nonwritten Records are more extensive than mnemonics, but don't utilize script. Example: quipu; seals and stamps"},
 {'name': 'Written Record',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Writing Systems, Written records are more than short and fragmentary inscriptions, such as found on tombs or runic stones. There must be several sentences strung together, at the very minimum. For example, royal proclamations from Mesopotamia and Egypt qualify as written records'},
 {'name': 'Script',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Writing Systems, script is as indicated at least by fragmentary inscriptions (note that if written records are present, then so is script)'},
 {'name': 'Non Phonetic Writing',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Writing Systems, this refers to the kind of script'},
 {'name': 'Phonetic Alphabetic Writing',
  'section': 'Information',
  'subsection': 'Writing Systems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Writing Systems, this refers to the kind of script'},
 {'name': 'Lists Tables And Classification',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, we have coded the absence or presence of the variable.'},
 {'name': 'Calendar',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, we have coded the absence or presence of the variable.'},
 {'name': 'Sacred Text',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, Sacred Texts originate from supernatural agents (deities), or are directly inspired by them.'},
 {'name': 'Religious Literature',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, Religious literature differs from the sacred texts. For example, it may provide commentary on the sacred texts, or advice on how to live a virtuous life.'},
 {'name': 'Practical Literature',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, Practical literature refers to texts written with the aim of providing guidance on a certain topic, for example manuals on agriculture, warfare, or cooking. Letters do not count as practical literature.'},
 {'name': 'History',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, we have coded the absence or presence of the variable.'},
 {'name': 'Philosophy',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, we have coded the absence or presence of the variable.'},
 {'name': 'Scientific Literature',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, Scientific literature includes mathematics, natural sciences, social sciences'},
 {'name': 'Fiction',
  'section': 'Information',
  'subsection': 'Kinds of Written Documents',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about Kinds of Written Documents, fiction includes poetry.'},
 {'name': 'Article',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about forms of money, articles are items that have both a regular use and are used as money (example: axes, cattle, measures of grain, ingots of non-precious metals)'},
 {'name': 'Token',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about forms of money, tokens, unlike articles, are used only for exchange, and unlike coins, are not manufactured (example: cowries)'},
 {'name': 'Precious Metal',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'This variable tracks the role of precious metals as luxury goods in historical polities. It includes data on: the types of precious metals (e.g., gold, silver) used and traded, the geographic regions where these precious metals were sourced, and whether they were consumed or utilized by rulers, elites, or common people. This variable helps analyze the circulation, economic value, and societal implications of precious metals in ancient and historical economies.'},
 {'name': 'Foreign Coin',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'we have coded the absence or presence of the variable.'},
 {'name': 'Indigenous Coin',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'we have coded the absence or presence of the variable.'},
 {'name': 'Paper Currency',
  'section': 'Information',
  'subsection': 'Forms of money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Paper currency or another kind of fiat money. Note that this only refers to indigenously produced paper currency. Code absent if colonial money is used.'},
 {'name': 'Courier',
  'section': 'Information',
  'subsection': 'Postal sytems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Full-time professional couriers.'},
 {'name': 'Postal Station',
  'section': 'Information',
  'subsection': 'Postal sytems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Talking about postal sytems, Postal stations are specialized buildings exclusively devoted to the postal service. If there is a special building that has other functions than a postal station, we still code postal station as present. The intent is to capture additional infrastructure beyond having a corps of messengers.'},
 {'name': 'General Postal Service',
  'section': 'Information',
  'subsection': 'Postal sytems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Talking about postal sytems, 'General postal service' refers to a postal service that not only serves the ruler's needs, but carries mail for private citizens."},
 {'name': 'Fastest Individual Communication',
  'section': 'Information',
  'subsection': 'Postal sytems',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'This is the fastest time (in days) an individual can travel from the capital city to the most outlying provincial capital (if one exists), usually keeping within the boundaries of the polity. This might be by ship, horse, horse relay, or on foot, or a combination.'},
 {'name': 'communal building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "This code distinguishes between settlements that consist of only private households (code 'absent') and settlements where there are communal buildings which could be used for a variety of uses (code 'present')."},
 {'name': 'Utilitarian Public Building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Typical examples include aqueducts, sewers, and granaries. In the narrative paragraph list all utilitarian buildings and give examples of the most impressive/costly/large ones.'},
 {'name': 'Symbolic Building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Non-utilitarian constructions that display symbols, or are themselves symbols of the community or polity (or a ruler as a symbol of the polity). Examples include Taj Mahal mausoleum, Trajan's Column, Ashoka's Pillars, Qin Shih Huang's Terracota Army, the Statue of Liberty. Has to be constructed by humans, so sacred groves or mountains are not symbolic buildings. A palace is also not a symbolic building, because it has other, utilitarian functions (houses the ruler)."},
 {'name': 'Entertainment Building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'These include theaters, arenas, race tracks.'},
 {'name': 'Knowledge Or Information Building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'These include astronomic observatories, libraries, and museums.'},
 {'name': 'Other Utilitarian Public Building',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Other utilitarian public buildings...'},
 {'name': 'Special Purpose Site',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Sites not associated with residential areas. This position is primarily useful for coding archaneologically known societies.'},
 {'name': 'Ceremonial Site',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'No Description'},
 {'name': 'Burial Site',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Dissociated from settlement, has monumental features.'},
 {'name': 'Trading Emporia',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Trading settlements characterised by their peripheral locations, on the shore at the edge of a polity, a lack of infrastructure (typically those in Europe contained no churches) and often of a short-lived nature. They include isolated caravanserai along trade routes.'},
 {'name': 'Enclosure',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "An 'enclosure' is clearly demarcated special-purpose area. It can be separated from surrounding land by earthworks (including banks or ditches), walls, or fencing. It may be as small as a few meters across, or encompass many hectares. It is non-residential, but could serve numerous purposes, both practical (animal pens) as well as religious and ceremonial"},
 {'name': 'Length Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of length measurement systems. Measurement units are named in sources.'},
 {'name': 'Area Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of area measurement systems. Measurement units are named in sources.'},
 {'name': 'Volume Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of volume measurement systems. Measurement units are named in sources. Archaeological evidence includes finding containers of standard volume, etc. (use "inferred present" in such cases)'},
 {'name': 'Weight Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of weight measurement systems. Measurement units are named in sources.'},
 {'name': 'Time Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "Textual evidence of time measurement systems. Measurement units are named in sources. A natural unit such as 'day' doesn't qualify. Nor does a vague one like 'season'. Archaeological evidence is a clock (e.g., sundial)"},
 {'name': 'Geometrical Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of geometrical measurement systems. Measurement units are named in sources.  For example: degree.'},
 {'name': 'Other Measurement System',
  'section': 'Information',
  'subsection': 'Measurement System',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Textual evidence of more advanced measurement systems: temperature, force, astronomical'},
 {'name': 'Debt And Credit Structure',
  'section': 'Information',
  'subsection': 'Money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Commercial/market practices that take physical form, e.g. a contract on parchment (not just verbal agreements).'},
 {'name': 'Store Of Wealth',
  'section': 'Information',
  'subsection': 'Money',
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Example: hoard, chest for storing valuables, treasury room. Note for the future: perhaps should separate these into individual variables.'},
 {'name': 'Source Of Support',
  'section': 'Professions',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': "possible codes: state salary, governed population, land, none. 'State salary' can be paid either in currency or in kind (e.g., koku of rice). 'Governed population' means that the official directly collects tribute from the population (for example, the 'kormlenie' system in Medieval Russia). 'Land' is when the bureaucrats live off land supplied by the state. 'None' is when the state officials are not compensated (example: in the Republican and Principate Rome the magistrates were wealthy individuals who served without salary, motivated by prestige and social or career advancement)."},
 {'name': 'Occupational Complexity',
  'section': 'Professions',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'No Descriptions in the code book.'},
 {'name': 'Special Purpose House',
  'section': 'Specialized Buildings: polity owned',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'A normal house used in a distinctive or special manner. This code reflects differentiation between houses.'},
 {'name': 'Other Special Purpose Site',
  'section': 'Special-purpose Sites',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Other special-purpose sites.'},
 {'name': 'Largest Communication Distance',
  'section': 'Social Scale',
  'subsection': None,
  'db_section': 'Social Complexity',
  'who_can_access': 'public',
  'var_def': 'Distance in kilometers between the capital and the furthest provincial capital. Use the figure for the most direct land and/or sea route that was available.\nAs an alternative for prehistoric communities, measure the distance between largest quasi-capital and furthest village within the quasi-polity.'},
 {'name': 'Official Religion',
  'section': 'Religious Demography',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'This variable is coded to capture the official religion within the polity. It reflects the specific religious faith officially endorsed and supported by the polity as the polity religion, if any.'},
 {'name': 'Elites Religion',
  'section': 'Religious Demography',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to capture the religion associated with or favored by the political or societal elites within the polity, this variable reflects the specific religious belief system prevalent among the elite class, if identifiable.'},
 {'name': 'Theological Syncretism Of Different Religions',
  'section': 'Religious Demography',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': "This variable is coded to indicate the presence or absence of theological syncretism among different religions within the polity. It reflects whether diverse religious beliefs coexist and influence each other's theological doctrines."},
 {'name': 'Syncretism Of Religious Practices At The Level Of Individual Believers',
  'section': 'Religious Demography',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to reflect the presence or absence of syncretism of religious practices at the individual level, this variable signifies whether believers combine or adopt practices from multiple religious traditions within the polity.'},
 {'name': 'Religious Fragmentation',
  'section': 'Religious Demography',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to assess the level of diversity and division among religious groups within the polity, this variable indicates whether various distinct religious factions or denominations exist, reflecting the degree of religious diversity.'},
 {'name': 'Frequency Of Governmental Violence Against Religious Groups',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'This variable is coded to measure the frequency of governmental violence against religious groups within the polity. It indicates how often the government engages in violent actions directed towards religious communities, providing insights into the recurring nature of such incidents.'},
 {'name': 'Government Restrictions On Public Worship',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to reflect the presence or absence of government control over public worship, this variable indicates whether authorities regulate and limit religious gatherings and ceremonies within the polity.'},
 {'name': 'Government Restrictions On Public Proselytizing',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government restrictions on public proselytizing, this variable reflects the limitations imposed on the act of promoting or spreading religious beliefs to others within the public domain of the polity.'},
 {'name': 'Government Restrictions On Conversion',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': "Coded to reflect the presence or absence of government constraints on religious conversion, this variable indicates the degree to which authorities regulate or restrict individuals' ability to change their religious affiliation within the polity."},
 {'name': 'Government Pressure To Convert',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government-induced pressure for religious conversion, this variable reflects the extent to which authorities influence or coerce individuals to adopt a specific religious faith within the polity.'},
 {'name': 'Government Restrictions On Property Ownership For Adherents Of Any Religious Group',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': "Coded to indicate the presence or absence of government restrictions on property ownership for religious adherents, this variable reflects limitations imposed on individuals' rights to own property based on their religious affiliation within the polity."},
 {'name': 'Taxes Based On Religious Adherence Or On Religious Activities And Institutions',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'This variable is coded to indicate the presence or absence of taxes based on religious adherence or on religious activities and institutions. It reflects the financial burdens placed on religious individuals and institutions within the polity.'},
 {'name': 'Governmental Obligations For Religious Groups To Apply For Official Recognition',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of governmental obligations for religious groups to seek official recognition, this variable reflects the extent to which religious communities are required to obtain formal approval or acknowledgment from authorities within the polity.'},
 {'name': 'Government Restrictions On Construction Of Religious Buildings',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government limitations on the construction of religious buildings, this variable reflects the extent to which authorities regulate the establishment of places of worship within the polity.'},
 {'name': 'Government Restrictions On Religious Education',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government restrictions on religious education, this variable reflects limitations imposed on the teaching and dissemination of religious knowledge within educational institutions in the polity.'},
 {'name': 'Government Restrictions On Circulation Of Religious Literature',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government restrictions on the circulation of religious literature, this variable reflects limitations on the production, distribution, and accessibility of religious texts within the polity.'},
 {'name': 'Government Discrimination Against Religious Groups Taking Up Certain Occupations Or Functions',
  'section': 'Religious Tolerance',
  'subsection': 'Government Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of government discrimination against religious groups in terms of access to specific occupations or functions, this variable reflects the degree to which authorities limit certain roles based on religious affiliation within the polity.'},
 {'name': 'Frequency Of Societal Violence Against Religious Groups',
  'section': 'Religios Tolerance',
  'subsection': 'Societal Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'This variable is coded to measure the frequency of societal violence against religious groups within the polity. It reflects how often non-governmental entities, such as societal groups or individuals, engage in violent actions against religious communities. The variable provides insights into the recurring nature of violence originating from societal sources against religious groups.'},
 {'name': 'Societal Discrimination Against Religious Groups Taking Up Certain Occupations Or Functions',
  'section': 'Religios Tolerance',
  'subsection': 'Societal Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': 'Coded to indicate the presence or absence of societal discrimination against religious groups in occupational or functional contexts, this variable reflects the degree to which individuals face discrimination based on their religious affiliation within the polity.'},
 {'name': 'Societal Pressure To Convert Or Against Conversion',
  'section': 'Religios Tolerance',
  'subsection': 'Societal Restrictions',
  'db_section': 'Religion',
  'who_can_access': 'some_polities_are_public',
  'var_def': "Coded to indicate the presence or absence of societal pressure for religious conversion or against conversion, this variable reflects the influence of social norms and expectations on individuals' decisions to adopt or abandon specific religious beliefs within the polity."},
 {'name': 'Moralizing Supernatural Concern Is Primary',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'The principal concerns of supernatural agents or forces pertain to cooperation in human affairs (rather than the behaviour of humans toward the supernatural realm, for example by discharging ritual obligations)'},
 {'name': 'Moralizing Enforcement Is Certain',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'Moralizing supernatural punishments and/or rewards are certain and predictable (rather than arbitrary or capricious)'},
 {'name': 'Moralizing Enforcement Is Broad',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'Moralizing supernatural punishments and/or rewards enforce norms across a broad range of moral domains (instead of just a few domains)'},
 {'name': 'Moralizing Enforcement Is Targeted',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'Moralizing supernatural punishments and/or rewards are targeted specifically at culpable individuals (instead of the whole group)'},
 {'name': 'Moralizing Enforcement Of Rulers',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'Moralizing supernatural forces or agents punish and/or reward rulers'},
 {'name': 'Moralizing Religion Adopted By Elites',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'The elites of the polity subscribe to moralizing supernatural punishments and/or rewards'},
 {'name': 'Moralizing Religion Adopted By Commoners',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'The commoners of the polity subscribe to moralizing supernatural punishments and/or rewards'},
 {'name': 'Moralizing Enforcement In Afterlife',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'punishment is delayed until after the death of the transgressor'},
 {'name': 'Moralizing Enforcement In This Life',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': "punishment occurs during transgressor's lifetime"},
 {'name': 'Moralizing Enforcement Is Agentic',
  'section': 'Moralizing Supernatural Punishment and Reward',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'public',
  'var_def': 'Moralizing enforcement is administered by a supernatural agent, such as a deity or spirit (as opposed to an impersonal supernatural force, such as karma).'},
 {'name': 'Polity Utm Zone',
  'section': 'Identity and Location',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Usually where the capital city is locate. List only one per polity.'},
 {'name': 'Polity Original Name',
  'section': 'Identity and Location',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Original name of the polity.'},
 {'name': 'Polity Alternative Name',
  'section': 'Identity and Location',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Used in the historical literature; also supply the most common name used by the natives.'},
 {'name': 'Polity Peak Years',
  'section': 'Temporal Bounds',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'The period when the polity was at its peak, whether militarily, in terms of the size of territory controlled, or the degree of cultural development. This variable has a subjective element, but typically historians agree when the peak was.'},
 {'name': 'Polity Duration',
  'section': 'Temporal Bounds',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'The starting and ending dates of the polity. For example, the starting date could be the establishment of a long-ruling dynasty, while the ending date may be the year when the polity was conquered by an aggressive neighbor. In cases when starting and/or ending dates are fuzzy, as explained above, use the earliest possible starting date and the latest possible ending date. This approach will result in a temporal overlap, so that some NGAs for some periods will be coded as belonging to two polities simultaneously (e.g., to a disintegrating overarching polity and to the rising regional subpolity). Such overlap is acceptable, and will be dealt with at the analysis stage.'},
 {'name': 'Polity Degree Of Centralization',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': "unknown/ quasi-polity/ nominal/ loose/ confederated state /unitary state\n\n'quasi-polity' = or 'none'. Use if, for example, the NGA is inhabited by many politically independent groups. There are four types of quasi-polity: archaeological, temporal, complex and dominant. Quasi-Polities: further information.\n'nominal' = regional rulers pay only nominal allegiance to the overall ruler and maintain independence on all important aspects of governing, including taxation and warfare. (example: Japan during the Sengoku period)\n'loose' = the central government exercises a certain degree of control, especially over military matters and international relations. Otherwise the regional rulers are left alone (example: European 'feudalism' after the collapse of the Carolingian empire)\n'confederated state' = regions enjoy a large degree of autonomy in internal (regional) government. In particular, the regional governors are either hereditary rulers, or are elected by regional elites or by the population of the region; and regional governments can levy and dispose of regional taxes. Use this category for the more centralized 'feudal states'.\n'unitary state' = regional governors are appointed and removed by the central authorities, taxes are imposed by, and transmitted to the center"},
 {'name': 'Polity Suprapolity Relations',
  'section': 'Language',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'unknown/ none/ alliance/ nominal allegiance/ personal union/ vassalage/\n\n\'alliance\' = belongs to a long-term military-political alliance of independent polities (\'long-term\' refers to more or less permanent relationship between polities extending over multiple years)\n\'nominal allegiance\' = same as \'nominal\' under the variable "Degree of centralization" but now reflecting the position of the focal polity within the overarching political authority\n\'personal union\' = the focal polity is united with another, or others, as a result of a dynastic marriage\n\'vassalage\' = corresponding to \'loose\' category in the Degree of centralization'},
 {'name': 'Polity Capital',
  'section': 'Identity and Location',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'The city where the ruler spends most of its time. If there were more than one capital supply all names and enclose in curly braces. For example, {Susa; Pasargadae; Persepolis; Ecbatana; Babylon}. Note that the capital may be different from the largest city (see below). Capital may be difficult to code for archaeologically known societies. If there is reasonable basis to believe that the largest known settlement was the seat of the ruler code it as capital (and indicate uncertainty in the narrative paragraph). Archaeologists are able to recognize special architectural structures, such as a ceremonial centres and some kind of citadels or palaces. These features could be recognized with certainty after a careful study of the whole region and the settlement network. If such an inference cannot be made, code as "unknown" (again, the largest settlement is coded elsewhere).'},
 {'name': 'Polity Language',
  'section': 'Language',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'The language(s) used polity-wide for administration, religion, and military affairs.'},
 {'name': 'Polity Linguistic Family',
  'section': 'Language',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Linguistic family of the Polity.'},
 {'name': 'Polity Language Genus',
  'section': 'Language',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Language genus of the Polity.'},
 {'name': 'Polity Religion Genus',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Religion genus of the Polity.'},
 {'name': 'Polity Religion Family',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Religion family of the Polity.'},
 {'name': 'Polity Religion',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Religion of the Polity.'},
 {'name': 'Polity Relationship To Preceding Entity',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Possible codes: continuity (gradual change), cultural assimilation (by another quasi-polity in the absence of substantial population replacement), elite migration (the preceding elites replaced by new elites coming from elsewhere), population migration (evidence for substantial population replacement), secession (from another polity). In the narrative paragraph explain the evidential basis for the code: what are the proxies for change? Examples include DNA data, isotope data, material (other than subsistence) culture, subsistence mode, symbolic culture (incl. burial practices), settlement patterns.'},
 {'name': 'Polity Preceding Entity',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': "This code is based on the core region of the current polity (not the NGA region). E.g. Achaemenid Empire's core region was Persia, where they were preceded by the Median Empire."},
 {'name': 'Polity Succeeding Entity',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': "This code is based on the core region of the current polity (not the NGA region). E.g. Achaemenid Empire's core region was Persia, where they were preceded by the Median Empire."},
 {'name': 'Polity Supracultural Entity',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': "Our quasi-polity are often embedded within larger-scale cultural groupings of polities or quasi-polities. These are sometimes referred to as 'civilizations'. For example, medieval European kingdoms were part of Latin Christendom. During the periods of disunity in China, warring states there, nevertheless, belonged to the same Chinese cultural sphere. Archaeologists often use 'archaeological traditions' to denote such large-scale cultural entities (for example, Peregrine's Atlas of Cultural Evolution). Note, 'supracultural entity' refers to cultural interdependence, and is distinct from a political confederation or alliance, which should be coded under 'supra-polity relations.'"},
 {'name': 'Polity Scale Of Supracultural Interaction',
  'section': 'Political and Cultural Relations',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'km squared. An estimate of the area encompassed by the supracultural entity'},
 {'name': 'Polity Alternate Religion Genus',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Alternate Religion genus of the Polity.'},
 {'name': 'Polity Alternate Religion Family',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Alternate Religion family of the Polity.'},
 {'name': 'Polity Alternate Religion',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Alternate Religion of the Polity.'},
 {'name': 'Polity Religious Tradition',
  'section': 'Religion',
  'subsection': None,
  'db_section': 'General',
  'who_can_access': 'public',
  'var_def': 'Religious tradition  of the Polity.'},
 {'name': 'Precious Metal',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the role of precious metals as luxury goods in historical polities. It includes data on: the types of precious metals (e.g., gold, silver) used and traded, the geographic regions where these precious metals were sourced, and whether they were consumed or utilized by rulers, elites, or common people. This variable helps analyze the circulation, economic value, and societal implications of precious metals in ancient and historical economies.'},
 {'name': 'Luxury Fabrics',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the use and trade of luxury fabrics in historical polities. It includes data on: the types of high-quality textiles (e.g., silk, velvet, fine wool) produced or imported, the regions where these fabrics were sourced or manufactured, and their consumption or usage by rulers, elites, or other societal groups. This variable helps analyze the cultural significance, economic value, and trade networks associated with luxury fabrics.'},
 {'name': 'Luxury Manufactured Goods',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production and distribution of luxury manufactured goods in historical polities. It includes data on: artisan-produced items known for exceptional craftsmanship, their materials and designs, and their use by different societal groups. This variable sheds light on the role of high-quality manufactured goods in ancient economies and social hierarchies.'},
 {'name': 'Luxury Spices Incense And Dyes',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the trade and use of luxury spices, incense, and dyes in historical polities. It includes data on: the types of these substances (e.g., saffron, frankincense, indigo), their geographic origins, and their roles in culinary, religious, or artistic practices. This variable helps examine trade routes, cultural exchanges, and the societal value of these luxury items.'},
 {'name': 'Luxury Drink/Alcohol',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production, distribution, and consumption of luxury drinks or alcohol in historical polities. It includes data on: the types of beverages (e.g., fine wines, spirits), their production regions, and their consumption by rulers, elites, or other groups. This variable helps analyze the cultural significance and economic value of luxury drinks in historical contexts.'},
 {'name': 'Luxury Glass Goods',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production and trade of luxury glass goods in historical polities. It includes data on: the types of glass items (e.g., decorative glassware, colored glass), their regions of origin, and their use by societal groups. This variable helps explore the technological advancements, trade dynamics, and societal value of luxury glass goods.'},
 {'name': 'Fine Ceramic Wares',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production, trade, and use of fine ceramic wares in historical polities. It includes data on: the types of ceramics (e.g., porcelain, glazed pottery), their regions of production, and their consumption or use by rulers, elites, or common people. This variable provides insights into the technological and cultural significance of luxury ceramics.'},
 {'name': 'Precious Stone',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the use and trade of precious stones as luxury goods in historical polities. It includes data on: the types of stones (e.g., diamonds, rubies, emeralds), their geographic sources, and their use in jewelry or ceremonial contexts. This variable highlights the economic and cultural value of precious stones in historical societies.'},
 {'name': 'Statuary',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production and use of luxury statuary in historical polities. It includes data on: the materials used (e.g., marble, bronze), the types of statues produced (e.g., religious, political), and their role in societal, religious, or artistic contexts. This variable sheds light on the cultural and symbolic significance of statuary.'},
 {'name': 'Luxury Food',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks the production, trade, and consumption of luxury food items in historical polities. It includes data on: the types of rare or high-value foods, their regions of origin, and their consumption by rulers, elites, or other groups. This variable helps analyze the role of food in expressing wealth and status.'},
 {'name': 'Other Luxury Personal Items',
  'section': 'Luxury Goods',
  'subsection': None,
  'db_section': 'Economy',
  'who_can_access': 'private',
  'var_def': 'This variable tracks miscellaneous luxury personal items in historical polities. It includes data on: the types of these items (e.g., ornate accessories, personal tools), their materials and production methods, and their use or ownership by societal groups. This variable explores the diversity of luxury goods and their role in historical social structures.'},
 {'name': 'Human Sacrifice',
  'section': 'Human Sacrifice',
  'subsection': None,
  'db_section': 'Religion',
  'who_can_access': 'private',
  'var_def': 'Human Sacrifice is the deliberate and ritualized killing of a person to please or placate supernatural entities (including gods, spirits, and ancestors) or gain other supernatural benefits.'},
 {'name': 'Power Transition',
  'section': 'Power Transitions',
  'subsection': None,
  'db_section': 'Crisisdb',
  'who_can_access': 'private',
  'var_def': '\nWe are interested in cataloguing the relative stability of past societies as proxied by the transition of power from one ruler to the next. In particular, we identify each transition of power (from named predecessor to named successor) and record whether it took place through normal succession mechanisms (whether legal/institutionalized means or customary/de facto procedures) or as the result of a conflict. We are seeking to record this information across the Seshat sample of polities, subject to availability of evidence. We are particularly interested in documenting the ebb and flow of stability in particular regions over time.\nCoding Instructions: \nPredecessor: If a ruler came to power after a period during which the polity had no ruler (e.g. an interregnum), enter “None” in the predecessor field.\nSuccessor: If a ruler’s reign was followed by a period during which there was no ruler, enter “None” in the successor field.\nContested: Was the transition from predecessor to successor contested in any way? Code present if there was a contest at any time from the end of the predecessor’s reign to the end of the first 365 days of the successor’s reign. This is a general variable covering many possibilities, disambiguated in other variables. It should also be coded present if the transition was contested in a way not covered by any of the other variables, e.g. the judiciary challenges the result of a presidential election.If there was a contest, code for the following types of contest (note: multiple types of contest can be present).\nOverturn: Was the predecessor forcibly removed from power, e.g. through assassination, forced abdication, external invasion forcing them into exile? Note: There will often be succession crises when there is no “normal line of succession,” so that there will be a “contested transition” with no overturn. Examples: 1. The dynasty ends with no heir (typical cause of a succession crisis); 2. The previous ruler has died and divided the kingdom between his sons (who then decide to fight for it all); 3. There is no formal succession procedure and every power transitions is a fight (e.g., Mamluk Sultanate). These cases should not qualify as a successful overturn as nobody is being overturned, but still count as a contested transition.\nPredecessor assassination: Was the predecessor assassinated? This does not have to be carried out by the ultimate successor or their allies, but applies to any killing. Judicially sanctioned executions (e.g. of Charles I of England) also count.\nIntra-elite coup: Code present if either 1. the predecessor was removed from power by an intra-elite coup; or 2. the successor was unsuccessfully challenged by rival elites during their first year.\nMilitary revolt: Code as for intra-elite coup, but for rebellions that have military leadership. “Military” refers to professional soldiers and officers, not to nobles who have armed retinues (these are counted as elites).\nPopular uprising: For rebellions in which the majority of participants are non-elites.\nSeparatist rebellion: Part of the polity attempts to secede, whether successfully or unsuccessfully.\nExternal invasion:  An external polity invades. An invasion does not have to aim specifically at removing the ruler in order to code this variable present. However, small border skirmishes do not justify a “present” code and can be ignored. \nExternal interference:  Code this variable present when an external force helps internal rebels, e.g. by providing financial support or arms. Both external invasion and external interference may be present, e.g. when one polity sends military aid for a time, and then turns to an invasion.\n    '},
 {'name': 'Instability Event',
  'section': 'Instability Events',
  'subsection': None,
  'db_section': 'Crisisdb',
  'who_can_access': 'private',
  'var_def': 'a significant historical event characterized by social, political, or economic turmoil. This model captures key attributes of such events, including their types, intensity, extent, and reliability.'},
 {'name': 'Crisis Consequence',
  'section': 'Crisis Consequences',
  'subsection': None,
  'db_section': 'Crisisdb',
  'who_can_access': 'public',
  'var_def': 'We define Crises as arising within polities, which we define as an independent political unit. Kinds of polities range from villages (local communities) through simple and complex chiefdoms to states and empires. A polity can be either centralized or not (e.g., organized as a confederation). What distinguishes a polity from other human groupings and organizations is that it is politically independent of any overarching authority; it possesses sovereignty. Polities are defined spatially by the area enclosed within a boundary on the world map. There may be more than one such area. Polities are dynamical entities, and thus their geographical extent may change with time. Thus, typically each polity will be defined by a set of multiple boundaries, each for a specified period of time. '}]

class Command(BaseCommand):
    help = 'Populates the Section, Subsection, and Variablehierarchy models with predefined data'

    def handle(self, *args, **options):
        for var in VARIABLE_DATA:
            section_name = var['section']
            subsection_name = var['subsection']
            variable_name = var['name']

            # Get or create Section
            section_obj, _ = Section.objects.get_or_create(name=section_name)

            # Get or create Subsection (if any)
            subsection_obj = None
            if subsection_name:
                subsection_obj, _ = Subsection.objects.get_or_create(
                    name=subsection_name,
                    section=section_obj
                )

            # Get or create Variablehierarchy
            vh_obj, created = Variablehierarchy.objects.get_or_create(
                name=variable_name,
                section=section_obj,
                subsection=subsection_obj,
                defaults={
                    'who_can_access': var['who_can_access'],
                    'explanation': var['var_def'],
                    'is_verified': True
                }
            )

            if created:
                self.stdout.write(self.style.SUCCESS(f'Added variable: {variable_name}'))
            else:
                self.stdout.write(self.style.WARNING(f'Skipped existing variable: {variable_name}'))

        self.stdout.write(self.style.SUCCESS('Data population complete!'))
