# Generated by Django 4.0.3 on 2024-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_videoshapefile_cliopatria'),
        ('rt', '0008_elites_religion_private_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elites_religion',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='elites_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_dis_rel_grp_occ_fun',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_dis_rel_grp_occ_fun',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_obl_rel_grp_ofc_reco',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_obl_rel_grp_ofc_reco',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_press_conv',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_press_conv',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_press_conv_for_aga',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_press_conv_for_aga',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_cir_rel_lit',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_cir_rel_lit',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_cons_rel_buil',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_cons_rel_buil',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_conv',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_conv',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_prop_own_for_rel_grp',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_prop_own_for_rel_grp',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_pros',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_pros',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_wor',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_wor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_res_rel_edu',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_res_rel_edu',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gov_vio_freq_rel_grp',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gov_vio_freq_rel_grp',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='official_religion',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='official_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='religious_fragmentation',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='religious_fragmentation',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='soc_dis_rel_grp_occ_fun',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='soc_dis_rel_grp_occ_fun',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='soc_vio_freq_rel_grp',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='soc_vio_freq_rel_grp',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='sync_rel_pra_ind_beli',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='sync_rel_pra_ind_beli',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='tax_rel_adh_act_ins',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='tax_rel_adh_act_ins',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='theo_sync_dif_rel',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='theo_sync_dif_rel',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='widespread_religion',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='widespread_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
    ]
