# Generated by Django 4.0.3 on 2025-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0011_alter_elites_religion_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_dis_rel_grp_occ_fun',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_obl_rel_grp_ofc_reco',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_press_conv',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_press_conv_for_aga',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_cir_rel_lit',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_cons_rel_buil',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_conv',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_prop_own_for_rel_grp',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_pros',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_pub_wor',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gov_res_rel_edu',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='religious_fragmentation',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='soc_dis_rel_grp_occ_fun',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sync_rel_pra_ind_beli',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='tax_rel_adh_act_ins',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='theo_sync_dif_rel',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
    ]
