# Generated by Django 4.0.3 on 2025-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0014_alter_administrative_level_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_measurement_system',
            name='area_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='bridge',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='burial_site',
            name='burial_site',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='canal',
            name='canal',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='ceremonial_site',
            name='ceremonial_site',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='communal_building',
            name='communal_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='court',
            name='court',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='debt_and_credit_structure',
            name='debt_and_credit_structure',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='drinking_water_supply_system',
            name='drinking_water_supply_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='enclosure',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='entertainment_building',
            name='entertainment_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='examination_system',
            name='examination_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='fiction',
            name='fiction',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='food_storage_site',
            name='food_storage_site',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='foreign_coin',
            name='foreign_coin',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='formal_legal_code',
            name='formal_legal_code',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='full_time_bureaucrat',
            name='full_time_bureaucrat',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='general_postal_service',
            name='general_postal_service',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='geometrical_measurement_system',
            name='geometrical_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='indigenous_coin',
            name='indigenous_coin',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='irrigation_system',
            name='irrigation_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judge',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='knowledge_or_information_building',
            name='knowledge_or_information_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='length_measurement_system',
            name='length_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='lists_tables_and_classification',
            name='lists_tables_and_classification',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='market',
            name='market',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='merit_promotion',
            name='merit_promotion',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='mines_or_quarry',
            name='mines_or_quarry',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='mnemonic_device',
            name='mnemonic_device',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='non_phonetic_writing',
            name='non_phonetic_writing',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='nonwritten_record',
            name='nonwritten_record',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='occupational_complexity',
            name='occupational_complexity',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='other_measurement_system',
            name='other_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='other_special_purpose_site',
            name='other_special_purpose_site',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='other_utilitarian_public_building',
            name='other_utilitarian_public_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='paper_currency',
            name='paper_currency',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='philosophy',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='phonetic_alphabetic_writing',
            name='phonetic_alphabetic_writing',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='postal_station',
            name='postal_station',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='practical_literature',
            name='practical_literature',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='precious_metal',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='professional_lawyer',
            name='professional_lawyer',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='professional_military_officer',
            name='professional_military_officer',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='professional_priesthood',
            name='professional_priesthood',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='professional_soldier',
            name='professional_soldier',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='religious_literature',
            name='religious_literature',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='road',
            name='road',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sacred_text',
            name='sacred_text',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='scientific_literature',
            name='scientific_literature',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='special_purpose_house',
            name='special_purpose_house',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='special_purpose_site',
            name='special_purpose_site',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='specialized_government_building',
            name='specialized_government_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='store_of_wealth',
            name='store_of_wealth',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='symbolic_building',
            name='symbolic_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='time_measurement_system',
            name='time_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='trading_emporia',
            name='trading_emporia',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='utilitarian_public_building',
            name='utilitarian_public_building',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='volume_measurement_system',
            name='volume_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='weight_measurement_system',
            name='weight_measurement_system',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='written_record',
            name='written_record',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
    ]
