from django.urls import path

from . import views
from .specific_views import downloads

urlpatterns = [
    path("generalvars/", views.generalvars_view, name="generalvars"),
    path(
        "download-csv-general-all/",
        downloads.download_csv_all_general,
        name="download_csv_all_general",
    ),
    path(
        "polity_research_assistant/create/",
        views.Polity_research_assistantCreateView.as_view(),
        name="polity_research_assistant-create",
    ),
    path(
        "polity_research_assistants/",
        views.Polity_research_assistantListView.as_view(),
        name="polity_research_assistants",
    ),
    path(
        "polity_research_assistants_all/",
        views.Polity_research_assistantListAllView.as_view(),
        name="polity_research_assistants_all",
    ),
    path(
        "polity_research_assistant/<int:pk>",
        views.Polity_research_assistantDetailView.as_view(),
        name="polity_research_assistant-detail",
    ),
    path(
        "polity_research_assistant/<int:pk>/update/",
        views.Polity_research_assistantUpdateView.as_view(),
        name="polity_research_assistant-update",
    ),
    path(
        "polity_research_assistant/<int:pk>/delete/",
        views.Polity_research_assistantDeleteView.as_view(),
        name="polity_research_assistant-delete",
    ),
    path(
        "polity_research_assistantdownload/",
        downloads.polity_research_assistant_download_view,
        name="polity_research_assistant-download",
    ),
    path(
        "polity_research_assistantmetadownload/",
        downloads.polity_research_assistant_meta_download_view,
        name="polity_research_assistant-metadownload",
    ),
    path(
        "polity_utm_zone/create/",
        views.Polity_utm_zoneCreateView.as_view(),
        name="polity_utm_zone-create",
    ),
    path(
        "polity_utm_zones/",
        views.Polity_utm_zoneListView.as_view(),
        name="polity_utm_zones",
    ),
    path(
        "polity_utm_zones_all/",
        views.Polity_utm_zoneListAllView.as_view(),
        name="polity_utm_zones_all",
    ),
    path(
        "polity_utm_zone/<int:pk>",
        views.Polity_utm_zoneDetailView.as_view(),
        name="polity_utm_zone-detail",
    ),
    path(
        "polity_utm_zone/<int:pk>/update/",
        views.Polity_utm_zoneUpdateView.as_view(),
        name="polity_utm_zone-update",
    ),
    path(
        "polity_utm_zone/<int:pk>/delete/",
        views.Polity_utm_zoneDeleteView.as_view(),
        name="polity_utm_zone-delete",
    ),
    path(
        "polity_utm_zonedownload/",
        downloads.polity_utm_zone_download_view,
        name="polity_utm_zone-download",
    ),
    path(
        "polity_utm_zonemetadownload/",
        downloads.polity_utm_zone_meta_download_view,
        name="polity_utm_zone-metadownload",
    ),
    path(
        "polity_original_name/create/",
        views.Polity_original_nameCreateView.as_view(),
        name="polity_original_name-create",
    ),
    path(
        "polity_original_names/",
        views.Polity_original_nameListView.as_view(),
        name="polity_original_names",
    ),
    path(
        "polity_original_names_all/",
        views.Polity_original_nameListAllView.as_view(),
        name="polity_original_names_all",
    ),
    path(
        "polity_original_name/<int:pk>",
        views.Polity_original_nameDetailView.as_view(),
        name="polity_original_name-detail",
    ),
    path(
        "polity_original_name/<int:pk>/update/",
        views.Polity_original_nameUpdateView.as_view(),
        name="polity_original_name-update",
    ),
    path(
        "polity_original_name/<int:pk>/delete/",
        views.Polity_original_nameDeleteView.as_view(),
        name="polity_original_name-delete",
    ),
    path(
        "polity_original_namedownload/",
        downloads.polity_original_name_download_view,
        name="polity_original_name-download",
    ),
    path(
        "polity_original_namemetadownload/",
        downloads.polity_original_name_meta_download_view,
        name="polity_original_name-metadownload",
    ),
    path(
        "polity_alternative_name/create/",
        views.Polity_alternative_nameCreateView.as_view(),
        name="polity_alternative_name-create",
    ),
    path(
        "polity_alternative_names/",
        views.Polity_alternative_nameListView.as_view(),
        name="polity_alternative_names",
    ),
    path(
        "polity_alternative_names_all/",
        views.Polity_alternative_nameListAllView.as_view(),
        name="polity_alternative_names_all",
    ),
    path(
        "polity_alternative_name/<int:pk>",
        views.Polity_alternative_nameDetailView.as_view(),
        name="polity_alternative_name-detail",
    ),
    path(
        "polity_alternative_name/<int:pk>/update/",
        views.Polity_alternative_nameUpdateView.as_view(),
        name="polity_alternative_name-update",
    ),
    path(
        "polity_alternative_name/<int:pk>/delete/",
        views.Polity_alternative_nameDeleteView.as_view(),
        name="polity_alternative_name-delete",
    ),
    path(
        "polity_alternative_namedownload/",
        downloads.polity_alternative_name_download_view,
        name="polity_alternative_name-download",
    ),
    path(
        "polity_alternative_namemetadownload/",
        downloads.polity_alternative_name_meta_download_view,
        name="polity_alternative_name-metadownload",
    ),
    path(
        "polity_peak_years/create/",
        views.Polity_peak_yearsCreateView.as_view(),
        name="polity_peak_years-create",
    ),
    path(
        "polity_peak_yearss/",
        views.Polity_peak_yearsListView.as_view(),
        name="polity_peak_yearss",
    ),
    path(
        "polity_peak_yearss_all/",
        views.Polity_peak_yearsListAllView.as_view(),
        name="polity_peak_yearss_all",
    ),
    path(
        "polity_peak_years/<int:pk>",
        views.Polity_peak_yearsDetailView.as_view(),
        name="polity_peak_years-detail",
    ),
    path(
        "polity_peak_years/<int:pk>/update/",
        views.Polity_peak_yearsUpdateView.as_view(),
        name="polity_peak_years-update",
    ),
    path(
        "polity_peak_years/<int:pk>/delete/",
        views.Polity_peak_yearsDeleteView.as_view(),
        name="polity_peak_years-delete",
    ),
    path(
        "polity_peak_yearsdownload/",
        downloads.polity_peak_years_download_view,
        name="polity_peak_years-download",
    ),
    path(
        "polity_peak_yearsmetadownload/",
        downloads.polity_peak_years_meta_download_view,
        name="polity_peak_years-metadownload",
    ),
    path(
        "polity_duration/create/",
        views.Polity_durationCreateView.as_view(),
        name="polity_duration-create",
    ),
    path(
        "polity_durations/",
        views.Polity_durationListView.as_view(),
        name="polity_durations",
    ),
    path(
        "polity_durations_all/",
        views.Polity_durationListAllView.as_view(),
        name="polity_durations_all",
    ),
    path(
        "polity_duration/<int:pk>",
        views.Polity_durationDetailView.as_view(),
        name="polity_duration-detail",
    ),
    path(
        "polity_duration/<int:pk>/update/",
        views.Polity_durationUpdateView.as_view(),
        name="polity_duration-update",
    ),
    path(
        "polity_duration/<int:pk>/delete/",
        views.Polity_durationDeleteView.as_view(),
        name="polity_duration-delete",
    ),
    path(
        "polity_durationdownload/",
        downloads.polity_duration_download_view,
        name="polity_duration-download",
    ),
    path(
        "polity_durationmetadownload/",
        downloads.polity_duration_meta_download_view,
        name="polity_duration-metadownload",
    ),
    path(
        "polity_degree_of_centralization/create/",
        views.Polity_degree_of_centralizationCreateView.as_view(),
        name="polity_degree_of_centralization-create",
    ),
    path(
        "polity_degree_of_centralizations/",
        views.Polity_degree_of_centralizationListView.as_view(),
        name="polity_degree_of_centralizations",
    ),
    path(
        "polity_degree_of_centralizations_all/",
        views.Polity_degree_of_centralizationListAllView.as_view(),
        name="polity_degree_of_centralizations_all",
    ),
    path(
        "polity_degree_of_centralization/<int:pk>",
        views.Polity_degree_of_centralizationDetailView.as_view(),
        name="polity_degree_of_centralization-detail",
    ),
    path(
        "polity_degree_of_centralization/<int:pk>/update/",
        views.Polity_degree_of_centralizationUpdateView.as_view(),
        name="polity_degree_of_centralization-update",
    ),
    path(
        "polity_degree_of_centralization/<int:pk>/delete/",
        views.Polity_degree_of_centralizationDeleteView.as_view(),
        name="polity_degree_of_centralization-delete",
    ),
    path(
        "polity_degree_of_centralizationdownload/",
        downloads.polity_degree_of_centralization_download_view,
        name="polity_degree_of_centralization-download",
    ),
    path(
        "polity_degree_of_centralizationmetadownload/",
        downloads.polity_degree_of_centralization_meta_download_view,
        name="polity_degree_of_centralization-metadownload",
    ),
    path(
        "polity_suprapolity_relations/create/",
        views.Polity_suprapolity_relationsCreateView.as_view(),
        name="polity_suprapolity_relations-create",
    ),
    path(
        "polity_suprapolity_relationss/",
        views.Polity_suprapolity_relationsListView.as_view(),
        name="polity_suprapolity_relationss",
    ),
    path(
        "polity_suprapolity_relationss_all/",
        views.Polity_suprapolity_relationsListAllView.as_view(),
        name="polity_suprapolity_relationss_all",
    ),
    path(
        "polity_suprapolity_relations/<int:pk>",
        views.Polity_suprapolity_relationsDetailView.as_view(),
        name="polity_suprapolity_relations-detail",
    ),
    path(
        "polity_suprapolity_relations/<int:pk>/update/",
        views.Polity_suprapolity_relationsUpdateView.as_view(),
        name="polity_suprapolity_relations-update",
    ),
    path(
        "polity_suprapolity_relations/<int:pk>/delete/",
        views.Polity_suprapolity_relationsDeleteView.as_view(),
        name="polity_suprapolity_relations-delete",
    ),
    path(
        "polity_suprapolity_relationsdownload/",
        downloads.polity_suprapolity_relations_download_view,
        name="polity_suprapolity_relations-download",
    ),
    path(
        "polity_suprapolity_relationsmetadownload/",
        downloads.polity_suprapolity_relations_meta_download_view,
        name="polity_suprapolity_relations-metadownload",
    ),
    path(
        "polity_capital/create/",
        views.Polity_capitalCreateView.as_view(),
        name="polity_capital-create",
    ),
    path(
        "polity_capitals/",
        views.Polity_capitalListView.as_view(),
        name="polity_capitals",
    ),
    path(
        "polity_capitals_all/",
        views.Polity_capitalListAllView.as_view(),
        name="polity_capitals_all",
    ),
    path(
        "polity_capital/<int:pk>",
        views.Polity_capitalDetailView.as_view(),
        name="polity_capital-detail",
    ),
    path(
        "polity_capital/<int:pk>/update/",
        views.Polity_capitalUpdateView.as_view(),
        name="polity_capital-update",
    ),
    path(
        "polity_capital/<int:pk>/delete/",
        views.Polity_capitalDeleteView.as_view(),
        name="polity_capital-delete",
    ),
    path(
        "polity_capitaldownload/",
        downloads.polity_capital_download_view,
        name="polity_capital-download",
    ),
    path(
        "polity_capitalmetadownload/",
        downloads.polity_capital_meta_download_view,
        name="polity_capital-metadownload",
    ),
    path(
        "polity_language/create/",
        views.Polity_languageCreateView.as_view(),
        name="polity_language-create",
    ),
    path(
        "polity_languages/",
        views.Polity_languageListView.as_view(),
        name="polity_languages",
    ),
    path(
        "polity_languages_all/",
        views.Polity_languageListAllView.as_view(),
        name="polity_languages_all",
    ),
    path(
        "polity_language/<int:pk>",
        views.Polity_languageDetailView.as_view(),
        name="polity_language-detail",
    ),
    path(
        "polity_language/<int:pk>/update/",
        views.Polity_languageUpdateView.as_view(),
        name="polity_language-update",
    ),
    path(
        "polity_language/<int:pk>/delete/",
        views.Polity_languageDeleteView.as_view(),
        name="polity_language-delete",
    ),
    path(
        "polity_languagedownload/",
        downloads.polity_language_download_view,
        name="polity_language-download",
    ),
    path(
        "polity_languagemetadownload/",
        downloads.polity_language_meta_download_view,
        name="polity_language-metadownload",
    ),
    path(
        "polity_linguistic_family/create/",
        views.Polity_linguistic_familyCreateView.as_view(),
        name="polity_linguistic_family-create",
    ),
    path(
        "polity_linguistic_familys/",
        views.Polity_linguistic_familyListView.as_view(),
        name="polity_linguistic_familys",
    ),
    path(
        "polity_linguistic_familys_all/",
        views.Polity_linguistic_familyListAllView.as_view(),
        name="polity_linguistic_familys_all",
    ),
    path(
        "polity_linguistic_family/<int:pk>",
        views.Polity_linguistic_familyDetailView.as_view(),
        name="polity_linguistic_family-detail",
    ),
    path(
        "polity_linguistic_family/<int:pk>/update/",
        views.Polity_linguistic_familyUpdateView.as_view(),
        name="polity_linguistic_family-update",
    ),
    path(
        "polity_linguistic_family/<int:pk>/delete/",
        views.Polity_linguistic_familyDeleteView.as_view(),
        name="polity_linguistic_family-delete",
    ),
    path(
        "polity_linguistic_familydownload/",
        downloads.polity_linguistic_family_download_view,
        name="polity_linguistic_family-download",
    ),
    path(
        "polity_linguistic_familymetadownload/",
        downloads.polity_linguistic_family_meta_download_view,
        name="polity_linguistic_family-metadownload",
    ),
    path(
        "polity_language_genus/create/",
        views.Polity_language_genusCreateView.as_view(),
        name="polity_language_genus-create",
    ),
    path(
        "polity_language_genuss/",
        views.Polity_language_genusListView.as_view(),
        name="polity_language_genuss",
    ),
    path(
        "polity_language_genuss_all/",
        views.Polity_language_genusListAllView.as_view(),
        name="polity_language_genuss_all",
    ),
    path(
        "polity_language_genus/<int:pk>",
        views.Polity_language_genusDetailView.as_view(),
        name="polity_language_genus-detail",
    ),
    path(
        "polity_language_genus/<int:pk>/update/",
        views.Polity_language_genusUpdateView.as_view(),
        name="polity_language_genus-update",
    ),
    path(
        "polity_language_genus/<int:pk>/delete/",
        views.Polity_language_genusDeleteView.as_view(),
        name="polity_language_genus-delete",
    ),
    path(
        "polity_language_genusdownload/",
        downloads.polity_language_genus_download_view,
        name="polity_language_genus-download",
    ),
    path(
        "polity_language_genusmetadownload/",
        downloads.polity_language_genus_meta_download_view,
        name="polity_language_genus-metadownload",
    ),
    path(
        "polity_religion_genus/create/",
        views.Polity_religion_genusCreateView.as_view(),
        name="polity_religion_genus-create",
    ),
    path(
        "polity_religion_genuss/",
        views.Polity_religion_genusListView.as_view(),
        name="polity_religion_genuss",
    ),
    path(
        "polity_religion_genuss_all/",
        views.Polity_religion_genusListAllView.as_view(),
        name="polity_religion_genuss_all",
    ),
    path(
        "polity_religion_genus/<int:pk>",
        views.Polity_religion_genusDetailView.as_view(),
        name="polity_religion_genus-detail",
    ),
    path(
        "polity_religion_genus/<int:pk>/update/",
        views.Polity_religion_genusUpdateView.as_view(),
        name="polity_religion_genus-update",
    ),
    path(
        "polity_religion_genus/<int:pk>/delete/",
        views.Polity_religion_genusDeleteView.as_view(),
        name="polity_religion_genus-delete",
    ),
    path(
        "polity_religion_genusdownload/",
        downloads.polity_religion_genus_download_view,
        name="polity_religion_genus-download",
    ),
    path(
        "polity_religion_genusmetadownload/",
        downloads.polity_religion_genus_meta_download_view,
        name="polity_religion_genus-metadownload",
    ),
    path(
        "polity_religion_family/create/",
        views.Polity_religion_familyCreateView.as_view(),
        name="polity_religion_family-create",
    ),
    path(
        "polity_religion_familys/",
        views.Polity_religion_familyListView.as_view(),
        name="polity_religion_familys",
    ),
    path(
        "polity_religion_familys_all/",
        views.Polity_religion_familyListAllView.as_view(),
        name="polity_religion_familys_all",
    ),
    path(
        "polity_religion_family/<int:pk>",
        views.Polity_religion_familyDetailView.as_view(),
        name="polity_religion_family-detail",
    ),
    path(
        "polity_religion_family/<int:pk>/update/",
        views.Polity_religion_familyUpdateView.as_view(),
        name="polity_religion_family-update",
    ),
    path(
        "polity_religion_family/<int:pk>/delete/",
        views.Polity_religion_familyDeleteView.as_view(),
        name="polity_religion_family-delete",
    ),
    path(
        "polity_religion_familydownload/",
        downloads.polity_religion_family_download_view,
        name="polity_religion_family-download",
    ),
    path(
        "polity_religion_familymetadownload/",
        downloads.polity_religion_family_meta_download_view,
        name="polity_religion_family-metadownload",
    ),
    path(
        "polity_religion/create/",
        views.Polity_religionCreateView.as_view(),
        name="polity_religion-create",
    ),
    path(
        "polity_religions/",
        views.Polity_religionListView.as_view(),
        name="polity_religions",
    ),
    path(
        "polity_religions_all/",
        views.Polity_religionListAllView.as_view(),
        name="polity_religions_all",
    ),
    path(
        "polity_religion/<int:pk>",
        views.Polity_religionDetailView.as_view(),
        name="polity_religion-detail",
    ),
    path(
        "polity_religion/<int:pk>/update/",
        views.Polity_religionUpdateView.as_view(),
        name="polity_religion-update",
    ),
    path(
        "polity_religion/<int:pk>/delete/",
        views.Polity_religionDeleteView.as_view(),
        name="polity_religion-delete",
    ),
    path(
        "polity_religiondownload/",
        downloads.polity_religion_download_view,
        name="polity_religion-download",
    ),
    path(
        "polity_religionmetadownload/",
        downloads.polity_religion_meta_download_view,
        name="polity_religion-metadownload",
    ),
    path(
        "polity_relationship_to_preceding_entity/create/",
        views.Polity_relationship_to_preceding_entityCreateView.as_view(),
        name="polity_relationship_to_preceding_entity-create",
    ),
    path(
        "polity_relationship_to_preceding_entitys/",
        views.Polity_relationship_to_preceding_entityListView.as_view(),
        name="polity_relationship_to_preceding_entitys",
    ),
    path(
        "polity_relationship_to_preceding_entitys_all/",
        views.Polity_relationship_to_preceding_entityListAllView.as_view(),
        name="polity_relationship_to_preceding_entitys_all",
    ),
    path(
        "polity_relationship_to_preceding_entity/<int:pk>",
        views.Polity_relationship_to_preceding_entityDetailView.as_view(),
        name="polity_relationship_to_preceding_entity-detail",
    ),
    path(
        "polity_relationship_to_preceding_entity/<int:pk>/update/",
        views.Polity_relationship_to_preceding_entityUpdateView.as_view(),
        name="polity_relationship_to_preceding_entity-update",
    ),
    path(
        "polity_relationship_to_preceding_entity/<int:pk>/delete/",
        views.Polity_relationship_to_preceding_entityDeleteView.as_view(),
        name="polity_relationship_to_preceding_entity-delete",
    ),
    path(
        "polity_relationship_to_preceding_entitydownload/",
        downloads.polity_relationship_to_preceding_entity_download_view,
        name="polity_relationship_to_preceding_entity-download",
    ),
    path(
        "polity_relationship_to_preceding_entitymetadownload/",
        downloads.polity_relationship_to_preceding_entity_meta_download_view,
        name="polity_relationship_to_preceding_entity-metadownload",
    ),
    path(
        "polity_preceding_entity/create/",
        views.Polity_preceding_entityCreateView.as_view(),
        name="polity_preceding_entity-create",
    ),
    path(
        "polity_preceding_entitys/",
        views.Polity_preceding_entityListView.as_view(),
        name="polity_preceding_entitys",
    ),
    path(
        "polity_preceding_entitys_all/",
        views.Polity_preceding_entityListAllView.as_view(),
        name="polity_preceding_entitys_all",
    ),
    path(
        "polity_preceding_entity/<int:pk>",
        views.Polity_preceding_entityDetailView.as_view(),
        name="polity_preceding_entity-detail",
    ),
    path(
        "polity_preceding_entity/<int:pk>/update/",
        views.Polity_preceding_entityUpdateView.as_view(),
        name="polity_preceding_entity-update",
    ),
    path(
        "polity_preceding_entity/<int:pk>/delete/",
        views.Polity_preceding_entityDeleteView.as_view(),
        name="polity_preceding_entity-delete",
    ),
    path(
        "polity_preceding_entitydownload/",
        downloads.polity_preceding_entity_download_view,
        name="polity_preceding_entity-download",
    ),
    path(
        "polity_preceding_entitymetadownload/",
        downloads.polity_preceding_entity_meta_download_view,
        name="polity_preceding_entity-metadownload",
    ),
    path(
        "polity_succeeding_entity/create/",
        views.Polity_succeeding_entityCreateView.as_view(),
        name="polity_succeeding_entity-create",
    ),
    path(
        "polity_succeeding_entitys/",
        views.Polity_succeeding_entityListView.as_view(),
        name="polity_succeeding_entitys",
    ),
    path(
        "polity_succeeding_entitys_all/",
        views.Polity_succeeding_entityListAllView.as_view(),
        name="polity_succeeding_entitys_all",
    ),
    path(
        "polity_succeeding_entity/<int:pk>",
        views.Polity_succeeding_entityDetailView.as_view(),
        name="polity_succeeding_entity-detail",
    ),
    path(
        "polity_succeeding_entity/<int:pk>/update/",
        views.Polity_succeeding_entityUpdateView.as_view(),
        name="polity_succeeding_entity-update",
    ),
    path(
        "polity_succeeding_entity/<int:pk>/delete/",
        views.Polity_succeeding_entityDeleteView.as_view(),
        name="polity_succeeding_entity-delete",
    ),
    path(
        "polity_succeeding_entitydownload/",
        downloads.polity_succeeding_entity_download_view,
        name="polity_succeeding_entity-download",
    ),
    path(
        "polity_succeeding_entitymetadownload/",
        downloads.polity_succeeding_entity_meta_download_view,
        name="polity_succeeding_entity-metadownload",
    ),
    path(
        "polity_supracultural_entity/create/",
        views.Polity_supracultural_entityCreateView.as_view(),
        name="polity_supracultural_entity-create",
    ),
    path(
        "polity_supracultural_entitys/",
        views.Polity_supracultural_entityListView.as_view(),
        name="polity_supracultural_entitys",
    ),
    path(
        "polity_supracultural_entitys_all/",
        views.Polity_supracultural_entityListAllView.as_view(),
        name="polity_supracultural_entitys_all",
    ),
    path(
        "polity_supracultural_entity/<int:pk>",
        views.Polity_supracultural_entityDetailView.as_view(),
        name="polity_supracultural_entity-detail",
    ),
    path(
        "polity_supracultural_entity/<int:pk>/update/",
        views.Polity_supracultural_entityUpdateView.as_view(),
        name="polity_supracultural_entity-update",
    ),
    path(
        "polity_supracultural_entity/<int:pk>/delete/",
        views.Polity_supracultural_entityDeleteView.as_view(),
        name="polity_supracultural_entity-delete",
    ),
    path(
        "polity_supracultural_entitydownload/",
        downloads.polity_supracultural_entity_download_view,
        name="polity_supracultural_entity-download",
    ),
    path(
        "polity_supracultural_entitymetadownload/",
        downloads.polity_supracultural_entity_meta_download_view,
        name="polity_supracultural_entity-metadownload",
    ),
    path(
        "polity_scale_of_supracultural_interaction/create/",
        views.Polity_scale_of_supracultural_interactionCreateView.as_view(),
        name="polity_scale_of_supracultural_interaction-create",
    ),
    path(
        "polity_scale_of_supracultural_interactions/",
        views.Polity_scale_of_supracultural_interactionListView.as_view(),
        name="polity_scale_of_supracultural_interactions",
    ),
    path(
        "polity_scale_of_supracultural_interactions_all/",
        views.Polity_scale_of_supracultural_interactionListAllView.as_view(),
        name="polity_scale_of_supracultural_interactions_all",
    ),
    path(
        "polity_scale_of_supracultural_interaction/<int:pk>",
        views.Polity_scale_of_supracultural_interactionDetailView.as_view(),
        name="polity_scale_of_supracultural_interaction-detail",
    ),
    path(
        "polity_scale_of_supracultural_interaction/<int:pk>/update/",
        views.Polity_scale_of_supracultural_interactionUpdateView.as_view(),
        name="polity_scale_of_supracultural_interaction-update",
    ),
    path(
        "polity_scale_of_supracultural_interaction/<int:pk>/delete/",
        views.Polity_scale_of_supracultural_interactionDeleteView.as_view(),
        name="polity_scale_of_supracultural_interaction-delete",
    ),
    path(
        "polity_scale_of_supracultural_interactiondownload/",
        downloads.polity_scale_of_supracultural_interaction_download_view,
        name="polity_scale_of_supracultural_interaction-download",
    ),
    path(
        "polity_scale_of_supracultural_interactionmetadownload/",
        downloads.polity_scale_of_supracultural_interaction_meta_download_view,
        name="polity_scale_of_supracultural_interaction-metadownload",
    ),
    path(
        "polity_alternate_religion_genus/create/",
        views.Polity_alternate_religion_genusCreateView.as_view(),
        name="polity_alternate_religion_genus-create",
    ),
    path(
        "polity_alternate_religion_genuss/",
        views.Polity_alternate_religion_genusListView.as_view(),
        name="polity_alternate_religion_genuss",
    ),
    path(
        "polity_alternate_religion_genuss_all/",
        views.Polity_alternate_religion_genusListAllView.as_view(),
        name="polity_alternate_religion_genuss_all",
    ),
    path(
        "polity_alternate_religion_genus/<int:pk>",
        views.Polity_alternate_religion_genusDetailView.as_view(),
        name="polity_alternate_religion_genus-detail",
    ),
    path(
        "polity_alternate_religion_genus/<int:pk>/update/",
        views.Polity_alternate_religion_genusUpdateView.as_view(),
        name="polity_alternate_religion_genus-update",
    ),
    path(
        "polity_alternate_religion_genus/<int:pk>/delete/",
        views.Polity_alternate_religion_genusDeleteView.as_view(),
        name="polity_alternate_religion_genus-delete",
    ),
    path(
        "polity_alternate_religion_genusdownload/",
        downloads.polity_alternate_religion_genus_download_view,
        name="polity_alternate_religion_genus-download",
    ),
    path(
        "polity_alternate_religion_genusmetadownload/",
        downloads.polity_alternate_religion_genus_meta_download_view,
        name="polity_alternate_religion_genus-metadownload",
    ),
    path(
        "polity_alternate_religion_family/create/",
        views.Polity_alternate_religion_familyCreateView.as_view(),
        name="polity_alternate_religion_family-create",
    ),
    path(
        "polity_alternate_religion_familys/",
        views.Polity_alternate_religion_familyListView.as_view(),
        name="polity_alternate_religion_familys",
    ),
    path(
        "polity_alternate_religion_familys_all/",
        views.Polity_alternate_religion_familyListAllView.as_view(),
        name="polity_alternate_religion_familys_all",
    ),
    path(
        "polity_alternate_religion_family/<int:pk>",
        views.Polity_alternate_religion_familyDetailView.as_view(),
        name="polity_alternate_religion_family-detail",
    ),
    path(
        "polity_alternate_religion_family/<int:pk>/update/",
        views.Polity_alternate_religion_familyUpdateView.as_view(),
        name="polity_alternate_religion_family-update",
    ),
    path(
        "polity_alternate_religion_family/<int:pk>/delete/",
        views.Polity_alternate_religion_familyDeleteView.as_view(),
        name="polity_alternate_religion_family-delete",
    ),
    path(
        "polity_alternate_religion_familydownload/",
        downloads.polity_alternate_religion_family_download_view,
        name="polity_alternate_religion_family-download",
    ),
    path(
        "polity_alternate_religion_familymetadownload/",
        downloads.polity_alternate_religion_family_meta_download_view,
        name="polity_alternate_religion_family-metadownload",
    ),
    path(
        "polity_alternate_religion/create/",
        views.Polity_alternate_religionCreateView.as_view(),
        name="polity_alternate_religion-create",
    ),
    path(
        "polity_alternate_religions/",
        views.Polity_alternate_religionListView.as_view(),
        name="polity_alternate_religions",
    ),
    path(
        "polity_alternate_religions_all/",
        views.Polity_alternate_religionListAllView.as_view(),
        name="polity_alternate_religions_all",
    ),
    path(
        "polity_alternate_religion/<int:pk>",
        views.Polity_alternate_religionDetailView.as_view(),
        name="polity_alternate_religion-detail",
    ),
    path(
        "polity_alternate_religion/<int:pk>/update/",
        views.Polity_alternate_religionUpdateView.as_view(),
        name="polity_alternate_religion-update",
    ),
    path(
        "polity_alternate_religion/<int:pk>/delete/",
        views.Polity_alternate_religionDeleteView.as_view(),
        name="polity_alternate_religion-delete",
    ),
    path(
        "polity_alternate_religiondownload/",
        downloads.polity_alternate_religion_download_view,
        name="polity_alternate_religion-download",
    ),
    path(
        "polity_alternate_religionmetadownload/",
        downloads.polity_alternate_religion_meta_download_view,
        name="polity_alternate_religion-metadownload",
    ),
    path(
        "polity_expert/create/",
        views.Polity_expertCreateView.as_view(),
        name="polity_expert-create",
    ),
    path(
        "polity_experts/", views.Polity_expertListView.as_view(), name="polity_experts"
    ),
    path(
        "polity_experts_all/",
        views.Polity_expertListAllView.as_view(),
        name="polity_experts_all",
    ),
    path(
        "polity_expert/<int:pk>",
        views.Polity_expertDetailView.as_view(),
        name="polity_expert-detail",
    ),
    path(
        "polity_expert/<int:pk>/update/",
        views.Polity_expertUpdateView.as_view(),
        name="polity_expert-update",
    ),
    path(
        "polity_expert/<int:pk>/delete/",
        views.Polity_expertDeleteView.as_view(),
        name="polity_expert-delete",
    ),
    path(
        "polity_expertdownload/",
        downloads.polity_expert_download_view,
        name="polity_expert-download",
    ),
    path(
        "polity_expertmetadownload/",
        downloads.polity_expert_meta_download_view,
        name="polity_expert-metadownload",
    ),
    path(
        "polity_editor/create/",
        views.Polity_editorCreateView.as_view(),
        name="polity_editor-create",
    ),
    path(
        "polity_editors/", views.Polity_editorListView.as_view(), name="polity_editors"
    ),
    path(
        "polity_editors_all/",
        views.Polity_editorListAllView.as_view(),
        name="polity_editors_all",
    ),
    path(
        "polity_editor/<int:pk>",
        views.Polity_editorDetailView.as_view(),
        name="polity_editor-detail",
    ),
    path(
        "polity_editor/<int:pk>/update/",
        views.Polity_editorUpdateView.as_view(),
        name="polity_editor-update",
    ),
    path(
        "polity_editor/<int:pk>/delete/",
        views.Polity_editorDeleteView.as_view(),
        name="polity_editor-delete",
    ),
    path(
        "polity_editordownload/",
        downloads.polity_editor_download_view,
        name="polity_editor-download",
    ),
    path(
        "polity_editormetadownload/",
        downloads.polity_editor_meta_download_view,
        name="polity_editor-metadownload",
    ),
    path(
        "polity_religious_tradition/create/",
        views.Polity_religious_traditionCreateView.as_view(),
        name="polity_religious_tradition-create",
    ),
    path(
        "polity_religious_traditions/",
        views.Polity_religious_traditionListView.as_view(),
        name="polity_religious_traditions",
    ),
    path(
        "polity_religious_traditions_all/",
        views.Polity_religious_traditionListAllView.as_view(),
        name="polity_religious_traditions_all",
    ),
    path(
        "polity_religious_tradition/<int:pk>",
        views.Polity_religious_traditionDetailView.as_view(),
        name="polity_religious_tradition-detail",
    ),
    path(
        "polity_religious_tradition/<int:pk>/update/",
        views.Polity_religious_traditionUpdateView.as_view(),
        name="polity_religious_tradition-update",
    ),
    path(
        "polity_religious_tradition/<int:pk>/delete/",
        views.Polity_religious_traditionDeleteView.as_view(),
        name="polity_religious_tradition-delete",
    ),
    path(
        "polity_religious_traditiondownload/",
        downloads.polity_religious_tradition_download_view,
        name="polity_religious_tradition-download",
    ),
    path(
        "polity_religious_traditionmetadownload/",
        downloads.polity_religious_tradition_meta_download_view,
        name="polity_religious_tradition-metadownload",
    ),
]
