from django.urls import path

from . import views
from .specific_views import downloads
from ..generic_views import GenericMultipleDownloadView, VariableView, ProblematicDataView
from ..constants import SUBSECTIONS

APP_LABEL = "wf"

urlpatterns = [
    path(
        "wfvars/",
        VariableView.as_view(
            app_label=APP_LABEL,
            template_name="wf/wfvars.html"
        ),
        name="wfvars"
    ),
    path(
        "problematic_wf_data_table/",
        ProblematicDataView.as_view(
            app_label=APP_LABEL,
            template_name="wf/problematic_wf_data_table.html"
        ),
        name="problematic_wf_data_table",
    ),
    path(
        "download-csv-wf-all/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            prefix="warfare_data_"
        ),
        name="download_csv_all_wf",
    ),
    # General/category downloads
    path(
        "download_csv_fortifications/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.Fortifications,
            prefix="warfare_fortifications_",
        ),
        name="download_csv_fortifications",
    ),
    path(
        "download_csv_military_use_of_metals/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.MilitaryUseOfMetals,
            prefix="warfare_military_use_of_metals_",
        ),
        name="download_csv_military_use_of_metals",
    ),
    path(
        "download_csv_projectiles/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.Projectiles,
            prefix="warfare_projectiles_",
        ),
        name="download_csv_projectiles",
    ),
    path(
        "download_csv_handheld_weapons/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.HandheldWeapons,
            prefix="warfare_handheld_weapons_",
        ),
        name="download_csv_handheld_weapons",
    ),
    path(
        "download_csv_animals_used_in_warfare/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.AnimalsUsedInWarfare,
            prefix="warfare_animals_used_in_warfare_",
        ),
        name="download_csv_animals_used_in_warfare",
    ),
    path(
        "download_csv_armor/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.Armor,
            prefix="warfare_armor_",
        ),
        name="download_csv_armor",
    ),
    path(
        "download_csv_naval_technology/",
        GenericMultipleDownloadView.as_view(
            app_label=APP_LABEL,
            subsection=SUBSECTIONS.wf.NavalTechnology,
            prefix="warfare_naval_technology_",
        ),
        name="download_csv_naval_technology",
    ),
    # Long wall
    path(
        "long_wall/create/",
        views.Long_wallCreateView.as_view(),
        name="long_wall-create",
    ),
    path("long_walls/", views.Long_wallListView.as_view(), name="long_walls"),
    path(
        "long_walls_all/",
        views.Long_wallListAllView.as_view(),
        name="long_walls_all",
    ),
    path(
        "long_wall/<int:pk>",
        views.Long_wallDetailView.as_view(),
        name="long_wall-detail",
    ),
    path(
        "long_wall/<int:pk>/update/",
        views.Long_wallUpdateView.as_view(),
        name="long_wall-update",
    ),
    path(
        "long_wall/<int:pk>/delete/",
        views.Long_wallDeleteView.as_view(),
        name="long_wall-delete",
    ),
    path(
        "long_walldownload/",
        downloads.long_wall_download_view,
        name="long_wall-download",
    ),
    path(
        "long_wallmetadownload/",
        downloads.long_wall_meta_download_view,
        name="long_wall-metadownload",
    ),
    # Copper
    path(
        "copper/create/",
        views.CopperCreateView.as_view(),
        name="copper-create",
    ),
    path("coppers/", views.CopperListView.as_view(), name="coppers"),
    path(
        "coppers_all/", views.CopperListAllView.as_view(), name="coppers_all"
    ),
    path(
        "copper/<int:pk>",
        views.CopperDetailView.as_view(),
        name="copper-detail",
    ),
    path(
        "copper/<int:pk>/update/",
        views.CopperUpdateView.as_view(),
        name="copper-update",
    ),
    path(
        "copper/<int:pk>/delete/",
        views.CopperDeleteView.as_view(),
        name="copper-delete",
    ),
    path(
        "copperdownload/", downloads.copper_download_view, name="copper-download"
    ),
    path(
        "coppermetadownload/",
        downloads.copper_meta_download_view,
        name="copper-metadownload",
    ),
    # Bronze
    path(
        "bronze/create/",
        views.BronzeCreateView.as_view(),
        name="bronze-create",
    ),
    path("bronzes/", views.BronzeListView.as_view(), name="bronzes"),
    path(
        "bronzes_all/", views.BronzeListAllView.as_view(), name="bronzes_all"
    ),
    path(
        "bronze/<int:pk>",
        views.BronzeDetailView.as_view(),
        name="bronze-detail",
    ),
    path(
        "bronze/<int:pk>/update/",
        views.BronzeUpdateView.as_view(),
        name="bronze-update",
    ),
    path(
        "bronze/<int:pk>/delete/",
        views.BronzeDeleteView.as_view(),
        name="bronze-delete",
    ),
    path(
        "bronzedownload/", downloads.bronze_download_view, name="bronze-download"
    ),
    path(
        "bronzemetadownload/",
        downloads.bronze_meta_download_view,
        name="bronze-metadownload",
    ),
    # Iron
    path("iron/create/", views.IronCreateView.as_view(), name="iron-create"),
    path("irons/", views.IronListView.as_view(), name="irons"),
    path("irons_all/", views.IronListAllView.as_view(), name="irons_all"),
    path("iron/<int:pk>", views.IronDetailView.as_view(), name="iron-detail"),
    path(
        "iron/<int:pk>/update/",
        views.IronUpdateView.as_view(),
        name="iron-update",
    ),
    path(
        "iron/<int:pk>/delete/",
        views.IronDeleteView.as_view(),
        name="iron-delete",
    ),
    path("irondownload/", downloads.iron_download_view, name="iron-download"),
    path(
        "ironmetadownload/",
        downloads.iron_meta_download_view,
        name="iron-metadownload",
    ),
    # Steel
    path(
        "steel/create/", views.SteelCreateView.as_view(), name="steel-create"
    ),
    path("steels/", views.SteelListView.as_view(), name="steels"),
    path("steels_all/", views.SteelListAllView.as_view(), name="steels_all"),
    path(
        "steel/<int:pk>", views.SteelDetailView.as_view(), name="steel-detail"
    ),
    path(
        "steel/<int:pk>/update/",
        views.SteelUpdateView.as_view(),
        name="steel-update",
    ),
    path(
        "steel/<int:pk>/delete/",
        views.SteelDeleteView.as_view(),
        name="steel-delete",
    ),
    path("steeldownload/", downloads.steel_download_view, name="steel-download"),
    path(
        "steelmetadownload/",
        downloads.steel_meta_download_view,
        name="steel-metadownload",
    ),
    # Javelin
    path(
        "javelin/create/",
        views.JavelinCreateView.as_view(),
        name="javelin-create",
    ),
    path("javelins/", views.JavelinListView.as_view(), name="javelins"),
    path(
        "javelins_all/",
        views.JavelinListAllView.as_view(),
        name="javelins_all",
    ),
    path(
        "javelin/<int:pk>",
        views.JavelinDetailView.as_view(),
        name="javelin-detail",
    ),
    path(
        "javelin/<int:pk>/update/",
        views.JavelinUpdateView.as_view(),
        name="javelin-update",
    ),
    path(
        "javelin/<int:pk>/delete/",
        views.JavelinDeleteView.as_view(),
        name="javelin-delete",
    ),
    path(
        "javelindownload/",
        downloads.javelin_download_view,
        name="javelin-download",
    ),
    path(
        "javelinmetadownload/",
        downloads.javelin_meta_download_view,
        name="javelin-metadownload",
    ),
    # Atlatl
    path(
        "atlatl/create/",
        views.AtlatlCreateView.as_view(),
        name="atlatl-create",
    ),
    path("atlatls/", views.AtlatlListView.as_view(), name="atlatls"),
    path(
        "atlatls_all/", views.AtlatlListAllView.as_view(), name="atlatls_all"
    ),
    path(
        "atlatl/<int:pk>",
        views.AtlatlDetailView.as_view(),
        name="atlatl-detail",
    ),
    path(
        "atlatl/<int:pk>/update/",
        views.AtlatlUpdateView.as_view(),
        name="atlatl-update",
    ),
    path(
        "atlatl/<int:pk>/delete/",
        views.AtlatlDeleteView.as_view(),
        name="atlatl-delete",
    ),
    path(
        "atlatldownload/", downloads.atlatl_download_view, name="atlatl-download"
    ),
    path(
        "atlatlmetadownload/",
        downloads.atlatl_meta_download_view,
        name="atlatl-metadownload",
    ),
    # Sling
    path(
        "sling/create/", views.SlingCreateView.as_view(), name="sling-create"
    ),
    path("slings/", views.SlingListView.as_view(), name="slings"),
    path("slings_all/", views.SlingListAllView.as_view(), name="slings_all"),
    path(
        "sling/<int:pk>", views.SlingDetailView.as_view(), name="sling-detail"
    ),
    path(
        "sling/<int:pk>/update/",
        views.SlingUpdateView.as_view(),
        name="sling-update",
    ),
    path(
        "sling/<int:pk>/delete/",
        views.SlingDeleteView.as_view(),
        name="sling-delete",
    ),
    path("slingdownload/", downloads.sling_download_view, name="sling-download"),
    path(
        "slingmetadownload/",
        downloads.sling_meta_download_view,
        name="sling-metadownload",
    ),
    # Self bow
    path(
        "self_bow/create/",
        views.Self_bowCreateView.as_view(),
        name="self_bow-create",
    ),
    path("self_bows/", views.Self_bowListView.as_view(), name="self_bows"),
    path(
        "self_bows_all/",
        views.Self_bowListAllView.as_view(),
        name="self_bows_all",
    ),
    path(
        "self_bow/<int:pk>",
        views.Self_bowDetailView.as_view(),
        name="self_bow-detail",
    ),
    path(
        "self_bow/<int:pk>/update/",
        views.Self_bowUpdateView.as_view(),
        name="self_bow-update",
    ),
    path(
        "self_bow/<int:pk>/delete/",
        views.Self_bowDeleteView.as_view(),
        name="self_bow-delete",
    ),
    path(
        "self_bowdownload/",
        downloads.self_bow_download_view,
        name="self_bow-download",
    ),
    path(
        "self_bowmetadownload/",
        downloads.self_bow_meta_download_view,
        name="self_bow-metadownload",
    ),
    # Composite bow
    path(
        "composite_bow/create/",
        views.Composite_bowCreateView.as_view(),
        name="composite_bow-create",
    ),
    path(
        "composite_bows/",
        views.Composite_bowListView.as_view(),
        name="composite_bows",
    ),
    path(
        "composite_bows_all/",
        views.Composite_bowListAllView.as_view(),
        name="composite_bows_all",
    ),
    path(
        "composite_bow/<int:pk>",
        views.Composite_bowDetailView.as_view(),
        name="composite_bow-detail",
    ),
    path(
        "composite_bow/<int:pk>/update/",
        views.Composite_bowUpdateView.as_view(),
        name="composite_bow-update",
    ),
    path(
        "composite_bow/<int:pk>/delete/",
        views.Composite_bowDeleteView.as_view(),
        name="composite_bow-delete",
    ),
    path(
        "composite_bowdownload/",
        downloads.composite_bow_download_view,
        name="composite_bow-download",
    ),
    path(
        "composite_bowmetadownload/",
        downloads.composite_bow_meta_download_view,
        name="composite_bow-metadownload",
    ),
    # Crossbow
    path(
        "crossbow/create/",
        views.CrossbowCreateView.as_view(),
        name="crossbow-create",
    ),
    path("crossbows/", views.CrossbowListView.as_view(), name="crossbows"),
    path(
        "crossbows_all/",
        views.CrossbowListAllView.as_view(),
        name="crossbows_all",
    ),
    path(
        "crossbow/<int:pk>",
        views.CrossbowDetailView.as_view(),
        name="crossbow-detail",
    ),
    path(
        "crossbow/<int:pk>/update/",
        views.CrossbowUpdateView.as_view(),
        name="crossbow-update",
    ),
    path(
        "crossbow/<int:pk>/delete/",
        views.CrossbowDeleteView.as_view(),
        name="crossbow-delete",
    ),
    path(
        "crossbowdownload/",
        downloads.crossbow_download_view,
        name="crossbow-download",
    ),
    path(
        "crossbowmetadownload/",
        downloads.crossbow_meta_download_view,
        name="crossbow-metadownload",
    ),
    # Sieges
    path(
        "tension_siege_engine/create/",
        views.Tension_siege_engineCreateView.as_view(),
        name="tension_siege_engine-create",
    ),
    path(
        "tension_siege_engines/",
        views.Tension_siege_engineListView.as_view(),
        name="tension_siege_engines",
    ),
    path(
        "tension_siege_engines_all/",
        views.Tension_siege_engineListAllView.as_view(),
        name="tension_siege_engines_all",
    ),
    path(
        "tension_siege_engine/<int:pk>",
        views.Tension_siege_engineDetailView.as_view(),
        name="tension_siege_engine-detail",
    ),
    path(
        "tension_siege_engine/<int:pk>/update/",
        views.Tension_siege_engineUpdateView.as_view(),
        name="tension_siege_engine-update",
    ),
    path(
        "tension_siege_engine/<int:pk>/delete/",
        views.Tension_siege_engineDeleteView.as_view(),
        name="tension_siege_engine-delete",
    ),
    path(
        "tension_siege_enginedownload/",
        downloads.tension_siege_engine_download_view,
        name="tension_siege_engine-download",
    ),
    path(
        "tension_siege_enginemetadownload/",
        downloads.tension_siege_engine_meta_download_view,
        name="tension_siege_engine-metadownload",
    ),
    path(
        "sling_siege_engine/create/",
        views.Sling_siege_engineCreateView.as_view(),
        name="sling_siege_engine-create",
    ),
    path(
        "sling_siege_engines/",
        views.Sling_siege_engineListView.as_view(),
        name="sling_siege_engines",
    ),
    path(
        "sling_siege_engines_all/",
        views.Sling_siege_engineListAllView.as_view(),
        name="sling_siege_engines_all",
    ),
    path(
        "sling_siege_engine/<int:pk>",
        views.Sling_siege_engineDetailView.as_view(),
        name="sling_siege_engine-detail",
    ),
    path(
        "sling_siege_engine/<int:pk>/update/",
        views.Sling_siege_engineUpdateView.as_view(),
        name="sling_siege_engine-update",
    ),
    path(
        "sling_siege_engine/<int:pk>/delete/",
        views.Sling_siege_engineDeleteView.as_view(),
        name="sling_siege_engine-delete",
    ),
    path(
        "sling_siege_enginedownload/",
        downloads.sling_siege_engine_download_view,
        name="sling_siege_engine-download",
    ),
    path(
        "sling_siege_enginemetadownload/",
        downloads.sling_siege_engine_meta_download_view,
        name="sling_siege_engine-metadownload",
    ),
    path(
        "gunpowder_siege_artillery/create/",
        views.Gunpowder_siege_artilleryCreateView.as_view(),
        name="gunpowder_siege_artillery-create",
    ),
    path(
        "gunpowder_siege_artillerys/",
        views.Gunpowder_siege_artilleryListView.as_view(),
        name="gunpowder_siege_artillerys",
    ),
    path(
        "gunpowder_siege_artillerys_all/",
        views.Gunpowder_siege_artilleryListAllView.as_view(),
        name="gunpowder_siege_artillerys_all",
    ),
    path(
        "gunpowder_siege_artillery/<int:pk>",
        views.Gunpowder_siege_artilleryDetailView.as_view(),
        name="gunpowder_siege_artillery-detail",
    ),
    path(
        "gunpowder_siege_artillery/<int:pk>/update/",
        views.Gunpowder_siege_artilleryUpdateView.as_view(),
        name="gunpowder_siege_artillery-update",
    ),
    path(
        "gunpowder_siege_artillery/<int:pk>/delete/",
        views.Gunpowder_siege_artilleryDeleteView.as_view(),
        name="gunpowder_siege_artillery-delete",
    ),
    path(
        "gunpowder_siege_artillerydownload/",
        downloads.gunpowder_siege_artillery_download_view,
        name="gunpowder_siege_artillery-download",
    ),
    path(
        "gunpowder_siege_artillerymetadownload/",
        downloads.gunpowder_siege_artillery_meta_download_view,
        name="gunpowder_siege_artillery-metadownload",
    ),
    # Handheld firearm
    path(
        "handheld_firearm/create/",
        views.Handheld_firearmCreateView.as_view(),
        name="handheld_firearm-create",
    ),
    path(
        "handheld_firearms/",
        views.Handheld_firearmListView.as_view(),
        name="handheld_firearms",
    ),
    path(
        "handheld_firearms_all/",
        views.Handheld_firearmListAllView.as_view(),
        name="handheld_firearms_all",
    ),
    path(
        "handheld_firearm/<int:pk>",
        views.Handheld_firearmDetailView.as_view(),
        name="handheld_firearm-detail",
    ),
    path(
        "handheld_firearm/<int:pk>/update/",
        views.Handheld_firearmUpdateView.as_view(),
        name="handheld_firearm-update",
    ),
    path(
        "handheld_firearm/<int:pk>/delete/",
        views.Handheld_firearmDeleteView.as_view(),
        name="handheld_firearm-delete",
    ),
    path(
        "handheld_firearmdownload/",
        downloads.handheld_firearm_download_view,
        name="handheld_firearm-download",
    ),
    path(
        "handheld_firearmmetadownload/",
        downloads.handheld_firearm_meta_download_view,
        name="handheld_firearm-metadownload",
    ),
    # Warclub
    path(
        "war_club/create/",
        views.War_clubCreateView.as_view(),
        name="war_club-create",
    ),
    path("war_clubs/", views.War_clubListView.as_view(), name="war_clubs"),
    path(
        "war_clubs_all/",
        views.War_clubListAllView.as_view(),
        name="war_clubs_all",
    ),
    path(
        "war_club/<int:pk>",
        views.War_clubDetailView.as_view(),
        name="war_club-detail",
    ),
    path(
        "war_club/<int:pk>/update/",
        views.War_clubUpdateView.as_view(),
        name="war_club-update",
    ),
    path(
        "war_club/<int:pk>/delete/",
        views.War_clubDeleteView.as_view(),
        name="war_club-delete",
    ),
    path(
        "war_clubdownload/",
        downloads.war_club_download_view,
        name="war_club-download",
    ),
    path(
        "war_clubmetadownload/",
        downloads.war_club_meta_download_view,
        name="war_club-metadownload",
    ),
    # Battle axe
    path(
        "battle_axe/create/",
        views.Battle_axeCreateView.as_view(),
        name="battle_axe-create",
    ),
    path(
        "battle_axes/", views.Battle_axeListView.as_view(), name="battle_axes"
    ),
    path(
        "battle_axes_all/",
        views.Battle_axeListAllView.as_view(),
        name="battle_axes_all",
    ),
    path(
        "battle_axe/<int:pk>",
        views.Battle_axeDetailView.as_view(),
        name="battle_axe-detail",
    ),
    path(
        "battle_axe/<int:pk>/update/",
        views.Battle_axeUpdateView.as_view(),
        name="battle_axe-update",
    ),
    path(
        "battle_axe/<int:pk>/delete/",
        views.Battle_axeDeleteView.as_view(),
        name="battle_axe-delete",
    ),
    path(
        "battle_axedownload/",
        downloads.battle_axe_download_view,
        name="battle_axe-download",
    ),
    path(
        "battle_axemetadownload/",
        downloads.battle_axe_meta_download_view,
        name="battle_axe-metadownload",
    ),
    # Dagger
    path(
        "dagger/create/",
        views.DaggerCreateView.as_view(),
        name="dagger-create",
    ),
    path("daggers/", views.DaggerListView.as_view(), name="daggers"),
    path(
        "daggers_all/", views.DaggerListAllView.as_view(), name="daggers_all"
    ),
    path(
        "dagger/<int:pk>",
        views.DaggerDetailView.as_view(),
        name="dagger-detail",
    ),
    path(
        "dagger/<int:pk>/update/",
        views.DaggerUpdateView.as_view(),
        name="dagger-update",
    ),
    path(
        "dagger/<int:pk>/delete/",
        views.DaggerDeleteView.as_view(),
        name="dagger-delete",
    ),
    path(
        "daggerdownload/", downloads.dagger_download_view, name="dagger-download"
    ),
    path(
        "daggermetadownload/",
        downloads.dagger_meta_download_view,
        name="dagger-metadownload",
    ),
    # Sword
    path(
        "sword/create/", views.SwordCreateView.as_view(), name="sword-create"
    ),
    path("swords/", views.SwordListView.as_view(), name="swords"),
    path("swords_all/", views.SwordListAllView.as_view(), name="swords_all"),
    path(
        "sword/<int:pk>", views.SwordDetailView.as_view(), name="sword-detail"
    ),
    path(
        "sword/<int:pk>/update/",
        views.SwordUpdateView.as_view(),
        name="sword-update",
    ),
    path(
        "sword/<int:pk>/delete/",
        views.SwordDeleteView.as_view(),
        name="sword-delete",
    ),
    path("sworddownload/", downloads.sword_download_view, name="sword-download"),
    path(
        "swordmetadownload/",
        downloads.sword_meta_download_view,
        name="sword-metadownload",
    ),
    # Spear
    path(
        "spear/create/", views.SpearCreateView.as_view(), name="spear-create"
    ),
    path("spears/", views.SpearListView.as_view(), name="spears"),
    path("spears_all/", views.SpearListAllView.as_view(), name="spears_all"),
    path(
        "spear/<int:pk>", views.SpearDetailView.as_view(), name="spear-detail"
    ),
    path(
        "spear/<int:pk>/update/",
        views.SpearUpdateView.as_view(),
        name="spear-update",
    ),
    path(
        "spear/<int:pk>/delete/",
        views.SpearDeleteView.as_view(),
        name="spear-delete",
    ),
    path("speardownload/", downloads.spear_download_view, name="spear-download"),
    path(
        "spearmetadownload/",
        downloads.spear_meta_download_view,
        name="spear-metadownload",
    ),
    # Polearm
    path(
        "polearm/create/",
        views.PolearmCreateView.as_view(),
        name="polearm-create",
    ),
    path("polearms/", views.PolearmListView.as_view(), name="polearms"),
    path(
        "polearms_all/",
        views.PolearmListAllView.as_view(),
        name="polearms_all",
    ),
    path(
        "polearm/<int:pk>",
        views.PolearmDetailView.as_view(),
        name="polearm-detail",
    ),
    path(
        "polearm/<int:pk>/update/",
        views.PolearmUpdateView.as_view(),
        name="polearm-update",
    ),
    path(
        "polearm/<int:pk>/delete/",
        views.PolearmDeleteView.as_view(),
        name="polearm-delete",
    ),
    path(
        "polearmdownload/",
        downloads.polearm_download_view,
        name="polearm-download",
    ),
    path(
        "polearmmetadownload/",
        downloads.polearm_meta_download_view,
        name="polearm-metadownload",
    ),
    # Dog
    path("dog/create/", views.DogCreateView.as_view(), name="dog-create"),
    path("dogs/", views.DogListView.as_view(), name="dogs"),
    path("dogs_all/", views.DogListAllView.as_view(), name="dogs_all"),
    path("dog/<int:pk>", views.DogDetailView.as_view(), name="dog-detail"),
    path(
        "dog/<int:pk>/update/",
        views.DogUpdateView.as_view(),
        name="dog-update",
    ),
    path(
        "dog/<int:pk>/delete/",
        views.DogDeleteView.as_view(),
        name="dog-delete",
    ),
    path("dogdownload/", downloads.dog_download_view, name="dog-download"),
    path(
        "dogmetadownload/",
        downloads.dog_meta_download_view,
        name="dog-metadownload",
    ),
    # Donkey
    path(
        "donkey/create/",
        views.DonkeyCreateView.as_view(),
        name="donkey-create",
    ),
    path("donkeys/", views.DonkeyListView.as_view(), name="donkeys"),
    path(
        "donkeys_all/", views.DonkeyListAllView.as_view(), name="donkeys_all"
    ),
    path(
        "donkey/<int:pk>",
        views.DonkeyDetailView.as_view(),
        name="donkey-detail",
    ),
    path(
        "donkey/<int:pk>/update/",
        views.DonkeyUpdateView.as_view(),
        name="donkey-update",
    ),
    path(
        "donkey/<int:pk>/delete/",
        views.DonkeyDeleteView.as_view(),
        name="donkey-delete",
    ),
    path(
        "donkeydownload/", downloads.donkey_download_view, name="donkey-download"
    ),
    path(
        "donkeymetadownload/",
        downloads.donkey_meta_download_view,
        name="donkey-metadownload",
    ),
    # Horse
    path(
        "horse/create/", views.HorseCreateView.as_view(), name="horse-create"
    ),
    path("horses/", views.HorseListView.as_view(), name="horses"),
    path("horses_all/", views.HorseListAllView.as_view(), name="horses_all"),
    path(
        "horse/<int:pk>", views.HorseDetailView.as_view(), name="horse-detail"
    ),
    path(
        "horse/<int:pk>/update/",
        views.HorseUpdateView.as_view(),
        name="horse-update",
    ),
    path(
        "horse/<int:pk>/delete/",
        views.HorseDeleteView.as_view(),
        name="horse-delete",
    ),
    path("horsedownload/", downloads.horse_download_view, name="horse-download"),
    path(
        "horsemetadownload/",
        downloads.horse_meta_download_view,
        name="horse-metadownload",
    ),
    # Camel
    path(
        "camel/create/", views.CamelCreateView.as_view(), name="camel-create"
    ),
    path("camels/", views.CamelListView.as_view(), name="camels"),
    path("camels_all/", views.CamelListAllView.as_view(), name="camels_all"),
    path(
        "camel/<int:pk>", views.CamelDetailView.as_view(), name="camel-detail"
    ),
    path(
        "camel/<int:pk>/update/",
        views.CamelUpdateView.as_view(),
        name="camel-update",
    ),
    path(
        "camel/<int:pk>/delete/",
        views.CamelDeleteView.as_view(),
        name="camel-delete",
    ),
    path("cameldownload/", downloads.camel_download_view, name="camel-download"),
    path(
        "camelmetadownload/",
        downloads.camel_meta_download_view,
        name="camel-metadownload",
    ),
    # Elephant
    path(
        "elephant/create/",
        views.ElephantCreateView.as_view(),
        name="elephant-create",
    ),
    path("elephants/", views.ElephantListView.as_view(), name="elephants"),
    path(
        "elephants_all/",
        views.ElephantListAllView.as_view(),
        name="elephants_all",
    ),
    path(
        "elephant/<int:pk>",
        views.ElephantDetailView.as_view(),
        name="elephant-detail",
    ),
    path(
        "elephant/<int:pk>/update/",
        views.ElephantUpdateView.as_view(),
        name="elephant-update",
    ),
    path(
        "elephant/<int:pk>/delete/",
        views.ElephantDeleteView.as_view(),
        name="elephant-delete",
    ),
    path(
        "elephantdownload/",
        downloads.elephant_download_view,
        name="elephant-download",
    ),
    path(
        "elephantmetadownload/",
        downloads.elephant_meta_download_view,
        name="elephant-metadownload",
    ),
    # Wood, bark
    path(
        "wood_bark_etc/create/",
        views.Wood_bark_etcCreateView.as_view(),
        name="wood_bark_etc-create",
    ),
    path(
        "wood_bark_etcs/",
        views.Wood_bark_etcListView.as_view(),
        name="wood_bark_etcs",
    ),
    path(
        "wood_bark_etcs_all/",
        views.Wood_bark_etcListAllView.as_view(),
        name="wood_bark_etcs_all",
    ),
    path(
        "wood_bark_etc/<int:pk>",
        views.Wood_bark_etcDetailView.as_view(),
        name="wood_bark_etc-detail",
    ),
    path(
        "wood_bark_etc/<int:pk>/update/",
        views.Wood_bark_etcUpdateView.as_view(),
        name="wood_bark_etc-update",
    ),
    path(
        "wood_bark_etc/<int:pk>/delete/",
        views.Wood_bark_etcDeleteView.as_view(),
        name="wood_bark_etc-delete",
    ),
    path(
        "wood_bark_etcdownload/",
        downloads.wood_bark_etc_download_view,
        name="wood_bark_etc-download",
    ),
    path(
        "wood_bark_etcmetadownload/",
        downloads.wood_bark_etc_meta_download_view,
        name="wood_bark_etc-metadownload",
    ),
    # Leather
    path(
        "leather_cloth/create/",
        views.Leather_clothCreateView.as_view(),
        name="leather_cloth-create",
    ),
    path(
        "leather_cloths/",
        views.Leather_clothListView.as_view(),
        name="leather_cloths",
    ),
    path(
        "leather_cloths_all/",
        views.Leather_clothListAllView.as_view(),
        name="leather_cloths_all",
    ),
    path(
        "leather_cloth/<int:pk>",
        views.Leather_clothDetailView.as_view(),
        name="leather_cloth-detail",
    ),
    path(
        "leather_cloth/<int:pk>/update/",
        views.Leather_clothUpdateView.as_view(),
        name="leather_cloth-update",
    ),
    path(
        "leather_cloth/<int:pk>/delete/",
        views.Leather_clothDeleteView.as_view(),
        name="leather_cloth-delete",
    ),
    path(
        "leather_clothdownload/",
        downloads.leather_cloth_download_view,
        name="leather_cloth-download",
    ),
    path(
        "leather_clothmetadownload/",
        downloads.leather_cloth_meta_download_view,
        name="leather_cloth-metadownload",
    ),
    # Shield
    path(
        "shield/create/",
        views.ShieldCreateView.as_view(),
        name="shield-create",
    ),
    path("shields/", views.ShieldListView.as_view(), name="shields"),
    path(
        "shields_all/", views.ShieldListAllView.as_view(), name="shields_all"
    ),
    path(
        "shield/<int:pk>",
        views.ShieldDetailView.as_view(),
        name="shield-detail",
    ),
    path(
        "shield/<int:pk>/update/",
        views.ShieldUpdateView.as_view(),
        name="shield-update",
    ),
    path(
        "shield/<int:pk>/delete/",
        views.ShieldDeleteView.as_view(),
        name="shield-delete",
    ),
    path(
        "shielddownload/", downloads.shield_download_view, name="shield-download"
    ),
    path(
        "shieldmetadownload/",
        downloads.shield_meta_download_view,
        name="shield-metadownload",
    ),
    # Helmet
    path(
        "helmet/create/",
        views.HelmetCreateView.as_view(),
        name="helmet-create",
    ),
    path("helmets/", views.HelmetListView.as_view(), name="helmets"),
    path(
        "helmets_all/", views.HelmetListAllView.as_view(), name="helmets_all"
    ),
    path(
        "helmet/<int:pk>",
        views.HelmetDetailView.as_view(),
        name="helmet-detail",
    ),
    path(
        "helmet/<int:pk>/update/",
        views.HelmetUpdateView.as_view(),
        name="helmet-update",
    ),
    path(
        "helmet/<int:pk>/delete/",
        views.HelmetDeleteView.as_view(),
        name="helmet-delete",
    ),
    path(
        "helmetdownload/", downloads.helmet_download_view, name="helmet-download"
    ),
    path(
        "helmetmetadownload/",
        downloads.helmet_meta_download_view,
        name="helmet-metadownload",
    ),
    # Breastplate
    path(
        "breastplate/create/",
        views.BreastplateCreateView.as_view(),
        name="breastplate-create",
    ),
    path(
        "breastplates/",
        views.BreastplateListView.as_view(),
        name="breastplates",
    ),
    path(
        "breastplates_all/",
        views.BreastplateListAllView.as_view(),
        name="breastplates_all",
    ),
    path(
        "breastplate/<int:pk>",
        views.BreastplateDetailView.as_view(),
        name="breastplate-detail",
    ),
    path(
        "breastplate/<int:pk>/update/",
        views.BreastplateUpdateView.as_view(),
        name="breastplate-update",
    ),
    path(
        "breastplate/<int:pk>/delete/",
        views.BreastplateDeleteView.as_view(),
        name="breastplate-delete",
    ),
    path(
        "breastplatedownload/",
        downloads.breastplate_download_view,
        name="breastplate-download",
    ),
    path(
        "breastplatemetadownload/",
        downloads.breastplate_meta_download_view,
        name="breastplate-metadownload",
    ),
    # Limb protection
    path(
        "limb_protection/create/",
        views.Limb_protectionCreateView.as_view(),
        name="limb_protection-create",
    ),
    path(
        "limb_protections/",
        views.Limb_protectionListView.as_view(),
        name="limb_protections",
    ),
    path(
        "limb_protections_all/",
        views.Limb_protectionListAllView.as_view(),
        name="limb_protections_all",
    ),
    path(
        "limb_protection/<int:pk>",
        views.Limb_protectionDetailView.as_view(),
        name="limb_protection-detail",
    ),
    path(
        "limb_protection/<int:pk>/update/",
        views.Limb_protectionUpdateView.as_view(),
        name="limb_protection-update",
    ),
    path(
        "limb_protection/<int:pk>/delete/",
        views.Limb_protectionDeleteView.as_view(),
        name="limb_protection-delete",
    ),
    path(
        "limb_protectiondownload/",
        downloads.limb_protection_download_view,
        name="limb_protection-download",
    ),
    path(
        "limb_protectionmetadownload/",
        downloads.limb_protection_meta_download_view,
        name="limb_protection-metadownload",
    ),
    # Armors
    path(
        "scaled_armor/create/",
        views.Scaled_armorCreateView.as_view(),
        name="scaled_armor-create",
    ),
    path(
        "scaled_armors/",
        views.Scaled_armorListView.as_view(),
        name="scaled_armors",
    ),
    path(
        "scaled_armors_all/",
        views.Scaled_armorListAllView.as_view(),
        name="scaled_armors_all",
    ),
    path(
        "scaled_armor/<int:pk>",
        views.Scaled_armorDetailView.as_view(),
        name="scaled_armor-detail",
    ),
    path(
        "scaled_armor/<int:pk>/update/",
        views.Scaled_armorUpdateView.as_view(),
        name="scaled_armor-update",
    ),
    path(
        "scaled_armor/<int:pk>/delete/",
        views.Scaled_armorDeleteView.as_view(),
        name="scaled_armor-delete",
    ),
    path(
        "scaled_armordownload/",
        downloads.scaled_armor_download_view,
        name="scaled_armor-download",
    ),
    path(
        "scaled_armormetadownload/",
        downloads.scaled_armor_meta_download_view,
        name="scaled_armor-metadownload",
    ),
    path(
        "laminar_armor/create/",
        views.Laminar_armorCreateView.as_view(),
        name="laminar_armor-create",
    ),
    path(
        "laminar_armors/",
        views.Laminar_armorListView.as_view(),
        name="laminar_armors",
    ),
    path(
        "laminar_armors_all/",
        views.Laminar_armorListAllView.as_view(),
        name="laminar_armors_all",
    ),
    path(
        "laminar_armor/<int:pk>",
        views.Laminar_armorDetailView.as_view(),
        name="laminar_armor-detail",
    ),
    path(
        "laminar_armor/<int:pk>/update/",
        views.Laminar_armorUpdateView.as_view(),
        name="laminar_armor-update",
    ),
    path(
        "laminar_armor/<int:pk>/delete/",
        views.Laminar_armorDeleteView.as_view(),
        name="laminar_armor-delete",
    ),
    path(
        "laminar_armordownload/",
        downloads.laminar_armor_download_view,
        name="laminar_armor-download",
    ),
    path(
        "laminar_armormetadownload/",
        downloads.laminar_armor_meta_download_view,
        name="laminar_armor-metadownload",
    ),
    path(
        "plate_armor/create/",
        views.Plate_armorCreateView.as_view(),
        name="plate_armor-create",
    ),
    path(
        "plate_armors/",
        views.Plate_armorListView.as_view(),
        name="plate_armors",
    ),
    path(
        "plate_armors_all/",
        views.Plate_armorListAllView.as_view(),
        name="plate_armors_all",
    ),
    path(
        "plate_armor/<int:pk>",
        views.Plate_armorDetailView.as_view(),
        name="plate_armor-detail",
    ),
    path(
        "plate_armor/<int:pk>/update/",
        views.Plate_armorUpdateView.as_view(),
        name="plate_armor-update",
    ),
    path(
        "plate_armor/<int:pk>/delete/",
        views.Plate_armorDeleteView.as_view(),
        name="plate_armor-delete",
    ),
    path(
        "plate_armordownload/",
        downloads.plate_armor_download_view,
        name="plate_armor-download",
    ),
    path(
        "plate_armormetadownload/",
        downloads.plate_armor_meta_download_view,
        name="plate_armor-metadownload",
    ),
    # Small vessels
    path(
        "small_vessels_canoes_etc/create/",
        views.Small_vessels_canoes_etcCreateView.as_view(),
        name="small_vessels_canoes_etc-create",
    ),
    path(
        "small_vessels_canoes_etcs/",
        views.Small_vessels_canoes_etcListView.as_view(),
        name="small_vessels_canoes_etcs",
    ),
    path(
        "small_vessels_canoes_etcs_all/",
        views.Small_vessels_canoes_etcListAllView.as_view(),
        name="small_vessels_canoes_etcs_all",
    ),
    path(
        "small_vessels_canoes_etc/<int:pk>",
        views.Small_vessels_canoes_etcDetailView.as_view(),
        name="small_vessels_canoes_etc-detail",
    ),
    path(
        "small_vessels_canoes_etc/<int:pk>/update/",
        views.Small_vessels_canoes_etcUpdateView.as_view(),
        name="small_vessels_canoes_etc-update",
    ),
    path(
        "small_vessels_canoes_etc/<int:pk>/delete/",
        views.Small_vessels_canoes_etcDeleteView.as_view(),
        name="small_vessels_canoes_etc-delete",
    ),
    path(
        "small_vessels_canoes_etcdownload/",
        downloads.small_vessels_canoes_etc_download_view,
        name="small_vessels_canoes_etc-download",
    ),
    path(
        "small_vessels_canoes_etcmetadownload/",
        downloads.small_vessels_canoes_etc_meta_download_view,
        name="small_vessels_canoes_etc-metadownload",
    ),
    # Merchant ships
    path(
        "merchant_ships_pressed_into_service/create/",
        views.Merchant_ships_pressed_into_serviceCreateView.as_view(),
        name="merchant_ships_pressed_into_service-create",
    ),
    path(
        "merchant_ships_pressed_into_services/",
        views.Merchant_ships_pressed_into_serviceListView.as_view(),
        name="merchant_ships_pressed_into_services",
    ),
    path(
        "merchant_ships_pressed_into_services_all/",
        views.Merchant_ships_pressed_into_serviceListAllView.as_view(),
        name="merchant_ships_pressed_into_services_all",
    ),
    path(
        "merchant_ships_pressed_into_service/<int:pk>",
        views.Merchant_ships_pressed_into_serviceDetailView.as_view(),
        name="merchant_ships_pressed_into_service-detail",
    ),
    path(
        "merchant_ships_pressed_into_service/<int:pk>/update/",
        views.Merchant_ships_pressed_into_serviceUpdateView.as_view(),
        name="merchant_ships_pressed_into_service-update",
    ),
    path(
        "merchant_ships_pressed_into_service/<int:pk>/delete/",
        views.Merchant_ships_pressed_into_serviceDeleteView.as_view(),
        name="merchant_ships_pressed_into_service-delete",
    ),
    path(
        "merchant_ships_pressed_into_servicedownload/",
        downloads.merchant_ships_pressed_into_service_download_view,
        name="merchant_ships_pressed_into_service-download",
    ),
    path(
        "merchant_ships_pressed_into_servicemetadownload/",
        downloads.merchant_ships_pressed_into_service_meta_download_view,
        name="merchant_ships_pressed_into_service-metadownload",
    ),
    # Military vessel
    path(
        "specialized_military_vessel/create/",
        views.Specialized_military_vesselCreateView.as_view(),
        name="specialized_military_vessel-create",
    ),
    path(
        "specialized_military_vessels/",
        views.Specialized_military_vesselListView.as_view(),
        name="specialized_military_vessels",
    ),
    path(
        "specialized_military_vessels_all/",
        views.Specialized_military_vesselListAllView.as_view(),
        name="specialized_military_vessels_all",
    ),
    path(
        "specialized_military_vessel/<int:pk>",
        views.Specialized_military_vesselDetailView.as_view(),
        name="specialized_military_vessel-detail",
    ),
    path(
        "specialized_military_vessel/<int:pk>/update/",
        views.Specialized_military_vesselUpdateView.as_view(),
        name="specialized_military_vessel-update",
    ),
    path(
        "specialized_military_vessel/<int:pk>/delete/",
        views.Specialized_military_vesselDeleteView.as_view(),
        name="specialized_military_vessel-delete",
    ),
    path(
        "specialized_military_vesseldownload/",
        downloads.specialized_military_vessel_download_view,
        name="specialized_military_vessel-download",
    ),
    path(
        "specialized_military_vesselmetadownload/",
        downloads.specialized_military_vessel_meta_download_view,
        name="specialized_military_vessel-metadownload",
    ),
    # Defensive settlements
    path(
        "settlements_in_a_defensive_position/create/",
        views.Settlements_in_a_defensive_positionCreateView.as_view(),
        name="settlements_in_a_defensive_position-create",
    ),
    path(
        "settlements_in_a_defensive_positions/",
        views.Settlements_in_a_defensive_positionListView.as_view(),
        name="settlements_in_a_defensive_positions",
    ),
    path(
        "settlements_in_a_defensive_positions_all/",
        views.Settlements_in_a_defensive_positionListAllView.as_view(),
        name="settlements_in_a_defensive_positions_all",
    ),
    path(
        "settlements_in_a_defensive_position/<int:pk>",
        views.Settlements_in_a_defensive_positionDetailView.as_view(),
        name="settlements_in_a_defensive_position-detail",
    ),
    path(
        "settlements_in_a_defensive_position/<int:pk>/update/",
        views.Settlements_in_a_defensive_positionUpdateView.as_view(),
        name="settlements_in_a_defensive_position-update",
    ),
    path(
        "settlements_in_a_defensive_position/<int:pk>/delete/",
        views.Settlements_in_a_defensive_positionDeleteView.as_view(),
        name="settlements_in_a_defensive_position-delete",
    ),
    path(
        "settlements_in_a_defensive_positiondownload/",
        downloads.settlements_in_a_defensive_position_download_view,
        name="settlements_in_a_defensive_position-download",
    ),
    path(
        "settlements_in_a_defensive_positionmetadownload/",
        downloads.settlements_in_a_defensive_position_meta_download_view,
        name="settlements_in_a_defensive_position-metadownload",
    ),
    # Wooden palisades
    path(
        "wooden_palisade/create/",
        views.Wooden_palisadeCreateView.as_view(),
        name="wooden_palisade-create",
    ),
    path(
        "wooden_palisades/",
        views.Wooden_palisadeListView.as_view(),
        name="wooden_palisades",
    ),
    path(
        "wooden_palisades_all/",
        views.Wooden_palisadeListAllView.as_view(),
        name="wooden_palisades_all",
    ),
    path(
        "wooden_palisade/<int:pk>",
        views.Wooden_palisadeDetailView.as_view(),
        name="wooden_palisade-detail",
    ),
    path(
        "wooden_palisade/<int:pk>/update/",
        views.Wooden_palisadeUpdateView.as_view(),
        name="wooden_palisade-update",
    ),
    path(
        "wooden_palisade/<int:pk>/delete/",
        views.Wooden_palisadeDeleteView.as_view(),
        name="wooden_palisade-delete",
    ),
    path(
        "wooden_palisadedownload/",
        downloads.wooden_palisade_download_view,
        name="wooden_palisade-download",
    ),
    path(
        "wooden_palisademetadownload/",
        downloads.wooden_palisade_meta_download_view,
        name="wooden_palisade-metadownload",
    ),
    # Earth rampart
    path(
        "earth_rampart/create/",
        views.Earth_rampartCreateView.as_view(),
        name="earth_rampart-create",
    ),
    path(
        "earth_ramparts/",
        views.Earth_rampartListView.as_view(),
        name="earth_ramparts",
    ),
    path(
        "earth_ramparts_all/",
        views.Earth_rampartListAllView.as_view(),
        name="earth_ramparts_all",
    ),
    path(
        "earth_rampart/<int:pk>",
        views.Earth_rampartDetailView.as_view(),
        name="earth_rampart-detail",
    ),
    path(
        "earth_rampart/<int:pk>/update/",
        views.Earth_rampartUpdateView.as_view(),
        name="earth_rampart-update",
    ),
    path(
        "earth_rampart/<int:pk>/delete/",
        views.Earth_rampartDeleteView.as_view(),
        name="earth_rampart-delete",
    ),
    path(
        "earth_rampartdownload/",
        downloads.earth_rampart_download_view,
        name="earth_rampart-download",
    ),
    path(
        "earth_rampartmetadownload/",
        downloads.earth_rampart_meta_download_view,
        name="earth_rampart-metadownload",
    ),
    # Ditch
    path(
        "ditch/create/", views.DitchCreateView.as_view(), name="ditch-create"
    ),
    path("ditchs/", views.DitchListView.as_view(), name="ditchs"),
    path("ditchs_all/", views.DitchListAllView.as_view(), name="ditchs_all"),
    path(
        "ditch/<int:pk>", views.DitchDetailView.as_view(), name="ditch-detail"
    ),
    path(
        "ditch/<int:pk>/update/",
        views.DitchUpdateView.as_view(),
        name="ditch-update",
    ),
    path(
        "ditch/<int:pk>/delete/",
        views.DitchDeleteView.as_view(),
        name="ditch-delete",
    ),
    path("ditchdownload/", downloads.ditch_download_view, name="ditch-download"),
    path(
        "ditchmetadownload/",
        downloads.ditch_meta_download_view,
        name="ditch-metadownload",
    ),
    # Moat
    path("moat/create/", views.MoatCreateView.as_view(), name="moat-create"),
    path("moats/", views.MoatListView.as_view(), name="moats"),
    path("moats_all/", views.MoatListAllView.as_view(), name="moats_all"),
    path("moat/<int:pk>", views.MoatDetailView.as_view(), name="moat-detail"),
    path(
        "moat/<int:pk>/update/",
        views.MoatUpdateView.as_view(),
        name="moat-update",
    ),
    path(
        "moat/<int:pk>/delete/",
        views.MoatDeleteView.as_view(),
        name="moat-delete",
    ),
    path("moatdownload/", downloads.moat_download_view, name="moat-download"),
    path(
        "moatmetadownload/",
        downloads.moat_meta_download_view,
        name="moat-metadownload",
    ),
    # Stone walls
    path(
        "stone_walls_non_mortared/create/",
        views.Stone_walls_non_mortaredCreateView.as_view(),
        name="stone_walls_non_mortared-create",
    ),
    path(
        "stone_walls_non_mortareds/",
        views.Stone_walls_non_mortaredListView.as_view(),
        name="stone_walls_non_mortareds",
    ),
    path(
        "stone_walls_non_mortareds_all/",
        views.Stone_walls_non_mortaredListAllView.as_view(),
        name="stone_walls_non_mortareds_all",
    ),
    path(
        "stone_walls_non_mortared/<int:pk>",
        views.Stone_walls_non_mortaredDetailView.as_view(),
        name="stone_walls_non_mortared-detail",
    ),
    path(
        "stone_walls_non_mortared/<int:pk>/update/",
        views.Stone_walls_non_mortaredUpdateView.as_view(),
        name="stone_walls_non_mortared-update",
    ),
    path(
        "stone_walls_non_mortared/<int:pk>/delete/",
        views.Stone_walls_non_mortaredDeleteView.as_view(),
        name="stone_walls_non_mortared-delete",
    ),
    path(
        "stone_walls_non_mortareddownload/",
        downloads.stone_walls_non_mortared_download_view,
        name="stone_walls_non_mortared-download",
    ),
    path(
        "stone_walls_non_mortaredmetadownload/",
        downloads.stone_walls_non_mortared_meta_download_view,
        name="stone_walls_non_mortared-metadownload",
    ),
    path(
        "stone_walls_mortared/create/",
        views.Stone_walls_mortaredCreateView.as_view(),
        name="stone_walls_mortared-create",
    ),
    path(
        "stone_walls_mortareds/",
        views.Stone_walls_mortaredListView.as_view(),
        name="stone_walls_mortareds",
    ),
    path(
        "stone_walls_mortareds_all/",
        views.Stone_walls_mortaredListAllView.as_view(),
        name="stone_walls_mortareds_all",
    ),
    path(
        "stone_walls_mortared/<int:pk>",
        views.Stone_walls_mortaredDetailView.as_view(),
        name="stone_walls_mortared-detail",
    ),
    path(
        "stone_walls_mortared/<int:pk>/update/",
        views.Stone_walls_mortaredUpdateView.as_view(),
        name="stone_walls_mortared-update",
    ),
    path(
        "stone_walls_mortared/<int:pk>/delete/",
        views.Stone_walls_mortaredDeleteView.as_view(),
        name="stone_walls_mortared-delete",
    ),
    path(
        "stone_walls_mortareddownload/",
        downloads.stone_walls_mortared_download_view,
        name="stone_walls_mortared-download",
    ),
    path(
        "stone_walls_mortaredmetadownload/",
        downloads.stone_walls_mortared_meta_download_view,
        name="stone_walls_mortared-metadownload",
    ),
    # Fortified camps
    path(
        "fortified_camp/create/",
        views.Fortified_campCreateView.as_view(),
        name="fortified_camp-create",
    ),
    path(
        "fortified_camps/",
        views.Fortified_campListView.as_view(),
        name="fortified_camps",
    ),
    path(
        "fortified_camps_all/",
        views.Fortified_campListAllView.as_view(),
        name="fortified_camps_all",
    ),
    path(
        "fortified_camp/<int:pk>",
        views.Fortified_campDetailView.as_view(),
        name="fortified_camp-detail",
    ),
    path(
        "fortified_camp/<int:pk>/update/",
        views.Fortified_campUpdateView.as_view(),
        name="fortified_camp-update",
    ),
    path(
        "fortified_camp/<int:pk>/delete/",
        views.Fortified_campDeleteView.as_view(),
        name="fortified_camp-delete",
    ),
    path(
        "fortified_campdownload/",
        downloads.fortified_camp_download_view,
        name="fortified_camp-download",
    ),
    path(
        "fortified_campmetadownload/",
        downloads.fortified_camp_meta_download_view,
        name="fortified_camp-metadownload",
    ),
    # Fortifications
    path(
        "complex_fortification/create/",
        views.Complex_fortificationCreateView.as_view(),
        name="complex_fortification-create",
    ),
    path(
        "complex_fortifications/",
        views.Complex_fortificationListView.as_view(),
        name="complex_fortifications",
    ),
    path(
        "complex_fortifications_all/",
        views.Complex_fortificationListAllView.as_view(),
        name="complex_fortifications_all",
    ),
    path(
        "complex_fortification/<int:pk>",
        views.Complex_fortificationDetailView.as_view(),
        name="complex_fortification-detail",
    ),
    path(
        "complex_fortification/<int:pk>/update/",
        views.Complex_fortificationUpdateView.as_view(),
        name="complex_fortification-update",
    ),
    path(
        "complex_fortification/<int:pk>/delete/",
        views.Complex_fortificationDeleteView.as_view(),
        name="complex_fortification-delete",
    ),
    path(
        "complex_fortificationdownload/",
        downloads.complex_fortification_download_view,
        name="complex_fortification-download",
    ),
    path(
        "complex_fortificationmetadownload/",
        downloads.complex_fortification_meta_download_view,
        name="complex_fortification-metadownload",
    ),
    path(
        "modern_fortification/create/",
        views.Modern_fortificationCreateView.as_view(),
        name="modern_fortification-create",
    ),
    path(
        "modern_fortifications/",
        views.Modern_fortificationListView.as_view(),
        name="modern_fortifications",
    ),
    path(
        "modern_fortifications_all/",
        views.Modern_fortificationListAllView.as_view(),
        name="modern_fortifications_all",
    ),
    path(
        "modern_fortification/<int:pk>",
        views.Modern_fortificationDetailView.as_view(),
        name="modern_fortification-detail",
    ),
    path(
        "modern_fortification/<int:pk>/update/",
        views.Modern_fortificationUpdateView.as_view(),
        name="modern_fortification-update",
    ),
    path(
        "modern_fortification/<int:pk>/delete/",
        views.Modern_fortificationDeleteView.as_view(),
        name="modern_fortification-delete",
    ),
    path(
        "modern_fortificationdownload/",
        downloads.modern_fortification_download_view,
        name="modern_fortification-download",
    ),
    path(
        "modern_fortificationmetadownload/",
        downloads.modern_fortification_meta_download_view,
        name="modern_fortification-metadownload",
    ),
    # Chainmail
    path(
        "chainmail/create/",
        views.ChainmailCreateView.as_view(),
        name="chainmail-create",
    ),
    path("chainmails/", views.ChainmailListView.as_view(), name="chainmails"),
    path(
        "chainmails_all/",
        views.ChainmailListAllView.as_view(),
        name="chainmails_all",
    ),
    path(
        "chainmail/<int:pk>",
        views.ChainmailDetailView.as_view(),
        name="chainmail-detail",
    ),
    path(
        "chainmail/<int:pk>/update/",
        views.ChainmailUpdateView.as_view(),
        name="chainmail-update",
    ),
    path(
        "chainmail/<int:pk>/delete/",
        views.ChainmailDeleteView.as_view(),
        name="chainmail-delete",
    ),
    path(
        "chainmaildownload/",
        downloads.chainmail_download_view,
        name="chainmail-download",
    ),
    path(
        "chainmailmetadownload/",
        downloads.chainmail_meta_download_view,
        name="chainmail-metadownload",
    ),
]
