wf_var_defs = {
"ra": "The absence or presence of ra as a military technology used in warfare. The name of the research assistant or associate who coded the data.",
"copper": "The absence or presence of copper as a military technology used in warfare. ",
"bronze": "The absence or presence of bronze as a military technology used in warfare. Bronze is an alloy that includes copper, so a polity that uses bronze in warfare is familiar with copper technology and probably uses it to at least a limited extent. Consequently, if a culture uses bronze in warfare and there is no mention of using copper then 'inferred present' is probably best.",
"iron": "The absence or presence of iron as a military technology used in warfare. ",
"steel": "The absence or presence of steel as a military technology used in warfare. Steel is an alloy that includes iron, so a polity that uses bronze in warfare is familiar with copper technology and probably uses it to at least a limited extent. Consequently, if a culture uses steel in warfare and there is no mention of using iron then 'inferred present' is probably best.",
"javelin": "The absence or presence of javelins as a military technology used in warfare. Includes thrown spears",
"atlatl": "The absence or presence of atlatl as a military technology used in warfare. ",
"sling": "The absence or presence of slings as a military technology used in warfare. ",
"self_bow": "The absence or presence of self_bow as a military technology used in warfare. This is a bow made from a single piece of wood (example: the English/Welsh longbow)",
"composite_bow": "The absence or presence of composite_bow as a military technology used in warfare. This is a bow made from several different materials, usually wood, horn, and sinew. Also known as laminated bow. Recurved bows should be coded here as well, because usually they are composite bows. When there is evidence for bows (or arrows) and no specific comment about how sophisticated the bows are then 'inferred present' for self bows and 'inferred absent' for composite bows is generally best (along with brief notes indicating that it is best to assume the less sophisticated rather than the more sophisticated technology is present).",
"crossbow": "The absence or presence of crossbow as a military technology used in warfare. ",
"tension_siege_engine": "The absence or presence of tension_siege_engines as a military technology used in warfare. For example, catapult, onager",
"sling_siege_engine": "The absence or presence of sling_siege_engines as a military technology used in warfare. E.g., trebuchet, innclude mangonels here",
"gunpowder_siege_artillery": "The absence or presence of gunpowder_siege_artillery as a military technology used in warfare. For example, cannon, mortars.",
"handheld_firearm": "The absence or presence of handheld_firearms as a military technology used in warfare. E.g., muskets, pistols, and rifles",
"war_club": "The absence or presence of war_clubs as a military technology used in warfare. Includes maces",
"battle_axe": "The absence or presence of battle_axes as a military technology used in warfare. Axes designed for military use.",
"dagger": "The absence or presence of daggers as a military technology used in warfare. Bladed weapons shorter than 50 cm. Includes knives. Material is not important (coded elsewhere), thus flint daggers should be coded as present.",
"sword": "The absence or presence of swords as a military technology used in warfare. Bladed weapons longer than 50 cm. A machete is a sword (assuming the blade is probably longer than 50 cm). Material is not important (coded elsewhere), thus swords made from hard wood, or those edged with stones or bone should be coded as present.",
"spear": "The absence or presence of spears as a military technology used in warfare. Includes lances and pikes. A trident is a spear.",
"polearm": "The absence or presence of polearms as a military technology used in warfare. This category includes halberds, naginatas, and morning stars",
"dog": "The absence or presence of dogs as a military technology used in warfare. ",
"donkey": "The absence or presence of donkeys as a military technology used in warfare. ",
"horse": "The absence or presence of horses as a military technology used in warfare. ",
"camel": "The absence or presence of camels as a military technology used in warfare. ",
"elephant": "The absence or presence of elephants as a military technology used in warfare. ",
"wood_bark_etc": "The absence or presence of wood_bark_etc as a military technology used in warfare. ",
"leather_cloth": "The absence or presence of leather_cloth as a military technology used in warfare. For example, leather cuirass, quilted cotton armor",
"shield": "The absence or presence of shields as a military technology used in warfare. ",
"helmet": "The absence or presence of helmets as a military technology used in warfare. ",
"breastplate": "The absence or presence of breastplates as a military technology used in warfare. Armor made from wood, horn, or bone can be very important (as in the spread of the Asian War Complex into North America). Leather and cotton (in the Americas) armor was also effective against arrows and warclubs. Breastplate refers to any form of torso protection (in fact, we might rename this variable 'torso protection' at a later date). In the vast majority of cases you will probably find that if a culture has wooden armor, leather armor, chainmail armor, or scaled armor that breastplate should be coded as present because this is the most common location for armor. However, in theory, it is possible to have armor that doesn't protect the torso (for example, a culture might use armor that protects the limbs only).",
"limb_protection": "The absence or presence of limb_protection as a military technology used in warfare. E.g., greaves. Covering arms, or legs, or both.",
"scaled_armor": "The absence or presence of scaled_armor as a military technology used in warfare. Armor consisting of many individual small armor scales (plates) attached to a backing of cloth or leather. The scaled don't need to be metal (i.e. they could be particularly rigid bits of leather, horn, bone, etc).",
"laminar_armor": "The absence or presence of laminar_armor as a military technology used in warfare. (also known as banded mail, example: lorica segmentata). Armor that is made from horizontal overlapping rows or bands of sold armor plates.",
"plate_armor": "The absence or presence of plate_armor as a military technology used in warfare. Armor made of iron or steel plates.",
"small_vessels_canoes_etc": "The absence or presence of small_vessels_canoes_etc as a military technology used in warfare. ",
"merchant_ships_pressed_into_service": "The absence or presence of merchant_ships_pressed_into_service as a military technology used in warfare. ",
"specialized_military_vessel": "The absence or presence of specialized_military_vessels as a military technology used in warfare. (such as galleys and sailing ships)",
"settlements_in_a_defensive_position": "The absence or presence of settlements_in_a_defensive_position as a military technology used in warfare. Settlements in a location that was clearly chosen for defensive reasons. E.g. on a hill top, peninsula.",
"wooden_palisade": "The absence or presence of wooden_palisades as a military technology used in warfare. ",
"earth_rampart": "The absence or presence of earth_ramparts as a military technology used in warfare. ",
"ditch": "The absence or presence of ditch as a military technology used in warfare. ",
"moat": "The absence or presence of moat as a military technology used in warfare. Differs from a ditch in that it has water",
"stone_walls_non_mortared": "The absence or presence of stone_walls_non-mortared as a military technology used in warfare. ",
"stone_walls_mortared": "The absence or presence of stone_walls_mortared as a military technology used in warfare. ",
"fortified_camp": "The absence or presence of fortified_camps as a military technology used in warfare. Camps made by armies on the move (e.g. on a campaign) that which could be constructed on a hill top or in the middle of a plain or desert, usually out of local materials.",
"complex_fortification": "The absence or presence of complex_fortifications as a military technology used in warfare. When there are two or more concentric walls. So simply a wall and a donjon, for example, is not enough.",
"modern_fortification": "The absence or presence of modern_fortifications as a military technology used in warfare. used after the introduction of gunpowder, e.g., trace italienne/starfort.",
"chainmail": "The absence or presence of chainmail as a military technology used in warfare. We’re using a broad definition of chainmail. Habergeon was the word used to describe the Chinese version and that would qualify as chainmail. Armor that is made of small metal rings linked together in a pattern to form a mesh.",
'long_wall': "in km. These are fortifications that were used not to protect a specific city or town, but a large territory. Examples include the Great Wall of China. Provide an estimate in km of the extent of the longest of such fortification systems. If not present, enter '0'. Very large circular walls protecting a settlement are not long walls - long walls are fairly linear and protect whole areas from incursions. If a polity inherits a stone wall from a previous one and continues to use and repair it, then we should probably code it as present.",
}