# Generated by Django 4.0.3 on 2024-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_videoshapefile_cliopatria'),
        ('crisisdb', '0066_agricultural_population_private_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultural_population',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='arable_land',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land_per_farmer',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='arable_land_per_farmer',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crop_failure_event',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='crop_failure_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='disease_outbreak',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='disease_outbreak',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='drought_event',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='drought_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='external_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict_side',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='external_conflict_side',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='famine_event',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='famine_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_per_capita',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gdp_per_capita',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='internal_conflict',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='internal_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='locust_event',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='locust_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='military_expense',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='military_expense',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='net_grain_shared_per_agricultural_population',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='net_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='power_transition',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='power_transition',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_inflow',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='silver_inflow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_stock',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='silver_stock',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='socioeconomic_turmoil_event',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='socioeconomic_turmoil_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_population',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity'),
        ),
        migrations.AlterField(
            model_name='total_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5),
        ),
    ]
