# Generated by Django 4.0.3 on 2025-03-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_seshat_expert_role'),
        ('core', '0069_prec_met_instance'),
        ('crisisdb', '0068_alter_agricultural_population_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('check_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Instability_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_real', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instability_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instability_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('tag', models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], default='TRS', max_length=5)),
                ('is_disputed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_uncertain', models.BooleanField(blank=True, default=False, null=True)),
                ('expert_reviewed', models.BooleanField(blank=True, default=True, null=True)),
                ('drb_reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('inst_extent', models.CharField(blank=True, choices=[('1', 'Highly localized: a neighborhood within a town'), ('2', 'A small town or rural location'), ('4', 'One or few districts within a single province'), ('6', 'One or two provinces, or only the capital'), ('8', 'Several provinces, including the capital'), ('10', 'Whole polity')], max_length=5, null=True)),
                ('inst_intensity', models.CharField(blank=True, choices=[('0', 'Nobody is killed'), ('1', 'One or few individuals killed'), ('2', 'Tens killed'), ('3', 'Tens or Hundreds killed'), ('4', 'Hundreds killed'), ('5', 'Hundreds or Thousands killed'), ('6', 'Thousands killed'), ('7', 'Thousands or Tens of thousands killed'), ('8', 'Tens of thousands killed'), ('9', 'Tens of thousands or Hundreds of thousands killed'), ('10', 'Hundreds of thousands killed'), ('11', 'Hundreds of thousands or Millions killed'), ('12', 'Millions killed')], max_length=5, null=True)),
                ('general_cot', models.TextField(blank=True, null=True)),
                ('classification_cot', models.TextField(blank=True, null=True)),
                ('sorokin_rationale', models.TextField(blank=True, null=True)),
                ('real_event_check', models.CharField(blank=True, choices=[('Real', 'Real'), ('Uncertain', 'Uncertain')], max_length=20, null=True)),
                ('llm_description', models.CharField(blank=True, choices=[('Real', 'Real'), ('Uncertain', 'Uncertain')], max_length=20, null=True)),
                ('citations', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='core.citation')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatcomment')),
                ('curator', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert')),
                ('inst_llm_ref', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.instability_ref')),
                ('inst_type', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.instability_type')),
                ('polity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.polity')),
                ('private_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='core.seshatprivatecomment')),
                ('ra_check', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.check_choice')),
            ],
            options={
                'ordering': ['polity'],
                'abstract': False,
            },
        ),
    ]
