# Generated by Django 4.0.3 on 2025-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0069_check_choice_instability_ref_instability_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_event',
            name='llm_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
