# Generated by Django 4.0.3 on 2025-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0072_alter_check_choice_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_event',
            name='inst_extent',
            field=models.CharField(blank=True, choices=[('1', '1. Highly localized: a neighborhood within a town'), ('2', '2. A small town or rural location'), ('4', '4. One or few districts within a single province'), ('6', '6. One or two provinces, or only the capital'), ('8', '8. Several provinces, including the capital'), ('10', '10. Whole polity')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='instability_event',
            name='llm_inst_extent',
            field=models.CharField(blank=True, choices=[('1', '1. Highly localized: a neighborhood within a town'), ('2', '2. A small town or rural location'), ('4', '4. One or few districts within a single province'), ('6', '6. One or two provinces, or only the capital'), ('8', '8. Several provinces, including the capital'), ('10', '10. Whole polity')], max_length=5, null=True),
        ),
    ]
