# Generated by Django 4.0.3 on 2025-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0073_alter_instability_event_inst_extent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_event',
            name='llm_real_event_check',
            field=models.CharField(blank=True, choices=[('Real', 'Good'), ('Uncertain', 'Uncertain'), ('Duplicate', 'Duplicate'), ('Bad', 'Bad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instability_event',
            name='real_event_check',
            field=models.CharField(blank=True, choices=[('Real', 'Good'), ('Uncertain', 'Uncertain'), ('Duplicate', 'Duplicate'), ('Bad', 'Bad')], max_length=20, null=True),
        ),
    ]
