# Generated by Django 4.0.3 on 2025-04-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0074_alter_instability_event_llm_real_event_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instability_event',
            name='llm_year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instability_event',
            name='llm_year_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
