# Generated by Django 4.0.3 on 2025-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0075_instability_event_llm_year_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_event',
            name='inst_extent',
            field=models.CharField(blank=True, choices=[('1', '1. Highly localized: a neighborhood within a town or a village'), ('2', '2. A small town or rural district'), ('4', '4. A single province'), ('6', '6. Two or more provinces; or the polity capital'), ('8', '8. Several provinces and the capital'), ('10', '10. Whole polity')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='instability_event',
            name='llm_inst_extent',
            field=models.CharField(blank=True, choices=[('1', '1. Highly localized: a neighborhood within a town or a village'), ('2', '2. A small town or rural district'), ('4', '4. A single province'), ('6', '6. Two or more provinces; or the polity capital'), ('8', '8. Several provinces and the capital'), ('10', '10. Whole polity')], max_length=5, null=True),
        ),
    ]
