# Generated by Django 4.0.3 on 2025-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0076_alter_instability_event_inst_extent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instability_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
