# Generated by Django 4.0.3 on 2025-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0077_instability_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_ref',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
