# Generated by Django 4.0.3 on 2026-04-07 16:30

from django.db import migrations, models


def populate_instability_event_source(apps, schema_editor):
    InstabilityEvent = apps.get_model("crisisdb", "Instability_event")
    db_alias = schema_editor.connection.alias

    llm_fields = (
        "llm_name",
        "llm_description",
        "llm_inst_type",
        "llm_inst_extent",
        "llm_inst_intensity",
        "llm_real_event_check",
        "general_cot",
        "classification_cot",
        "sorokin_rationale",
    )

    for event in InstabilityEvent.objects.using(db_alias).all():
        has_llm_data = any(getattr(event, field, None) for field in llm_fields)
        has_llm_years = (
            getattr(event, "llm_year_from", None) is not None
            or getattr(event, "llm_year_to", None) is not None
        )
        has_llm_refs = event.inst_llm_ref.using(db_alias).exists()

        event.source = "llm" if has_llm_data or has_llm_years or has_llm_refs else "manual"
        event.save(using=db_alias, update_fields=["source"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crisisdb", "0078_alter_instability_ref_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="instability_event",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("llm", "LLM Import")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(populate_instability_event_source, noop_reverse),
        migrations.AlterField(
            model_name="instability_event",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("llm", "LLM Import")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
