# Generated by Django 4.0.3 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisisdb", "0079_instability_event_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="instability_event",
            name="is_macro_event",
            field=models.BooleanField(default=False),
        ),
    ]
