# Generated by Django 4.0.3 on 2026-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0080_instability_event_is_macro_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instability_event',
            name='inst_intensity',
            field=models.CharField(blank=True, choices=[('0', '0. Nobody is killed'), ('1', '1. One or few individuals killed'), ('2', '2. Tens killed'), ('3', '3. Tens or Hundreds killed'), ('4', '4. Hundreds killed'), ('5', '5. Hundreds or Thousands killed'), ('6', '6. Thousands killed'), ('7', '7. Thousands or Tens of thousands killed'), ('8', '8. Tens of thousands killed'), ('9', '9. Tens of thousands or Hundreds of thousands killed'), ('10', '10. Hundreds of thousands killed'), ('11', '11. Hundreds of thousands or Millions killed'), ('12', '12. Millions killed'), ('13', '13. Millions or Tens of millions killed'), ('14', '14. Tens of millions killed')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='instability_event',
            name='llm_inst_intensity',
            field=models.CharField(blank=True, choices=[('0', '0. Nobody is killed'), ('1', '1. One or few individuals killed'), ('2', '2. Tens killed'), ('3', '3. Tens or Hundreds killed'), ('4', '4. Hundreds killed'), ('5', '5. Hundreds or Thousands killed'), ('6', '6. Thousands killed'), ('7', '7. Thousands or Tens of thousands killed'), ('8', '8. Tens of thousands killed'), ('9', '9. Tens of thousands or Hundreds of thousands killed'), ('10', '10. Hundreds of thousands killed'), ('11', '11. Hundreds of thousands or Millions killed'), ('12', '12. Millions killed'), ('13', '13. Millions or Tens of millions killed'), ('14', '14. Tens of millions killed')], max_length=5, null=True),
        ),
    ]
