# Generated by Django 4.0.3 on 2025-01-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precious_metal_instance',
            options={},
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='drb_reviewed',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='expert_reviewed',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='is_disputed',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='is_uncertain',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='note',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='polity',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='private_comment',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='precious_metal_instance',
            name='year_to',
        ),
    ]
