# Generated by Django 4.0.3 on 2025-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_alter_precious_metal_instance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precious_metal_instance',
            name='metal',
            field=models.CharField(max_length=100),
        ),
    ]
