# Generated by Django 4.0.3 on 2025-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_prec_met_instance'),
        ('ec', '0003_alter_precious_metal_instance_metal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precious_metal_instance',
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='which_metals',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related_metals', related_query_name='%(app_label)s_%(class)ss', to='core.prec_met_instance'),
        ),
    ]
