# Generated by Django 4.0.3 on 2025-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_alter_precious_metal_common_people_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='common_people_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='common_people_consumption_tag',
            field=models.CharField(blank=True, choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='elite_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='elite_consumption_tag',
            field=models.CharField(blank=True, choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='ruler_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='ruler_consumption_tag',
            field=models.CharField(blank=True, choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UND', 'Undecided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='coded_value',
            field=models.CharField(choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='common_people_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='elite_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='ruler_consumption',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('uncoded', 'Uncoded'), ('absent', 'Absent'), ('unknown', 'Unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=50),
        ),
    ]
