# Generated by Django 4.0.3 on 2025-01-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0007_other_luxury_personal_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precious_metal',
            name='which_metals',
        ),
    ]
