# Generated by Django 4.0.3 on 2025-01-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0008_remove_precious_metal_which_metals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lux_fine_ceramic_wares',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='lux_precious_stone',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='lux_statuary',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_drink_alcohol',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_fabrics',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_food',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_glass_goods',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_manufactured_goods',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='luxury_spices_incense_and_dyes',
            name='which_metals',
        ),
        migrations.RemoveField(
            model_name='other_luxury_personal_items',
            name='which_metals',
        ),
    ]
