# Generated by Django 4.0.3 on 2025-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0009_remove_lux_fine_ceramic_wares_which_metals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lux_fine_ceramic_wares',
            name='name',
            field=models.CharField(default='Lux_fine_ceramic_wares', max_length=100),
        ),
        migrations.AlterField(
            model_name='lux_precious_metal',
            name='name',
            field=models.CharField(default='Lux_precious_metal', max_length=100),
        ),
        migrations.AlterField(
            model_name='lux_precious_stone',
            name='name',
            field=models.CharField(default='Lux_precious_stone', max_length=100),
        ),
        migrations.AlterField(
            model_name='lux_statuary',
            name='name',
            field=models.CharField(default='Lux_statuary', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_drink_alcohol',
            name='name',
            field=models.CharField(default='Luxury_drink_alcohol', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_fabrics',
            name='name',
            field=models.CharField(default='Luxury_fabrics', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_food',
            name='name',
            field=models.CharField(default='Luxury_food', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_glass_goods',
            name='name',
            field=models.CharField(default='Luxury_glass_goods', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_manufactured_goods',
            name='name',
            field=models.CharField(default='Luxury_manufactured_goods', max_length=100),
        ),
        migrations.AlterField(
            model_name='luxury_spices_incense_and_dyes',
            name='name',
            field=models.CharField(default='Luxury_spices_incense_and_dyes', max_length=100),
        ),
        migrations.AlterField(
            model_name='other_luxury_personal_items',
            name='name',
            field=models.CharField(default='Other_luxury_personal_items', max_length=100),
        ),
        migrations.AlterField(
            model_name='precious_metal',
            name='name',
            field=models.CharField(default='Precious_metal', max_length=100),
        ),
    ]
