# Generated by Django 4.0.3 on 2025-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement_population',
            name='tag',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=5),
        ),
    ]
