# Generated by Django 4.0.3 on 2025-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlm', '0003_tablet_seal_indicator_number_of_ziggurats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensive_wall',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='number_of_palaces',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='number_of_temples',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='number_of_ziggurats',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='seal_indicator',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settlement_population',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
