---
name: build_docker_image

on:
  push:
    branches: [dev]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/${ env.REPO }/seshat/tests-image:latest